IOVERSION 1
ipaddr=192.168.0.170
simulate=1
NumOfModules=21
Type=STB3610DDI
Name=2D4(1)
Connect1="Pallebane1 Foto" "Fotocelle sektion 1"
Connect2="Pallebane3 Foto" "Fotocelle sektion 3"
Connect3="Pallebane4 FotoRev" "Fotocelle 1 sektion 4"
Connect4="Pallebane3 FotoSecure" "FotoSecure i sektion3"
Connect5="Pallebane4 FotoTest" "Fotocelle 3 sektion 4"
Connect6="Pallebane5 Foto" "Fotocelle sektion 5"
Type=STB3610DDI
Name=2D5(2)
Connect1="Pallebane6 FotoRev" "Fotocelle 1 sektion 6"
Connect2="Pallebane6 FotoAlign" "Fotocelle 2 sektion 6"
Connect3="Pallebane6 FotoTest" "Fotocelle 3 sektion 6"
Connect4="Pallebane7 Foto" "Fotocelle sektion 7"
Connect5="Pallebane9 Foto" "Fotocelle sektion 9"
Connect6="ConveyorIn Foto1" "Plads 1 fri"
Type=STB3610DDI
Name=2D6(3)
Connect1="ConveyorIn Foto2" "Plads 2 fri"
Connect2="ConveyorIn Foto3" "Plads 3 fri"
Connect3="ConveyorIn Foto4" "Plads 4 fri"
Connect4="ConveyorIn Foto5" "Plads 5 fri"
Connect5="ConveyorIn kasseSkubber-" "reed kasseSkubber-"
Connect6="ConveyorIn kasseSkubber+" "reed kasseSkubber+"
Type=STB3610DDI
Name=2D7(4)
Connect1="ConveyorOut Foto6" "Plads 6 fri"
Connect2="ConveyorOut Foto7" "Plads 7 fri"
Connect3="KassePakker maskineLukket" "KassePakker maskine lukket"
Connect4="Pallebane4 C11Test" "Pallebane4 C11Test"
Connect5="ConveyorManuelIn foto2" "ConveyorManuelIn foto2"
Connect6="ConveyorManuelIn foto3" "ConveyorManuelIn foto3"
Type=STB3610DDI
Name=2D8(5)
Connect1="KassePakker conveyorFull" "KassePakker conveyorFull"
Connect2="" ""
Connect3="" ""
Connect4="KassePakker bakkeKlar2" "KassePakker bakke 2 klar"
Connect5="KassePakker bakkeKlar1" "KassePakker bakke 1 klar"
Connect6="KassePakker bredKasseklemmer-" "KassePakker reed bredKasseklemmer-"
Type=STB3610DDI
Name=3D1(6)
Connect1="" ""
Connect2="KassePakker smalKasseklemmer-" "KassePakker smalKasseklemmer-"
Connect3="ConveyorManuelIn foto1" "ConveyorManuelIn foto1"
Connect4="KassePakker langKasseLift-" "KassePakker langKasseLift-"
Connect5="ConveyorFeed foto" "ConnveyorFeed foto"
Connect6="KassePakker kortKasseLift-" "KassePakker kortKasseLift-"
Type=STB3610DDI
Name=3D2(7)
Connect1="KassePakker kortKasseLift+" "KassePakker kortKasseLift+"
Connect2="KassePakker kortBufferSkub+" "KassePakker kortBufferSkub+"
Connect3="KassePakker kortBufferSkub-" "KassePakker kortBufferSkub-"
Connect4="KassePakker langBufferSkub-" "KassePakker langBufferSkub-"
Connect5="KassePakker langBufferSkub+" "KassePakker langBufferSkub+"
Connect6="KassePakker bundOpen1-" "KassePakker bundOpen1-"
Type=STB3610DDI
Name=3D3(8)
Connect1="KassePakker bundOpen1+" "KassePakker bundOpen1+"
Connect2="KassePakker bundOpen2-" "KassePakker bundOpen2-"
Connect3="KassePakker bundOpen2+" "KassePakker bundOpen2+"
Connect4="ConveyorOut Foto17" "Foto17 ved udgang af KassePakker"
Connect5="KassePakker kasseKlar" "KassePakker kasseklar"
Connect6="UniChain skumKlapFoto" "UniChain skumKlapFoto"
Type=STB3610DDI
Name=3D4(9)
Connect1="ConveyorManuelOut button" "ConveyorManuelOut button"
Connect2="KassePakker ProduktMolester-" "KassePakker ProduktMolester-"
Connect3="checkWeigher fotoIn" "checkWeigher fotoIn"
Connect4="PrinterStop" "PrinterLabel stop"
Connect5="" ""
Connect6="ConveyorIn endestop" "ConveyorIn endestop"
Type=STB3610DDI
Name=3D9(10)
Connect1="BakkeTipper Foto" "BakkeTipper Foto"
Connect2="InLiner Foto" "InLiner Foto"
Connect3="ProduktInd Foto" "ProduktInd Foto"
Connect4="checkWeigher fotoOut" "checkWeigher fotoOut"
Connect5="" ""
Connect6="" ""
Type=STB3600DDO
Name=3D10(11)
Connect1="ConveyorIn Enable" "ConveyorIn Enable"
Connect2="ConveyorOut Enable" "ConveyorOut Enable"
Connect3="checkWeigher motorEnable" "checkWeigher motorEnable"
Connect4="checkWeigher setZero" "checkWeigher setZero"
Connect5="KassePakker bakkeVender" "KassePakker bakkeVender"
Connect6="KassePakker MolestProdukt" "KassePakker saks"
Type=STB3600DDO
Name=3D5(12)
Connect1="ConveyorIn holdKasse1" "ConveyorIn hold kasse 1"
Connect2="ConveyorIn holdKasse2" "ConveyorIn hold kasse 2"
Connect3="ConveyorIn kasseSkubberUd" "ConveyorIn kasseskubber ud"
Connect4="" ""
Connect5="KassePakker bredKasseKlem" "KassePakker bred Kasseklem"
Connect6="KassePakker langBufferSkub2" "KassePakker langBuffer2 skub"
Type=STB3600DDO
Name=3D6(13)
Connect1="KassePakker smalKasseKlem" "KassePakker smal Kasseklem"
Connect2="ManuelRullebane lift" "ManuelRullebane lift" 
Connect3="KassePakker langKasseLiftOp" "KassePakker langKasseLift op"
Connect4="KassePakker skubbePladsMotor" "KassePakker skubbePladsMotor"
Connect5="KassePakker kortKasseLiftOp" "KassePakker kortKasseLift op"
Connect6="InLiner Motor" "InLiner Motor"
Type=STB3600DDO 
Name=3D7(14)
Connect1="KassePakker kortBufferSkub" "KassePakker kortBuffer skub"
Connect2="KassePakker langBufferSkub" "KassePakker langBuffer skub"
Connect3="KassePakker bundOpen1" "KassePakker bundOpen1"
Connect4="KassePakker bundOpen2" "KassePakker bundOpen2"
Connect5="checkWeigher productOut" "checkWeigher productOut"
Connect6="KassePakker langBufferInd" "KassePakker langBuffer ind"
Type=STB3600DDO 
Name=3D8(15)
Connect1="Pallebane4 Cyl" "Sektor 4 lÃ¸ft"
Connect2="Pallebane6 Cyl" "Sektor 6 lÃ¸ft"
Connect3="KassePakker bundClose1" "KassePakker bundClose1"
Connect4="KassePakker bundClose2" "KassePakker bundClose2"
Connect5="stopFlowPakker" "Stop Flowpakker"
Connect6="UniChain skumKlap" "UniChain skumKlap"
Type=EPI2145
Name=4E1(16)
Connect1="Pallebane1 Motor" "Motor i sektor 1"
Connect2="" ""
Connect3="Pallebane3 Motor" "Motor i sektor 3"
Connect4="" ""
Connect5="Pallebane4 Chain" "Pallekryds ind venstre sektor 4"
Connect6="" ""
Connect7="Pallebane5 Motor" "Mellemstykke for pallekryds sektor 5"
Connect8="" ""
Type=EPI2145
Name=4E2(17)
Connect1="Pallebane6 Chain" "Pallekryds ud hÃ¸jre sektor 6"
Connect2="" ""
Connect3="Pallebane7 Motor" "Motor i sektor 7"
Connect4="" ""
Connect5="Pallebane9 Motor" "Motor i sektor 9"
Connect6="" ""
Connect7="ConveyorIn Motor" "ConveyorIn Motor"
Connect8="" ""
Type=EPI2145
Name=4E3(18)
Connect1="ConveyorOut Motor" "ConveyorOut Motor"
Connect2="" ""
Connect3="KassePakker Motor" "KassePakker Motor"
Connect4="" ""
Connect5="ConveyorManuelIn Motor" "ConveyorManuelIn Motor"
Connect6="" ""
Connect7="ConveyorManuelOut Motor" "ConveyorManuelOut Motor"
Connect8="" ""
Type=EPI2145
Name=4E4(19)
Connect1="Pallebane4 MotorFwd" "Motor i sektor 4 Fwd/Rev."
Connect2="Pallebane4 MotorRev" "Motor i sektor 4 reverse"
Connect3="Pallebane6 MotorFwd" "Motor i sektor 6 Fwd/Rev."
Connect4="Pallebane6 MotorRev" "Motor i sektor 6 reverse"
Connect5="BakkeTipper Motor" "BakkeTipper Motor"
Connect6="" ""
Connect7="UniChain Motor" "UniChain Motor"
Connect8="" ""
Type=EPI2145
Name=4E4(20)
Connect1="ConveyorFeed Motor" "ConveyorFeed Motor"
Connect2="" ""
Connect3="checkWeigher motor" "checkWeigher motor"
Connect4="" ""
Connect5="ProduktInd Motor" "ProduktInd Motor"
Connect6="" ""
Connect7="" ""
Connect8="" ""
Type=AVI1270
Name=4E5(21)
InWord1="checkWeigher cell1data" "checkWeigher cell1data"
InWord2="checkWeigher cell1status" "checkWeigher cell1status"
InWord3="" ""
InWord4="" ""
