//Code generated by bxbuilder (c) LMS 2002 
// formStdRunCode.c
#include "Bx.h"
#include "formStdRun.h"

BX_VOID formStdRunInit(HBOX hBox)
{
  //PIXMAP ID = 12
  BxSendMessage(BxGetDlgItem(hBox, FORMSTDRUN_TEXTLABEL1), BSTM_SETIMAGE, (BX_WPARAM)BxResourceLoadBxBitmap(12, "data/robostacker.bxr"), 0);
}

BX_VOID formStdRunUpdate(HBOX hBox)
{
}

