//Code generated by bxbuilder (c) LMS 2002 
// formStdRun.h
#if !defined(FORMSTDRUN_H)
#define FORMSTDRUN_H
#include "Bx.h"
#include "formStdRunUser.h"
#define FORMSTDRUN_CMDMENU 1
extern BX_BOOL formStdRun_cmdMenu_Click(HBOX hBox);
#define FORMSTDRUN_CMDSPEED 2
extern BX_BOOL formStdRun_cmdSpeed_Click(HBOX hBox);
#define FORMSTDRUN_TEXTLABEL2_2_2 3
#define FORMSTDRUN_CMDRUN 4
extern BX_BOOL formStdRun_cmdRun_Click(HBOX hBox);
#define FORMSTDRUN_CMDSTOP 5
extern BX_BOOL formStdRun_cmdStop_Click(HBOX hBox);
#define FORMSTDRUN_TEXTLABEL2_2 6
#define FORMSTDRUN_TEXTLABEL1 7
#define FORMSTDRUN_GROUPBOX1_2_2 8
#define FORMSTDRUN_LABINFOTYPE 9
#define FORMSTDRUN_LABINFO 10
#define FORMSTDRUN_LABTIME 11
#define FORMSTDRUN_LAB1_4 12
extern BX_CHAR formStdRunText[][MAXLANGUAGE][255];
extern BOXSTRUCT formStdRun[];
extern BX_BOOL formStdRunProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formStdRunUpdate(HBOX hBox);
extern BX_VOID formStdRunInit(HBOX hBox);
#endif // FORMSTDRUN_H
