//Code generated by bxbuilder (c) LMS 2002 
// formStdRunUser.c
#include "Bx.h"
#include "formStdRun.h"

static FONT strFont;
int gram = 448;
static BXSCROLLBARSTRUCT tmps;

static BXMENUSTRUCT pBxMainMenu;

BX_BOOL formStdRunUserInit(HBOX hBox,BX_LPARAM lParam)
{

  BxScrollBar_Create( BxGetDlgItem(hBox, FORMSTDRUN_LABINFO), &tmps, BSB_HORIZONTAL | BSB_NOCAPTION);
  BxScrollBar_SetRange( BxGetDlgItem(hBox, FORMSTDRUN_LABINFO), 0, 10);

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTDRUN_CMDSPEED));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTDRUN_CMDSPEED), 100.0);

//  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTDRUN_LABINFO));
//  BxOpenFont(&strFont, "data/decker.ttf", 100);
//  BxSetFont(BxGetDC(BxGetDlgItem(hBox, FORMSTDRUN_LABINFO)), &strFont);
//  BxSetBoxText(BxGetDlgItem(hBox, FORMSTDRUN_LABINFO), "448");
  
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTDRUN_LABINFOTYPE));
  BxSetBoxText(BxGetDlgItem(hBox, FORMSTDRUN_LABINFOTYPE), "Bx for Windows XP");

  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTDRUN_LABTIME));
  BxSetBoxText(BxGetDlgItem(hBox, FORMSTDRUN_LABTIME), "00:00:00");

  BxShowBox(BxGetDlgItem(hBox, FORMSTDRUN_CMDSPEED), FALSE );
//  BxShowBox(BxGetDlgItem(hBox, FORMSTDRUN_TEXTLABEL2_2_2), FALSE );

  BxSendMessage(BxGetDlgItem(hBox, FORMSTDRUN_TEXTLABEL2_2_2), BSTM_SETIMAGE, (BX_WPARAM)BxLoadImage("data/BxLogo.png"), 0);

  return TRUE;
}

BX_BOOL formStdRunUserUpdate(HBOX hBox)
{  
  char s[25];
  
  sprintf(s,"%d", gram++);
  
//  BxSetBoxText(BxGetDlgItem(hBox, FORMSTDRUN_LABINFO), s);
  return TRUE;
}

BX_BOOL formStdRun_cmdSpeed_Click(HBOX hBox)
{
/*
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMSTDRUN_CMDSPEED)));
  BxVirtNumBox_SetFloatLimits(1.0, 100.0);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMSTDRUN_CMDSPEED), BxVirtNumBox_GetFloatValue());
//    SetSpeedFactor(BxVirtNumBox_GetFloatValue()/100.0);
  }
*/
  return TRUE;
}

BX_BOOL formStdRun_cmdRun_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formStdRun_cmdStop_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdAxis_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdInOut_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdDistIO_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdSTMCtrl_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdJogAxis_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdJogIk_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdFixPoints_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdStatus_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdSystem_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdLog_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdSetupVision_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdAutoHome_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdMoveHomeA_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdMoveHomeB_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdMoveHomeC_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdMoveHomeD_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdMoveHomeE_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdMoveHomeF_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdSetZeroA_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdSetZeroB_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdSetZeroC_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdSetZeroD_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdSetZeroE_Click(HBOX hBox)
{
  return TRUE;
}
BX_BOOL formTools_cmdSetZeroF_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdSetZeroTool_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formTools_cmdSetupSysParam_Click(HBOX hBox)
{
  return TRUE;
}


BX_BOOL formTools_cmdDebug_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formStd_cmdProgram_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formStd_cmdDummy_Click(HBOX hBox)
{

  BXFILEDLGSTRUCT FDlg = {".",};
  BxFileDialog( hBox, &FDlg );

  return TRUE;
}

BX_BOOL formStd_cmdExit_Click(HBOX hBox)
{
  BxEndDialog(hBox, FALSE);
  return FALSE;
}

BX_BOOL formStdRun_cmdMenu_Click(HBOX hBox)
{
  HBOX hBx, ToolBx, ToolJogBx, hOptions, hDummy, hExDum, hTest;

  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMSTDRUN_CMDMENU), &pBxMainMenu);

  hOptions = BxMenu_Add(hBx ,"Setup", SUB, NULL, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 1", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 2", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 3", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 4", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 5", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 6", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hOptions ,"Option 7", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  hDummy = BxMenu_Add(hOptions ,"Option 8", SUB, formStd_cmdDummy_Click, TRUE, NULL);
  hExDum = BxMenu_Add(hDummy ,"Dummy 1", SUB, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 2", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 3", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 4", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 5", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 6", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 7", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 8", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 9", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dummy 10", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hDummy ,"Dette er en Dummy 11", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hExDum ,"Dummy 9", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hExDum ,"Dummy 10", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hExDum ,"Dummy 11", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hBx ,"Program", MENU, formStd_cmdProgram_Click, TRUE, NULL);
  ToolBx = BxMenu_Add(hBx , "Tools", SUB, NULL, TRUE, NULL);
  ToolJogBx = BxMenu_Add(ToolBx ,"Jog axis", SUB, NULL, TRUE, NULL);
  BxMenu_Add(ToolJogBx ,"Jog I.K.", MENU, formTools_cmdJogIk_Click, TRUE, NULL);
  hTest = BxMenu_Add(hBx ,"Option 6", SUB, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hTest ,"Test 1", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hTest ,"Test 2", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hTest ,"Test 3", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hTest ,"Test 4", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hBx ,"Option 7", MENU, formStd_cmdDummy_Click, TRUE, NULL);
  BxMenu_Add(hBx ,"Exit", MENU, formStd_cmdExit_Click, TRUE, NULL);

  return DoMenu(BxGetDlgItem(hBox, FORMSTDRUN_CMDMENU));
}

