//Code generated by bxbuilder (c) LMS 2002 
// formStdRun.c
#include "Bx.h"
#include "formStdRun.h"

BOXSTRUCT formStdRun[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formStdRun[1], NULL}
 ,{FORMSTDRUN_CMDMENU,{670,490,789,579},BUTTON,"Menu",BBS_PUSHBUTTON|BXS_VISIBLE,&formStdRun[2], &formStdRun[0]}
 ,{FORMSTDRUN_CMDSPEED,{10,490,119,579},BUTTON,"50.0",BBS_PUSHBUTTON|BXS_VISIBLE,&formStdRun[3], &formStdRun[0]}
 ,{FORMSTDRUN_TEXTLABEL2_2_2,{10,450,119,484},STATIC,"Hastighed",BSS_CENTER|BXS_VISIBLE,&formStdRun[4], &formStdRun[0]}
 ,{FORMSTDRUN_CMDRUN,{390,490,509,579},BUTTON,"Kør",BBS_PUSHBUTTON|BXS_VISIBLE,&formStdRun[5], &formStdRun[0]}
 ,{FORMSTDRUN_CMDSTOP,{520,490,639,579},BUTTON,"Stop",BBS_PUSHBUTTON|BXS_VISIBLE,&formStdRun[6], &formStdRun[0]}
 ,{FORMSTDRUN_TEXTLABEL2_2,{10,5,259,44},STATIC,"roboStacker RS2050",BXS_VISIBLE,&formStdRun[7], &formStdRun[0]}
 ,{FORMSTDRUN_TEXTLABEL1,{660,10,788,54},STATIC,"",BSS_BITMAP|BXS_VISIBLE,&formStdRun[8], &formStdRun[0]}
 ,{FORMSTDRUN_GROUPBOX1_2_2,{10,40,789,429},STATIC,"Information",BSS_WHITEFRAME|BXS_VISIBLE,&formStdRun[9], &formStdRun[0]}
 ,{FORMSTDRUN_LABINFOTYPE,{50,150,739,184},STATIC,"Information type",BSS_CENTER|BXS_VISIBLE,&formStdRun[10], &formStdRun[0]}
 ,{FORMSTDRUN_LABINFO,{40,180,739,264},STATIC,"Information",BXS_BORDER|BSS_CENTER|BXS_VISIBLE,&formStdRun[11], &formStdRun[0]}
 ,{FORMSTDRUN_LABTIME,{590,370,769,419},STATIC,"00:00:00",BXS_BORDER|BSS_CENTER|BXS_VISIBLE,&formStdRun[12], &formStdRun[0]}
 ,{FORMSTDRUN_LAB1_4,{490,380,559,414},STATIC,"Tid:",BXS_VISIBLE,&formStdRun[13], &formStdRun[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formStdRun[0]}
};

BX_BOOL formStdRunProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formStdRunUpdate(hBox);
				return formStdRunUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formStdRunInit(hBox);
				return formStdRunUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMSTDRUN_CMDMENU:
             return formStdRun_cmdMenu_Click(hBox);
         case FORMSTDRUN_CMDSPEED:
             return formStdRun_cmdSpeed_Click(hBox);
         case FORMSTDRUN_CMDRUN:
             return formStdRun_cmdRun_Click(hBox);
         case FORMSTDRUN_CMDSTOP:
             return formStdRun_cmdStop_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
