all:
	make -C Bx
	make -C libmpnrobot/libmpnrobot
	make -C hmi
	make -C io
	make -C stm
	make -C rs
clean:
	make -C Bx clean
	make -C libmpnrobot/libmpnrobot clean
	make -C hmi clean
	make -C io clean
	make -C stm clean
	make -C rs clean
