MACVERSION 1
ipaddr=192.168.0.201
port=4002
simulate=0
NumOfMotors=1
Name=KasseStop
Address=255
Init37=0 "START_MODE" "Passive startmode" word
Init36=0x200 "CNTRL_BITS" "Resync position" word
Init2=0 "MODE_REG" "Passive mode" word
Init3=0 "P_SOLL" "Commanded position" longint
Init10=0 "P_IST" "Actual motor position set to zero" longint
InBits35="KasseStop Status" "ERR_STAT" word
Bit0="KasseStop Overload" "I2t error"
Bit1="KasseStop FLW_ERR" "Follow error"
Bit2="KasseStop FNC_ERR" "Function error"
Bit3="KasseStop UIT_ERR" "Regenerative error"
Bit4="KasseStop IN_POS"  "In position"
Bit5="KasseStop ACC_FLAG" "Accelerating"
Bit6="KasseStop DEC_FLAG" "Decelerating"
Bit7="KasseStop PLIM_ERR" "Position limits error"
EndBits
InOut10="KasseStop Curpos" "P_IST" longint
Out35="KasseStop Status" "ERR_STAT" word
Out13="KasseStop Load Factor" "KVOUT" fixed8
InOut2="KasseStop Mode" "MODE_REG" word
Out3="KasseStop MacSetpoint" "P_SOLL" longint
Out5="KasseStop Maxvel" "V_SOLL" shortint factor=0.47687172150
Out6="KasseStop Maxacc" "A_SOLL" word factor=248.320
In12="KasseStop Curvel" "V_IST" shortint factor=7.6289
Out40="KasseStop Homevel" "V_HOME" shortint factor=0.47687172150
Out41="KasseStop Hometorque" "T_HOME" shortint factor=0.125
Out42="KasseStop Home Mode" "HOME_MODE" word
