IOVERSION 1
ipaddr=192.168.0.170
simulate=0
NumOfModules=3
Type=DDI3610
Name=aa
Connect1="S1 Extern Sync In" "Start/stop vejebånd"
Connect2="S1 Foto Product In" "FotocelleIn 11B1"
Connect3="S1 Foto Product Out" "FotocelleOut 11B3"
Connect4="S1 Power On" ""
Connect5="" ""
Connect6="" ""
Type=DDO3600
Name=aa
Connect1="S1 Motor" "Start vejebånd"
Connect2="S1 Product reject" "Produkt udkaster"
Connect3="S1 Zero" "Nulstil"
Connect4="S1 Extern Sync Out" "Skaf produkt"
Connect5="" ""
Connect6="" ""
Type=AVI1270
Name=dd
InWord1="checkWeigher cell1data"
InWord2="checkWeigher cell1status"
InWord3=""
InWord4=""
