IOVERSION 1
ipaddr=192.168.0.172
simulate=0
NumOfModules=13
Type=EHC3020
Name=D1304
InWord1="LangBufferSkub IO Data" "LangBufferSkub IO Data"
InWord2="LangBufferSkub IO Status" "LangBufferSkub IO Status"
InWord3="LangBufferSkub Counter Status" "LangBufferSkub Counter Status"
InWord4="LangBufferSkub Compare Status" "LangBufferSkub Compare Status"
InWord5="LangBufferSkub Encoder" "LangBufferSkub Encoder"
InWord6="LangBufferSkub Capture Value" "LangBufferSkub Capture Value"
OutWord1="LangBufferSkub Output Data" "LangBufferSkub Output Data"
OutWord2="LangBufferSkub Input Validation" "LangBufferSkub Input Validation"
OutWord3="LangBufferSkub Direct" "LangBufferSkub Direct"
OutWord4="LangBufferSkub Upper Threshold" "LangBufferSkub Upper Threshold"
OutWord5="LangBufferSkub Lower Threshold" "LangBufferSkub Lower Threshold"
Type=EHC3020
Name=D1305
InWord1="BufferPlads IO Data" "BufferPlads IO Data"
InWord2="BufferPlads IO Status" "BufferPlads IO Status"
InWord3="BufferPlads Counter Status" "BufferPlads Counter Status"
InWord4="BufferPlads Compare Status" "BufferPlads Compare Status"
InWord5="BufferPlads Encoder" "BufferPlads Encoder"
InWord6="BufferPlads Capture Value" "BufferPlads Capture Value"
OutWord1="BufferPlads Output Data" "BufferPlads Output Data"
OutWord2="BufferPlads Input Validation" "BufferPlads Input Validation"
OutWord3="BufferPlads Direct" "BufferPlads Direct"
OutWord4="BufferPlads Upper Threshold" "BufferPlads Upper Threshold"
OutWord5="BufferPlads Lower Threshold" "BufferPlads Lower Threshold"
Type=EHC3020
Name=D1306
InWord1="KasseLift IO Data" "KasseLift IO Data"
InWord2="KasseLift IO Status" "KasseLift IO Status"
InWord3="KasseLift Counter Status" "KasseLift Counter Status"
InWord4="KasseLift Compare Status" "KasseLift Compare Status"
InWord5="KasseLift Encoder" "KasseLift Encoder"
InWord6="KasseLift Capture Value" "KasseLift Capture Value"
OutWord1="KasseLift Output Data" "KasseLift Output Data"
OutWord2="KasseLift Input Validation" "KasseLift Input Validation"
OutWord3="KasseLift Direct" "KasseLift Direct"
OutWord4="KasseLift Upper Threshold" "KasseLift Upper Threshold"
OutWord5="KasseLift Lower Threshold" "KasseLift Lower Threshold"
Type=DDI3610
Name=D1307
InConnect1="Emergency OK"
InConnect2="ProduktConveyor_1 HZOK"
InConnect3="ProduktConveyor1 Foto1"
InConnect4="ProduktConveyor1 Foto2"
InConnect5="ProduktConveyor2 Foto2"
InConnect6="ProduktConveyor2 Foto1"
Type=DDI3610
Name=D1308
InConnect1="Produkt Buffer Plads Foto 1 bruges ikke endnu"
InConnect2="Produkt Buffer Plads Foto 2 bruges ikke endnu"
InConnect3="Produkt Buffer Plads Foto 3 bruges ikke endnu"
InConnect4="Produkt Buffer Plads Foto 4 bruges ikke endnu"
InConnect5="LangBufferSkub HZOK"
InConnect6="ProduktConveyor_2 HZOK"
Type=DDI3610
Name=D1801
InConnect1="LangBufferSkub HomeSensor"
InConnect2="LangBufferSkub Klap-"
InConnect3="BufferPlads HZOK"
InConnect4="BufferPlads HomeSensor"
InConnect5="KortBufferSkub Left Inde"
InConnect6="KortBufferSkub Right Inde"
Type=DDI3610
Name=D1802
InConnect1="KasseLoader Foto"
InConnect2="Buffer Plads Reed 3, ikke monteret"
InConnect3="KasseInLiner Foto"
InConnect4="KasseLift Foto"
InConnect5="KasseLift HZOK"
InConnect6="KasseCentrering+"
Type=DDI3610
Name=D1803
InConnect1="Next Sync In"
InConnect2="Prev Sync In"
InConnect3=""
InConnect4=""
InConnect5=""
InConnect6=""
Type=DDO3600
Name=D1804
OutConnect1="Styrespaending OK"
OutConnect2="ProductConveyor2 Motor Enable"
OutConnect3=""
OutConnect4="ProductConveyor1 Motor Enable"
OutConnect5="LangBufferSkub Motor Enable"
OutConnect6="LangBufferSkub Klap"
Type=DDO3600
Name=D1805
OutConnect1="BufferPlads Motor Enable"
OutConnect2="KortBufferSkubber Left 1"
OutConnect3="KortBufferSkubber Left 2"
OutConnect4="KortBufferSkubber Right 1"
OutConnect5="KortBufferSkubber Right 2"
OutConnect6="KasseSkubber1"
Type=DDO3600
Name=D1806
OutConnect1="KasseSkubber2"
OutConnect2="KasseLift Brake Release"
OutConnect3="KasseCentrer"
OutConnect4="KasseStop"
OutConnect5="Green Light"
OutConnect6="Yellow Light"
Type=DDO3600
Name=D1807
OutConnect1="KasseLift Motor Enable"
OutConnect2="Product Sync"
OutConnect3="Prev Sync Out"
OutConnect4="Red Light"
OutConnect5=""
OutConnect6=""
Type=EPI2145
Name=D1808
Connect1="KasseInLiner Motor"
Connect2=""
Connect3="KasseLift Conveyor Motor"
Connect4=""
Connect5="KasseLift Vibrator"
Connect6=""
Connect7="KasseLoader Motor"
Connect8=""
Ready1="KasseInliner Motor Ready"
Tripped1="KasseInliner Motor Tripped"
Energized1="KasseInliner Motor Energized"
Ready2="KasseLift Conveyor Motor Ready"
Tripped2="KasseLift Conveyor Motor Tripped"
Energized2="KasseLift Conveyor Motor Energized"
Ready3="KasseLift Vibrator Ready"
Tripped3="KasseLift Vibrator Tripped"
Energized3="KasseLift Vibrator Energized"
Ready4="KasseLoader Motor Ready"
Tripped4="KasseLoader Motor Tripped"
Energized4="KasseLoader Motor Energized"
