//Code generated by bxbuilder (c) LMS 2002 
// formPMCtrlUser.c
#include "Bx.h"
#include "formPMCtrl.h"
#include "dioc.h"

BX_BOOL formPMCtrlUserInit(HBOX hBox,BX_LPARAM lParam)
{
/*  if(idata[INPUT_PM_1] & PM_REED_BOTTOM)
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1BOTTOM), TRUE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2BOTTOM), TRUE);
	}
	else	
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1BOTTOM), FALSE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2BOTTOM), FALSE);
	}
	
  if(idata[INPUT_PM_2] & PM_REED_MID_L)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1MID), TRUE);
	else	
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1MID), FALSE);
  
	if(idata[INPUT_PM_2] & PM_REED_MID_R)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2MID), TRUE);
	else	
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2MID), FALSE);
  
	if(idata[INPUT_PM_1] & PM_REED_TOP)
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1TOP), TRUE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2TOP), TRUE);
	}
	else
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1TOP), TRUE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2TOP), TRUE);
	}
	
	if(idata[INPUT_PM_3] & PM_FOTO_PALLE_NEDE)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO1), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO1), FALSE);
		
	if(idata[INPUT_PM_3] & PM_FOTO_PALLE_KLAR)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO2), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO2), TRUE);

  if(idata[INPUT_PM_2] & PM_REED_SLIP)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_OUT), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_OUT), FALSE);
		
  if(idata[INPUT_PM_2] & PM_REED_GRIB)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_IN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_IN), FALSE);

  if(odata[OUTPUT_PM-1] & PM_CYLGRIB_SLIP)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPOUT), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPOUT), FALSE);
  
	if(odata[OUTPUT_PM-1] & PM_CYLGRIB_GRIB)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPIN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPIN), FALSE);
  
	if(odata[OUTPUT_PM-1] & PM_CYL_UP_L)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1UP), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1UP), FALSE);
	
	if(odata[OUTPUT_PM-1] & PM_CYL_UP_R)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2UP), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2UP), FALSE);
	
	if(odata[OUTPUT_PM-1] & PM_CYL_DOWN_L)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1DOWN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1DOWN), FALSE);
		
	if(odata[OUTPUT_PM-1] & PM_CYL_DOWN_R)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2DOWN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2DOWN), FALSE);
                     */
  return TRUE;
}

BX_BOOL formPMCtrlUserUpdate(HBOX hBox)
{
/*  if(idata[INPUT_PM_1] & PM_REED_BOTTOM)
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1BOTTOM), TRUE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2BOTTOM), TRUE);
	}
	else	
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1BOTTOM), FALSE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2BOTTOM), FALSE);
	}
	
  if(idata[INPUT_PM_2] & PM_REED_MID_L)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1MID), TRUE);
	else	
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1MID), FALSE);
  
	if(idata[INPUT_PM_2] & PM_REED_MID_R)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2MID), TRUE);
	else	
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2MID), FALSE);
  
	if(idata[INPUT_PM_1] & PM_REED_TOP)
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1TOP), TRUE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2TOP), TRUE);
	}
	else
	{
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1TOP), TRUE);
  	BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2TOP), TRUE);
	}
	
	if(idata[INPUT_PM_3] & PM_FOTO_PALLE_NEDE)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO1), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO1), FALSE);
		
	if(idata[INPUT_PM_3] & PM_FOTO_PALLE_KLAR)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO2), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKPHOTO2), TRUE);

  if(idata[INPUT_PM_2] & PM_REED_SLIP)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_OUT), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_OUT), FALSE);
		
  if(idata[INPUT_PM_2] & PM_REED_GRIB)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_IN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIP_IN), FALSE);

  if(odata[OUTPUT_PM-1] & PM_CYLGRIB_SLIP)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPOUT), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPOUT), FALSE);
  
	if(odata[OUTPUT_PM-1] & PM_CYLGRIB_GRIB)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPIN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKGRIPIN), FALSE);
  
	if(odata[OUTPUT_PM-1] & PM_CYL_UP_L)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1UP), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1UP), FALSE);
	
	if(odata[OUTPUT_PM-1] & PM_CYL_UP_R)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2UP), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2UP), FALSE);
	
	if(odata[OUTPUT_PM-1] & PM_CYL_DOWN_L)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1DOWN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL1DOWN), FALSE);
		
	if(odata[OUTPUT_PM-1] & PM_CYL_DOWN_R)
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2DOWN), TRUE);
	else
		BxSetCheck(BxGetDlgItem(hBox, FORMPMCTRL_CHKCYL2DOWN), FALSE);
                  */
	return TRUE;
}

BX_BOOL formPMCtrl_chkGripOut_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkGripIn_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkGrip_Out_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkPhoto1_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkPhoto2_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkGrip_In_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl1Up_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl1Down_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl1Bottom_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl1Mid_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl1Top_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl2Top_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl2Mid_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl2Bottom_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl2Up_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_chkCyl2Down_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPMCtrl_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);
	return FALSE;
}

BX_BOOL formPMCtrl_cmdReset_Click(HBOX hBox)
{
  return TRUE;
}

