//Code generated by bxbuilder (c) LMS 2002 
// formAVOMod.c
#include "Bx.h"
#include "formAVOMod.h"

BOXSTRUCT formAVOMod[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formAVOMod[1], NULL}
 ,{FORMAVOMOD_TEXTLABEL2_2_2,{20,70,99,104},STATIC,"Name :",BXS_VISIBLE,&formAVOMod[2], &formAVOMod[0]}
 ,{FORMAVOMOD_CMDCLOSE,{650,480,779,579},BUTTON,"Close",BBS_PUSHBUTTON|BXS_VISIBLE,&formAVOMod[3], &formAVOMod[0]}
 ,{FORMAVOMOD_LABMODNAME,{190,70,619,104},STATIC,"2D4 - Module",BXS_BORDER|BXS_VISIBLE,&formAVOMod[4], &formAVOMod[0]}
 ,{FORMAVOMOD_LABTYPE,{280,10,529,44},STATIC,"Advantys modules",BSS_CENTER|BXS_VISIBLE,&formAVOMod[5], &formAVOMod[0]}
 ,{FORMAVOMOD_TEXTLABEL1,{20,160,49,194},STATIC,"1",BXS_VISIBLE,&formAVOMod[6], &formAVOMod[0]}
 ,{FORMAVOMOD_TEXTLABEL2,{20,210,49,244},STATIC,"2",BXS_VISIBLE,&formAVOMod[7], &formAVOMod[0]}
 ,{FORMAVOMOD_LABCONNECT2,{190,210,619,244},STATIC,"Connect2",BXS_BORDER|BXS_VISIBLE,&formAVOMod[8], &formAVOMod[0]}
 ,{FORMAVOMOD_LABCONNECT1,{190,160,619,194},STATIC,"Connect1",BXS_BORDER|BXS_VISIBLE,&formAVOMod[9], &formAVOMod[0]}
 ,{FORMAVOMOD_DATA1,{60,160,170,199},BUTTON,"Data1",BBS_PUSHBUTTON|BXS_VISIBLE,&formAVOMod[10], &formAVOMod[0]}
 ,{FORMAVOMOD_DATA2,{60,210,170,249},BUTTON,"Data2",BBS_PUSHBUTTON|BXS_VISIBLE,&formAVOMod[11], &formAVOMod[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formAVOMod[0]}
};

BX_BOOL formAVOModProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formAVOModUpdate(hBox);
				return formAVOModUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formAVOModInit(hBox);
				return formAVOModUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMAVOMOD_CMDCLOSE:
             return formAVOMod_cmdClose_Click(hBox);
         case FORMAVOMOD_DATA1:
             return formAVOMod_Data1_Click(hBox);
         case FORMAVOMOD_DATA2:
             return formAVOMod_Data2_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
