//Code generated by bxbuilder (c) LMS 2002 
// formPMCtrl.c
#include "Bx.h"
#include "formPMCtrl.h"

BOXSTRUCT formPMCtrl[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formPMCtrl[1], NULL}
 ,{FORMPMCTRL_TEXTLABEL2_2,{10,10,179,44},STATIC,"Controls for PM",BXS_VISIBLE,&formPMCtrl[2], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKGRIPOUT,{410,320,529,379},BUTTON,"Out",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[3], &formPMCtrl[0]}
 ,{FORMPMCTRL_LABOUT_2_2,{350,230,449,264},STATIC,"Grip",BSS_CENTER|BXS_VISIBLE,&formPMCtrl[4], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKGRIPIN,{280,320,399,379},BUTTON,"In",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[5], &formPMCtrl[0]}
 ,{FORMPMCTRL_LABPHOTO2,{280,470,469,504},STATIC,"Pallet ready",BXS_VISIBLE,&formPMCtrl[6], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKGRIP_OUT,{440,280,499,309},BUTTON,"Out",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[7], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKPHOTO1,{500,410,550,460},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[8], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKPHOTO2,{500,470,550,520},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[9], &formPMCtrl[0]}
 ,{FORMPMCTRL_LABPHOTO1,{280,420,469,454},STATIC,"Pallet missing",BXS_VISIBLE,&formPMCtrl[10], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKGRIP_IN,{310,280,369,309},BUTTON,"In",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[11], &formPMCtrl[0]}
 ,{FORMPMCTRL_LABOUT_2,{570,80,699,114},STATIC,"Stabel cyl 2",BSS_RIGHT|BXS_VISIBLE,&formPMCtrl[12], &formPMCtrl[0]}
 ,{FORMPMCTRL_LABOUT,{110,80,239,114},STATIC,"Stabel cyl 1",BXS_VISIBLE,&formPMCtrl[13], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL1UP,{110,120,229,179},BUTTON,"Up",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[14], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL1DOWN,{110,191,229,250},BUTTON,"Down",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[15], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL1BOTTOM,{270,210,329,239},BUTTON,"Bottom",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[16], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL1MID,{270,170,329,199},BUTTON,"Mid",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[17], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL1TOP,{270,130,329,159},BUTTON,"Top",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[18], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL2TOP,{480,130,539,159},BUTTON,"Top",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[19], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL2MID,{480,170,539,199},BUTTON,"Mid",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[20], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL2BOTTOM,{480,210,539,239},BUTTON,"Bottom",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[21], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL2UP,{580,120,699,179},BUTTON,"Up",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[22], &formPMCtrl[0]}
 ,{FORMPMCTRL_CHKCYL2DOWN,{580,190,699,249},BUTTON,"Down",BBS_CHECKBOX|BXS_VISIBLE,&formPMCtrl[23], &formPMCtrl[0]}
 ,{FORMPMCTRL_CMDCLOSE,{670,490,789,579},BUTTON,"Close",BBS_PUSHBUTTON|BXS_VISIBLE,&formPMCtrl[24], &formPMCtrl[0]}
 ,{FORMPMCTRL_CMDRESET,{10,490,129,579},BUTTON,"Restart",BBS_PUSHBUTTON|BXS_VISIBLE,&formPMCtrl[25], &formPMCtrl[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formPMCtrl[0]}
};

BX_BOOL formPMCtrlProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formPMCtrlUpdate(hBox);
				return formPMCtrlUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formPMCtrlInit(hBox);
				return formPMCtrlUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMPMCTRL_CHKGRIPOUT:
             return formPMCtrl_chkGripOut_Click(hBox);
         case FORMPMCTRL_CHKGRIPIN:
             return formPMCtrl_chkGripIn_Click(hBox);
         case FORMPMCTRL_CHKGRIP_OUT:
             return formPMCtrl_chkGrip_Out_Click(hBox);
         case FORMPMCTRL_CHKPHOTO1:
             return formPMCtrl_chkPhoto1_Click(hBox);
         case FORMPMCTRL_CHKPHOTO2:
             return formPMCtrl_chkPhoto2_Click(hBox);
         case FORMPMCTRL_CHKGRIP_IN:
             return formPMCtrl_chkGrip_In_Click(hBox);
         case FORMPMCTRL_CHKCYL1UP:
             return formPMCtrl_chkCyl1Up_Click(hBox);
         case FORMPMCTRL_CHKCYL1DOWN:
             return formPMCtrl_chkCyl1Down_Click(hBox);
         case FORMPMCTRL_CHKCYL1BOTTOM:
             return formPMCtrl_chkCyl1Bottom_Click(hBox);
         case FORMPMCTRL_CHKCYL1MID:
             return formPMCtrl_chkCyl1Mid_Click(hBox);
         case FORMPMCTRL_CHKCYL1TOP:
             return formPMCtrl_chkCyl1Top_Click(hBox);
         case FORMPMCTRL_CHKCYL2TOP:
             return formPMCtrl_chkCyl2Top_Click(hBox);
         case FORMPMCTRL_CHKCYL2MID:
             return formPMCtrl_chkCyl2Mid_Click(hBox);
         case FORMPMCTRL_CHKCYL2BOTTOM:
             return formPMCtrl_chkCyl2Bottom_Click(hBox);
         case FORMPMCTRL_CHKCYL2UP:
             return formPMCtrl_chkCyl2Up_Click(hBox);
         case FORMPMCTRL_CHKCYL2DOWN:
             return formPMCtrl_chkCyl2Down_Click(hBox);
         case FORMPMCTRL_CMDCLOSE:
             return formPMCtrl_cmdClose_Click(hBox);
         case FORMPMCTRL_CMDRESET:
             return formPMCtrl_cmdReset_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
