//Code generated by bxbuilder (c) LMS 2002 
// formContinueUser.c
#include "Bx.h"
#include "formContinue.h"
#include "formInterrupt.h"
#include "rs.h"

extern int testMachineState(const char *machinename, const char *statename);

BX_BOOL formContinueUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMCONTINUE_LABINFO));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMCONTINUE_LABINFOTYPE));
  return TRUE;
}
   
extern int testStateChar(const char* machinename, const char *statename);
BX_BOOL formContinueUserUpdate(HBOX hBox)
{
  roboCheckForException(hBox);
   
  if((rs_param.workcellid==306||rs_param.workcellid==308)&&testMachineState("ContinueKnap","ST_PRESSED"))
  {
    formContinue_cmdContinue_Click(hBox);
  }
  return TRUE;
}

BX_BOOL formContinue_cmdStop_Click(HBOX hBox)
{
  GoRobot(FALSE);
  BxEndDialog(hBox, FORMCONTINUE_CMDSTOP);
  return TRUE;
}

extern void newcontinueRobot(void);

BX_BOOL formContinue_cmdContinue_Click(HBOX hBox)
{
  if(rs_param.workcellid==302||rs_param.workcellid==303)
  {
    if(continueRobot())
      BxEndDialog(hBox, FORMCONTINUE_CMDCONTINUE);
  }
  else if(rs_param.workcellid>=304&&rs_param.workcellid<=306)
  {
    newcontinueRobot(); //set state = RESTART
    BxEndDialog(hBox, FORMCONTINUE_CMDCONTINUE);
  } 
  else
  {
    GoRobot(TRUE);
    BxEndDialog(hBox, FORMCONTINUE_CMDCONTINUE);
  }
  return TRUE;
}

