//Code generated by bxbuilder (c) LMS 2002 
// formStartupUser.c
#include <unistd.h>
#include "Bx.h"
#include "formStartup.h"

#include "rs.h"
#include "tmpnrobot.h"

static BXPROGRESSBARSTRUCT pBxBar;
char pbstr[256];
char msgstr[256] = "roboStacker 2050";
static int state = 0;
static long oldfeq;

BX_BOOL formStartupUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTARTUP_TEXTLABEL2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSTARTUP_TEXTLABEL2), GetRSVersion());
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTARTUP_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSTARTUP_TEXTLABEL2_2), GetRSType());

  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMSTARTUP_LABPROGRESS))->lpBoxStr = pbstr;
  BxProgressBar_Create(BxGetDlgItem(hBox, FORMSTARTUP_LABPROGRESS), &pBxBar, BPB_HORIZONTAL);
  BxProgressBar_SetStep(BxGetDlgItem(hBox, FORMSTARTUP_LABPROGRESS), 1);
  
  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE))->lpBoxStr = msgstr;

  state = 0;
  return TRUE;
}

BX_BOOL formStartupUserUpdate(HBOX hBox)
{
  int val;

  switch(state)
  {
    case 0 :
        BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Kontrollerer hardware.");
        state++;
      break;
    case 1 :
      CancelMc(1);
      printf("VERSION: %f \n", GetVersion());
      BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Tryk nødstop ind.");
      state++;
      break;
    case 2 :
      if(emergency()||rs_param.simulateMC==1)
        state++;
      break;
    case 3 : // reset pressed ?
      if(!emergency())
      {
        usleep(2000000);
        // start STARTUP
        if (CmdStartup()==0)
        {
          state = 4;
          BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Starter akser ...");
        }
      }
      else
      {
        BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Frigiv nødstop og tryk reset.");
      }
      break;
    case 4 : // is SETUP done ?
      val = GetReply();
      if(val==1)
      {
        // start mpn_command_set_units_and_defaults
/*
        SetAxisParamValues(axis_t, 0);
        SetAxisParamValues(axis_a, 0);
        SetAxisParamValues(axis_b, 0);
        SetAxisParamValues(axis_c, 0);
        SetAxisParamValues(axis_d, 0);
        SetAxisParamValues(axis_e, 0);
        SetAxisParamValues(axis_f, 0);
*/
        if(SetUnitsAndDefaults()==0)
        {
          state = 5;
          BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Sætter startværdier ...");
        }
      }
      break;
    case 5 : // is setup units .... done ?
      val = GetReply();
      if(val==1)
      {
        state = 6;
        BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Sætter enheder ...");
      }
      break;
    case 6 : // is setup units .... done ?
      val = GetReply();
      if(val==1)
      {
        // start mpn_command_resetaxis
        if(ResetAxis()==0)
        {
          state = 7;
          BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Reset akser ...");
        }
      }
      break;
    case 7 : // is reset .... done ?
      val = GetReply();
      if(val==1)
      {
        // start mpn_command_set_mpn_home_all
        if(SetHomeAll()==0)
        {
          state = 8;
          BxSetBoxText(BxGetDlgItem(hBox, FORMSTARTUP_TEXTMESSAGE), "Finder nulpunkter ...");
        }
      }
      break;
    case 8 : // continue
      val = GetReply();
      if(val==1)
      {
        GetAxisParamValues(axis_t, 0);
        GetAxisParamValues(axis_t, 1);
        GetAxisParamValues(axis_a, 0);
        GetAxisParamValues(axis_a, 1);
        GetAxisParamValues(axis_b, 0);
        GetAxisParamValues(axis_b, 1);
        GetAxisParamValues(axis_c, 0);
        GetAxisParamValues(axis_c, 1);
        GetAxisParamValues(axis_d, 0);
        GetAxisParamValues(axis_d, 1);
        GetAxisParamValues(axis_e, 0);
        GetAxisParamValues(axis_e, 1);
        GetAxisParamValues(axis_f, 0);
        GetAxisParamValues(axis_f, 1);
        state = 9;
        val = (float)GetRetur();
        if(val==0)
        {
          BxEndDialog(hBox, IDOK);
        }
        else
          BxEndDialog(hBox, IDCANCEL);
        CancelMc(0);
        return FALSE;
      }
      break;
  }
  BxProgressBar_SetPos(BxGetDlgItem(hBox, FORMSTARTUP_LABPROGRESS), 100*((float)state)/9.0);
  return TRUE;
}
