//Code generated by bxbuilder (c) LMS 2002 
// formCWdataUser.c
#include "Bx.h"
#include "BxGdi.h"
#include "formCWdata.h"
#include "cmd.h"

static int WINDOWHEIGHT=350;
static int WINDOWOFFSETY=400;
static int WINDOWOFFSETX=50;

static int *startOffset;
static tmpnStateMachineValue *fweight;
static tmpnStateMachineValue *ffweight;
static tmpnStateMachineValue *sampling;
static tmpnStateMachineValue *avgWeight;
static tmpnStateMachineValue *calcWeight;

static int *capture;
static int *lastCalculate;
static int *lastTopIdx;

extern char cwSlave[256];
extern int cw60;

static char *scalestr=NULL;
static char *minstr=NULL;
static char *maxstr=NULL;

void drawTab(HBOX hBox)
{
	BX_RECT tRc;
  BX_COLORREF oldPen;
  BX_COLORREF oldBrush;
  BOXSTRUCT *b;
  int i;
  float diff,scale;

  if(sampling->table==NULL) return;
  b = BxGetDlgItem(hBox,FORMCWDATA_DATA);
	
  BxDC* bdc = BxGetBoxDC(BxGetDlgItem(hBox,FORMCWDATA_DATA));

	oldPen = BxSetPen(bdc, BXSYSTEM_PALETTE[BXCOLOR_BACKGROUND]);
	oldBrush = BxSetBrush(bdc, BXSYSTEM_PALETTE[BXCOLOR_BACKGROUND]);
	
	BxSetRect(&tRc, b->rc.left, b->rc.top, b->rc.right, b->rc.bottom);
	WINDOWOFFSETX=b->rc.left;
	WINDOWOFFSETY=b->rc.bottom;
	WINDOWHEIGHT=b->rc.bottom-b->rc.top;
	BxRectangle(bdc, &tRc);

	BxSetPen(bdc, oldPen);
	BxSetBrush(bdc, oldBrush);
  
  if(sampling->subtype==0)
  {
    //use min and max in table to calculate scale
    diff=sampling->table->max-sampling->table->min;
    scale=WINDOWHEIGHT/diff;
		
    for(i=1;i<sampling->table->curtablesize;i++)
    {
      BxLine(bdc,WINDOWOFFSETX+i  ,WINDOWOFFSETY-(sampling->table->item[i-1]-sampling->table->min)*scale
                ,WINDOWOFFSETX+i+1,WINDOWOFFSETY-(sampling->table->item[i]-sampling->table->min)*scale);
    }
    BxLine(bdc,WINDOWOFFSETX+sampling->table->maxidx,WINDOWOFFSETY-10,WINDOWOFFSETX+sampling->table->maxidx,b->rc.top+10);
  }
  else
  {
    //use fmin and fmax in table to calculate scale
    diff=sampling->table->fmax-sampling->table->fmin;
    scale=WINDOWHEIGHT/diff;
    for(i=1;i<sampling->table->curtablesize;i++)
    {
      BxLine(bdc,WINDOWOFFSETX+i,WINDOWOFFSETY-(sampling->table->fitem[i-1]-sampling->table->fmin)*scale
						 ,WINDOWOFFSETX+i+1,WINDOWOFFSETY-(sampling->table->fitem[i]-sampling->table->fmin)*scale);
    }
    BxLine(bdc,WINDOWOFFSETX+sampling->table->maxidx,WINDOWOFFSETY-10,WINDOWOFFSETX+sampling->table->maxidx,b->rc.top+10);
	}
	BxLine(bdc,WINDOWOFFSETX+*lastCalculate,400,WINDOWOFFSETX+*lastCalculate,10);
	BxLine(bdc,WINDOWOFFSETX+*lastTopIdx,400,WINDOWOFFSETX+*lastTopIdx,10);

  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.0,740,WINDOWOFFSETY-diff*scale*0.0);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.1,740,WINDOWOFFSETY-diff*scale*0.1);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.2,740,WINDOWOFFSETY-diff*scale*0.2);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.3,740,WINDOWOFFSETY-diff*scale*0.3);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.4,740,WINDOWOFFSETY-diff*scale*0.4);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.5,740,WINDOWOFFSETY-diff*scale*0.5);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.6,740,WINDOWOFFSETY-diff*scale*0.6);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.7,740,WINDOWOFFSETY-diff*scale*0.7);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.8,740,WINDOWOFFSETY-diff*scale*0.8);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*0.9,740,WINDOWOFFSETY-diff*scale*0.9);
  BxLine(bdc,10,WINDOWOFFSETY-diff*scale*1.0,740,WINDOWOFFSETY-diff*scale*1.0);
}


BX_BOOL formCWdataUserInit(HBOX hBox,BX_LPARAM lParam)
{
  char cwname[512];
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	BxAssignStringValue(BxGetDlgItem(hBox, FORMCWDATA_CMDMENU));
	BxSetStringValue(BxGetDlgItem(hBox, FORMCWDATA_CMDMENU), getLanguageLineFromIdx(langptr, 54, "Close"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMCWDATA_CAPTURE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMCWDATA_CAPTURE), getLanguageLineFromIdx(langptr, 88, "Capture"));
	scalestr=getLanguageLineFromIdx(langptr, 90 , "Scale");
	minstr=getLanguageLineFromIdx(langptr, 92 , "Min");
	maxstr=getLanguageLineFromIdx(langptr, 93 , "Max");

  BxAssignIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDSTARTVALUE));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDLENGTHVALUE));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMCWDATA_FILTER));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMCWDATA_CAPTURE));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMCWDATA_TEXT));

  if(cw60)
    sprintf(cwname,"checkWeigher");
  else
    sprintf(cwname,"checkWeigher%s",cwSlave);

  lastCalculate = getMachineValuePtr(getMachineIdx(cwname),"lastCalculate");
  lastTopIdx = getMachineValuePtr(getMachineIdx(cwname),"lastTopIdx");
  avgWeight = getMachineValue(getMachineIdx(cwname),"avgWeight");
  calcWeight = getMachineValue(getMachineIdx(cwname),"calcWeight");

  if(cw60)  
    sprintf(cwname,"checkWeigherCalc");
  else
    sprintf(cwname,"checkWeigherCalc%s",cwSlave);
  capture = getMachineValuePtr(getMachineIdx(cwname),"capture");
  fweight = getMachineValue(getMachineIdx(cwname),"fweight");
  ffweight = getMachineValue(getMachineIdx(cwname),"ffweight");
  sampling = getMachineValue(getMachineIdx(cwname),"sampling");
  
  if(cw60)
    sprintf(cwname,"Program");
  else
    sprintf(cwname,"Program%s",cwSlave);
  startOffset = getMachineValuePtr(getMachineIdx(cwname),"startOffset");
  
  BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_FILTER), fweight->table->curtablesize);
  BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDSTARTVALUE), *startOffset);
  BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDLENGTHVALUE), ffweight->table->curtablesize);

  BxSetCheck(BxGetDlgItem(hBox, FORMCWDATA_CAPTURE), *capture);
 return TRUE;
}

BX_BOOL formCWdataUserUpdate(HBOX hBox)
{
 char hstr[256];
 BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_FILTER), fweight->table->curtablesize);
 BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDSTARTVALUE), *startOffset);
 BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDLENGTHVALUE), ffweight->table->curtablesize);
 BxSetCheck(BxGetDlgItem(hBox, FORMCWDATA_CAPTURE), *capture);
 if(sampling->subtype==0)
   sprintf(hstr,"%s %d %s=%d %s=%d avgWeight=%0.2f calcWeight=%0.2f"
					 ,scalestr
					 ,sampling->table->max-sampling->table->min
					 ,minstr
					 ,sampling->table->min
					 ,maxstr
					 ,sampling->table->max
					 ,avgWeight->fdata
					 ,calcWeight->fdata);
 else
   sprintf(hstr,"%s %0.2f %s=%0.2f %s=%0.2f avgWeight=%0.2f calcWeight=%0.2f"
					 ,scalestr
					 ,sampling->table->fmax-sampling->table->fmin
					 ,minstr
					 ,sampling->table->fmin
					 ,maxstr
					 ,sampling->table->fmax
					 ,avgWeight->fdata
					 ,calcWeight->fdata);
 BxSetStringValue(BxGetDlgItem(hBox, FORMCWDATA_TEXT), hstr);
 if(!*capture)
   drawTab(hBox);
 return TRUE;
}

BX_BOOL formCWdata_cmdMenu_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formCWdata_Capture_Click(HBOX hBox)
{
	int i;
  *capture = BxGetCheck(BxGetDlgItem(hBox, FORMCWDATA_CAPTURE));
	if(!*capture)
	{
		if(sampling->subtype==0)
		{
			sampling->table->max=-999999999;
			sampling->table->min=999999999;
			for(i=0;i<sampling->table->curtablesize;i++)
			{
				if (sampling->table->item[i]>sampling->table->max)
					sampling->table->max=sampling->table->item[i];
				if (sampling->table->item[i]<sampling->table->min)
					sampling->table->min=sampling->table->item[i];
			}
		}
		else if(sampling->subtype==1)
		{
			sampling->table->fmax=-999999999.0;
			sampling->table->fmin=999999999.0;
			for(i=0;i<sampling->table->curtablesize;i++)
			{
				if (sampling->table->fitem[i]>sampling->table->fmax)
					sampling->table->fmax=sampling->table->fitem[i];
				if (sampling->table->fitem[i]<sampling->table->fmin)
					sampling->table->fmin=sampling->table->fitem[i];
			}
		}
	}
	return TRUE;
}

BX_BOOL formCWdata_Filter_Click(HBOX hBox)
{
  
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMCWDATA_FILTER)));
  BxVirtNumBox_SetLimits(0,fweight->table->maxsize);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    fweight->table->newtablesize = BxVirtNumBox_GetValue();
    BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_FILTER), fweight->table->newtablesize);
  }
  return TRUE;
}

BX_BOOL formCWdata_cmdStartValue_Click(HBOX hBox)
{
  
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDSTARTVALUE)));
//  BxVirtNumBox_SetLimits(0,100);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    *startOffset = BxVirtNumBox_GetValue();
    BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDSTARTVALUE), *startOffset);
  }
  return TRUE;
}

BX_BOOL formCWdata_cmdLengthValue_Click(HBOX hBox)
{
  
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDLENGTHVALUE)));
  BxVirtNumBox_SetLimits(0,ffweight->table->maxsize);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    ffweight->table->newtablesize = BxVirtNumBox_GetValue();
    BxSetIntValue(BxGetDlgItem(hBox, FORMCWDATA_CMDLENGTHVALUE), ffweight->table->newtablesize);
  }
  return TRUE;
}

