//Code generated by bxbuilder (c) LMS 2002 
// formEditSysParamUser.c
#include "Bx.h"
#include "cmd.h"
#include "formEditSysParam.h"

static void EditValues(HBOX hBox, int indx)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, indx)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, indx), BxVirtNumBox_GetFloatValue());
  }
}

BX_BOOL formEditSysParamUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDRETURN));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDRETURN), getLanguageLineFromIdx(langptr, 74, "Ok"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDCANCEL), getLanguageLineFromIdx(langptr, 3, "Cancel"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_GROUPBOX1));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_GROUPBOX1), getLanguageLineFromIdx(langptr, 107, "Limits"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_5));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_5), getLanguageLineFromIdx(langptr, 92, "Min"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_6));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_6), getLanguageLineFromIdx(langptr, 93, "Max"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_5_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_5_2), getLanguageLineFromIdx(langptr, 108, "Robot offset"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_5_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_TEXTLABEL2_5_2_2), getLanguageLineFromIdx(langptr, 109, "Calib offset"));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDAMIN));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDAMAX));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDBMIN));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDBMAX));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDCMIN));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDCMAX));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDDMIN));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDDMAX));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDEMIN));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDEMAX));

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDAROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDBROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDCROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDDROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDEROFF));

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDACOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDBCOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDCCOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDDCOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITSYSPARAM_CMDECOFF));
  return TRUE;
}

BX_BOOL formEditSysParamUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formEditSysParam_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDCANCEL);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdAMin_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDAMIN);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdAMax_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDAMAX);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdBMin_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDBMIN);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdBMax_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDBMAX);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdCMin_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDCMIN);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdCMax_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDCMAX);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdDMin_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDDMIN);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdDMax_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDDMAX);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdEMin_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDEMIN);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdEMax_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDEMAX);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdAROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDAROFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdBROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDBROFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdCROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDCROFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdDROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDDROFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdEROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDEROFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdACOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDACOFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdBCOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDBCOFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdCCOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDCCOFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdDCOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDDCOFF);
  return TRUE;
}

BX_BOOL formEditSysParam_cmdECOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITSYSPARAM_CMDECOFF);
  return TRUE;
}

