//Code generated by bxbuilder (c) LMS 2002 
// formSetDebug.h
#if !defined(FORMSETDEBUG_H)
#define FORMSETDEBUG_H
#include "Bx.h"
#include "formSetDebugUser.h"
#define FORMSETDEBUG_CMDOK 1
extern BX_BOOL formSetDebug_cmdOk_Click(HBOX hBox);
#define FORMSETDEBUG_CMDCANCEL 2
extern BX_BOOL formSetDebug_cmdCancel_Click(HBOX hBox);
#define FORMSETDEBUG_TEXTLABEL2_2 3
#define FORMSETDEBUG_CHKLOOP 4
extern BX_BOOL formSetDebug_chkLoop_Click(HBOX hBox);
#define FORMSETDEBUG_CHKWITHPALLET 5
extern BX_BOOL formSetDebug_chkWithPallet_Click(HBOX hBox);
#define FORMSETDEBUG_CHKWITHPRODUCT 6
extern BX_BOOL formSetDebug_chkWithProduct_Click(HBOX hBox);
#define FORMSETDEBUG_LAB 7
#define FORMSETDEBUG_LAB_2 8
#define FORMSETDEBUG_LAB_2_2_2 9
#define FORMSETDEBUG_LAB_2_2 10
#define FORMSETDEBUG_LAB_2_2_3 11
#define FORMSETDEBUG_CHKWITHBOX 12
extern BX_BOOL formSetDebug_chkWithBox_Click(HBOX hBox);
#define FORMSETDEBUG_LAB_3 13
#define FORMSETDEBUG_CHKONLINE 14
extern BX_BOOL formSetDebug_chkOnline_Click(HBOX hBox);
#define FORMSETDEBUG_CHKWITHREJECT 15
extern BX_BOOL formSetDebug_chkWithReject_Click(HBOX hBox);
#define FORMSETDEBUG_LAB_3_2 16
#define FORMSETDEBUG_CHKRESETSTAT 17
extern BX_BOOL formSetDebug_chkResetStat_Click(HBOX hBox);
#define FORMSETDEBUG_LAB_3_2_2 18
#define FORMSETDEBUG_LAB_3_2_2_2 19
#define FORMSETDEBUG_CHKRESETCURRENT 20
extern BX_BOOL formSetDebug_chkResetCurrent_Click(HBOX hBox);
#define FORMSETDEBUG_CHKRESETFOLLOWERR 21
extern BX_BOOL formSetDebug_chkResetFollowErr_Click(HBOX hBox);
extern BX_CHAR formSetDebugText[][MAXLANGUAGE][255];
extern BOXSTRUCT formSetDebug[];
extern BX_BOOL formSetDebugProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formSetDebugUpdate(HBOX hBox);
extern BX_VOID formSetDebugInit(HBOX hBox);
#endif // FORMSETDEBUG_H
