//Code generated by bxbuilder (c) LMS 2002 
// formLogger.h
#if !defined(FORMLOGGER_H)
#define FORMLOGGER_H
#include "Bx.h"
#include "formLoggerUser.h"
#define FORMLOGGER_LISTBOX 1
extern BX_BOOL formLogger_listBox_Click(HBOX hBox);
#define FORMLOGGER_CMDMENU 2
extern BX_BOOL formLogger_cmdMenu_Click(HBOX hBox);
extern BX_CHAR formLoggerText[][MAXLANGUAGE][255];
extern BOXSTRUCT formLogger[];
extern BX_BOOL formLoggerProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formLoggerUpdate(HBOX hBox);
extern BX_VOID formLoggerInit(HBOX hBox);
#endif // FORMLOGGER_H
