//Code generated by bxbuilder (c) LMS 2002 
// formAVIModUser.c
#include "Bx.h"
#include "formAVIMod.h"
#include "cmd.h"

extern volatile int dioIndex;
extern volatile int modIndex;
static char namestr[256]="Name :";

BX_BOOL formAVIModUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	sprintf(namestr,"%s :",getLanguageLineFromIdx(langptr, 87, "Name"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_TEXTLABEL2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_TEXTLABEL2_2_2), namestr);
	BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_CMDCLOSE), getLanguageLineFromIdx(langptr, 54, "Close"));

  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABTYPE));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABMODNAME));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT1));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT2));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT3));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT4));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA1));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA2));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA3));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA4));
  
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABTYPE), "AVI1270");
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABMODNAME),  tworkcell->dios.dio[dioIndex].iotab[modIndex].module_name);
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT1), tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[0].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT2), tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[1].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT3), tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[2].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVIMOD_LABCONNECT4), tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[3].key);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA1), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[0]);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA2), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[1]);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA3), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[2]);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA4), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[3]);
  return TRUE;
}

BX_BOOL formAVIModUserUpdate(HBOX hBox)
{
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA1), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[0]);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA2), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[1]);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA3), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[2]);
  BxSetIntValue(BxGetDlgItem(hBox, FORMAVIMOD_DATA4), tworkcell->dios.dio[dioIndex].iotab[modIndex].idata[3]);
  return TRUE;
}

BX_BOOL formAVIMod_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

