//Code generated by bxbuilder (c) LMS 2002 
// formAxisParmUser.c
#include "Bx.h"
#include "formAxisParm.h"

#include "rs.h"
#include "cmd.h"

char axparam[29][256] =
{"ATYPE"
,"P_GAIN"          
,"I_GAIN"
,"D_GAIN"
,"OV_GAIN"
,"VFF_GAIN"
,"UNITS"
,"SPEED"
,"ACCEL"
,"DECEL"
,"CREEP"
,"JOGSPEED"
,"FELIMIT"
,"DAC"
,"SERVO"
,"REDISPT"
,"FWD_IN"
,"REV_IN"
,"DAT_IN"
,"FH_IN"
,"FSLIMIT"
,"RSLIMIT"
,"MTYPE"
,"NTYPE"
,"MPOS"
,"DPOS"
,"FE"
,"AXISSTATUS"
,"VPSPEED"
};

char axparamv[29][256];
char axisnum[256] = "0";;
int AxisNumber=0;

int GetAxisValues(int axis, int tabel)
{
  GetAxisParamValues(axis, tabel);
  return 0;
}
static BX_BOOL setupAxisParamBox(HBOX hBox, int axis, int tabel)
{
  
  if(tabel==0)
  {
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDAXISNUM));
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_1));
    sprintf(axparamv[0], "%.4f", tspace.axis.array[axis].atype);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_1));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_2));
    sprintf(axparamv[1], "%.4f", tspace.axis.array[axis].p_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_2));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_3));
    sprintf(axparamv[2], "%.4f", tspace.axis.array[axis].i_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_3));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_4));
    sprintf(axparamv[3], "%.4f", tspace.axis.array[axis].d_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_4));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_5));
    sprintf(axparamv[4], "%.4f", tspace.axis.array[axis].ov_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_5));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_6));
    sprintf(axparamv[5], "%.4f", tspace.axis.array[axis].vff_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_6));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_7));
    sprintf(axparamv[6], "%.4f", tspace.axis.array[axis].units);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_7));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_8));
    sprintf(axparamv[7], "%.4f", tspace.axis.array[axis].speed);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_8));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_9));
    sprintf(axparamv[8], "%.4f", tspace.axis.array[axis].accel);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_9));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_10));
    sprintf(axparamv[9], "%.4f", tspace.axis.array[axis].decel);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_10));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_11));
    sprintf(axparamv[10], "%.4f", tspace.axis.array[axis].creep);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_11));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_12));
    sprintf(axparamv[11], "%.4f", tspace.axis.array[axis].jogspeed);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_12));

    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_13));
    sprintf(axparamv[12], "%.4f", tspace.axis.array[axis].felimit);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_13));

  }
  else // if 1
  {
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_14));
    sprintf(axparamv[13], "%.4f", tspace.axis.array[axis].dac);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_14));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_15));
    sprintf(axparamv[14], "%.4f", tspace.axis.array[axis].servo);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_15));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_16));
    sprintf(axparamv[15], "%.2f", tspace.axis.array[axis].redispt);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_16));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_17));
    sprintf(axparamv[16], "%.4f", tspace.axis.array[axis].fwd_in);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_17));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_18));
    sprintf(axparamv[17], "%.4f", tspace.axis.array[axis].rev_in);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_18));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_19));
    sprintf(axparamv[18], "%.4f", tspace.axis.array[axis].dat_in);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_19));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_20));
    sprintf(axparamv[19], "%.4f", tspace.axis.array[axis].fh_in);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_20));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_21));
    sprintf(axparamv[20], "%.2f", tspace.axis.array[axis].fslimit);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_21));
    
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_22));
    sprintf(axparamv[21], "%.2f", tspace.axis.array[axis].rslimit);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_22));


    sprintf(axparamv[22], "%0.4f", tspace.axis.array[axis].mtype);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_1));
    
    sprintf(axparamv[23], "%0.4f", tspace.axis.array[axis].ntype);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_2));
    
    sprintf(axparamv[24], "%0.4f", tspace.axis.array[axis].mpos);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_3));
    
    sprintf(axparamv[25], "%0.4f", tspace.axis.array[axis].dpos);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_4));
    
    sprintf(axparamv[26], "%0.4f", tspace.axis.array[axis].fe);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_5));
    
    sprintf(axparamv[27], "%0.4f", tspace.axis.array[axis].axisstatus);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_6));
    
    sprintf(axparamv[28], "%0.4f", tspace.axis.array[axis].vpspeed);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_7));
    
  }
  return TRUE;
}

BX_BOOL formAxisParmUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BOXSTRUCT *b;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	

  BxAssignStringValue(BxGetDlgItem(hBox, FORMAXISPARM_CMDRETURN));
  BxSetStringValue(BxGetDlgItem(hBox, FORMAXISPARM_CMDRETURN), getLanguageLineFromIdx(langptr, 5, "Return"));

	BxAssignStringValue(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL2_2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL2_2_2), getLanguageLineFromIdx(langptr, 45, "Axis"));
	
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL2_2), GetRSType());

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDAXISNUM);
  b->lpBoxStr = axisnum;
  sprintf(axisnum, "%d", AxisNumber);
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_1);
  b->lpBoxStr = axparam[0];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_1);
  b->lpBoxStr = axparamv[0];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_2);
  b->lpBoxStr = axparam[1];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_2);
  b->lpBoxStr = axparamv[1];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_3);
  b->lpBoxStr = axparam[2];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_3);
  b->lpBoxStr = axparamv[2];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_4);
  b->lpBoxStr = axparam[3];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_4);
  b->lpBoxStr = axparamv[3];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_5);
  b->lpBoxStr = axparam[4];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_5);
  b->lpBoxStr = axparamv[4];
  
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_6);
  b->lpBoxStr = axparam[5];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_6);
  b->lpBoxStr = axparamv[5];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_7);
  b->lpBoxStr = axparam[6];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_7);
  b->lpBoxStr = axparamv[6];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_8);
  b->lpBoxStr = axparam[7];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_8);
  b->lpBoxStr = axparamv[7];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_9);
  b->lpBoxStr = axparam[8];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_9);
  b->lpBoxStr = axparamv[8];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_10);
  b->lpBoxStr = axparam[9];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_10);
  b->lpBoxStr = axparamv[9];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_11);
  b->lpBoxStr = axparam[10];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_11);
  b->lpBoxStr = axparamv[10];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_12);
  b->lpBoxStr = axparam[11];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_12);
  b->lpBoxStr = axparamv[11];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_13);
  b->lpBoxStr = axparam[12];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_13);
  b->lpBoxStr = axparamv[12];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_14);
  b->lpBoxStr = axparam[13];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_14);
  b->lpBoxStr = axparamv[13];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_15);
  b->lpBoxStr = axparam[14];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_15);
  b->lpBoxStr = axparamv[14];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_16);
  b->lpBoxStr = axparam[15];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_16);
  b->lpBoxStr = axparamv[15];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_17);
  b->lpBoxStr = axparam[16];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_17);
  b->lpBoxStr = axparamv[16];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_18);
  b->lpBoxStr = axparam[17];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_18);
  b->lpBoxStr = axparamv[17];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_19);
  b->lpBoxStr = axparam[18];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_19);
  b->lpBoxStr = axparamv[18];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_20);
  b->lpBoxStr = axparam[19];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_20);
  b->lpBoxStr = axparamv[19];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_21);
  b->lpBoxStr = axparam[20];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_21);
  b->lpBoxStr = axparamv[20];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTLABEL_22);
  b->lpBoxStr = axparam[21];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_22);
  b->lpBoxStr = axparamv[21];

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_1);
  b->lpBoxStr = axparamv[22];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_2);
  b->lpBoxStr = axparamv[23];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_3);
  b->lpBoxStr = axparamv[24];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_4);
  b->lpBoxStr = axparamv[25];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_5);
  b->lpBoxStr = axparamv[26];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_6);
  b->lpBoxStr = axparamv[27];
  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMAXISPARM_TEXTBANKV_7);
  b->lpBoxStr = axparamv[28];

  GetAxisValues(AxisNumber, 1);
  setupAxisParamBox(hBox, AxisNumber, 0);
  setupAxisParamBox(hBox, AxisNumber, 1);
  
  return TRUE;
}

BX_BOOL formAxisParmUserUpdate(HBOX hBox)
{
//read values from mc into tspace
  GetAxisValues(AxisNumber, 1);
  setupAxisParamBox(hBox, AxisNumber, 1);
  return TRUE;
}

BX_BOOL formAxisParm_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formAxisParm_cmdSave_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  if(rs_param.mc_version >= 2)
  {
    copyAxisToRobotFile((tmpnRobot*)trobot);
    SaveCalibrationParam(&rs_param);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdAxisNum_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(AxisNumber);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    AxisNumber = BxVirtNumBox_GetValue();
  }
  sprintf(axisnum, "%d", AxisNumber);
  GetAxisValues(AxisNumber, 1);
  setupAxisParamBox(hBox, AxisNumber, 0);
  setupAxisParamBox(hBox, AxisNumber, 1);
  return TRUE;
}

BX_BOOL formAxisParm_cmdAxisNumMinus_Click(HBOX hBox)
{
  if(AxisNumber > 0)
  {
    AxisNumber--;
    sprintf(axisnum, "%d", AxisNumber);
    GetAxisValues(AxisNumber, 1);
    setupAxisParamBox(hBox, AxisNumber, 0);
    setupAxisParamBox(hBox, AxisNumber, 1);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdAxisNumPlus_Click(HBOX hBox)
{
  AxisNumber++;
  sprintf(axisnum, "%d", AxisNumber);
  GetAxisValues(AxisNumber, 1);
  setupAxisParamBox(hBox, AxisNumber, 0);
  setupAxisParamBox(hBox, AxisNumber, 1);
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_1_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_2_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].p_gain);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].p_gain = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[1], "%.4f", tspace.axis.array[AxisNumber].p_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_2));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}
BX_BOOL formAxisParm_cmdParam_3_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].i_gain);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].i_gain = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[2], "%.4f", tspace.axis.array[AxisNumber].i_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_3));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_4_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].d_gain);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].d_gain = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[3], "%.4f", tspace.axis.array[AxisNumber].d_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_4));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_5_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].ov_gain);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].ov_gain = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[4], "%.4f", tspace.axis.array[AxisNumber].ov_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_5));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}


BX_BOOL formAxisParm_cmdParam_6_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].vff_gain);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].vff_gain = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[5], "%.4f", tspace.axis.array[AxisNumber].vff_gain);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_6));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_7_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].units);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].units = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[6], "%.4f", tspace.axis.array[AxisNumber].units);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_7));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_8_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].speed);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].speed = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[7], "%.4f", tspace.axis.array[AxisNumber].speed);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_8));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}


BX_BOOL formAxisParm_cmdParam_9_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].accel);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].accel = BxVirtNumBox_GetFloatValue();
    SetAxisParamValues(AxisNumber, 0);
    sprintf(axparamv[8], "%.4f", tspace.axis.array[AxisNumber].accel);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_9));
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_10_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].decel);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].decel = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[9], "%.4f", tspace.axis.array[AxisNumber].decel);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_10));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_11_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].creep);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].creep = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[10], "%.4f", tspace.axis.array[AxisNumber].creep);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_11));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_12_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].jogspeed);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].jogspeed = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[11], "%.4f", tspace.axis.array[AxisNumber].jogspeed);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_12));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_13_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].felimit);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].felimit = BxVirtNumBox_GetFloatValue();
    sprintf(axparamv[12], "%.4f", tspace.axis.array[AxisNumber].felimit);
    BxRequestPaint(BxGetDlgItem(hBox, FORMAXISPARM_CMDPARAM_13));
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_14_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(tspace.axis.array[AxisNumber].dac);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].dac = BxVirtNumBox_GetValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_15_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(tspace.axis.array[AxisNumber].servo);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].servo = BxVirtNumBox_GetValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_16_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].redispt);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].redispt = BxVirtNumBox_GetFloatValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_17_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(tspace.axis.array[AxisNumber].fwd_in);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].fwd_in = BxVirtNumBox_GetValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_18_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(tspace.axis.array[AxisNumber].rev_in);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].rev_in = BxVirtNumBox_GetValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_19_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(tspace.axis.array[AxisNumber].dat_in);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].dat_in = BxVirtNumBox_GetValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_20_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(tspace.axis.array[AxisNumber].fh_in);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].fh_in = BxVirtNumBox_GetValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_21_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].fslimit);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].fslimit = BxVirtNumBox_GetFloatValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

BX_BOOL formAxisParm_cmdParam_22_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(tspace.axis.array[AxisNumber].rslimit);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    tspace.axis.array[AxisNumber].rslimit = BxVirtNumBox_GetFloatValue();
    SetAxisParamValues(AxisNumber, 0);
  }
  return TRUE;
}

