//Code generated by bxbuilder (c) LMS 2002 
// formEditBoxPatternUser.h

extern BX_BOOL formEditBoxPatternUserInit(HBOX hBox,BX_LPARAM lParam);
extern BX_BOOL formEditBoxPatternUserUpdate(HBOX hBox);
