//Code generated by bxbuilder (c) LMS 2002 
// formAVOModUser.c
#include "Bx.h"
#include "formAVOMod.h"
#include "cmd.h"

extern volatile int dioIndex;
extern volatile int modIndex;
static char namestr[256]="Name :";

BX_BOOL formAVOModUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	sprintf(namestr,"%s :",getLanguageLineFromIdx(langptr, 87, "Name"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMAVOMOD_TEXTLABEL2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVOMOD_TEXTLABEL2_2_2), namestr);
	BxAssignStringValue(BxGetDlgItem(hBox, FORMAVOMOD_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMAVOMOD_CMDCLOSE), getLanguageLineFromIdx(langptr, 54, "Close"));

  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABTYPE));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABMODNAME));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABCONNECT1));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABCONNECT2));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA1));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA2));
  
  BxSetStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABTYPE), "AVO1250");
  BxSetStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABMODNAME),  tworkcell->dios.dio[dioIndex].iotab[modIndex].module_name);
  BxSetStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABCONNECT1), tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[2].key);
  BxSetStringValue(BxGetDlgItem(hBox, FORMAVOMOD_LABCONNECT2), tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[3].key);
  
  BxSetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA1), getConnectValueInt(&tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[2]));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA2), getConnectValueInt(&tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[3]));
  return TRUE;
}

BX_BOOL formAVOModUserUpdate(HBOX hBox)
{
  BxSetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA1), getConnectValueInt(&tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[2]));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA2), getConnectValueInt(&tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[3]));
  return TRUE;
}

BX_BOOL formAVOMod_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formAVOMod_Data1_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA1)));
  BxVirtNumBox_SetFloatLimits(-65535.0, 65535.0);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA1), BxVirtNumBox_GetFloatValue());
    setConnectValueInt(&tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[2],BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formAVOMod_Data2_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA2)));
  BxVirtNumBox_SetFloatLimits(-65535.0, 65535.0);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMAVOMOD_DATA2), BxVirtNumBox_GetFloatValue());
    setConnectValueInt(&tworkcell->dios.dio[dioIndex].iotab[modIndex].connect[3],BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

