//Code generated by bxbuilder (c) LMS 2002 
// formStatusUser.c
#include "Bx.h"
#include "formStatus.h"

#include "rs.h"

BX_BOOL formStatusUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];

	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_TEXTLABEL2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_TEXTLABEL2_2), getLanguageLineFromIdx(langptr, 27, "Stats"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_CMDCLOSE), getLanguageLineFromIdx(langptr, 54, "Close"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_GROUPBOX2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_GROUPBOX2), getLanguageLineFromIdx(langptr, 226, "Box"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB), getLanguageLineFromIdx(langptr, 227, "Fill"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2), getLanguageLineFromIdx(langptr, 228, "Move"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2_2), getLanguageLineFromIdx(langptr, 229, "Reject"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_GROUPBOX3));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_GROUPBOX3), getLanguageLineFromIdx(langptr, 230, "Vacuum"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3), getLanguageLineFromIdx(langptr, 231, "Dropped"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2_2_3));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2_2_3), getLanguageLineFromIdx(langptr, 232, "Loss"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_2_2_2), getLanguageLineFromIdx(langptr, 134, "Error"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_GROUPBOX4));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_GROUPBOX4), getLanguageLineFromIdx(langptr, 233, "Wait"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2), getLanguageLineFromIdx(langptr, 226, "Box"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_3));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_3), getLanguageLineFromIdx(langptr, 234, "Total"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2_2_2_2), getLanguageLineFromIdx(langptr, 235, "Box release"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2), getLanguageLineFromIdx(langptr, 236, "Product (total)"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2_2), getLanguageLineFromIdx(langptr, 237, "Product (>2sec.)"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTATUS_LAB_3_2_2_2_2), getLanguageLineFromIdx(langptr, 238, "Pallet"));
	BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABFILL));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABFILL), GetVR(700));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABMOVE));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABMOVE), GetVR(701));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABREJECT));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABREJECT), GetVR(702));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABERROR));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABERROR), GetVR(703));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABLOSS));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABLOSS), GetVR(704));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABDROPPED));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABDROPPED), GetVR(705));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABBOX));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABBOX), GetVR(706));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LAB2SEC));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LAB2SEC), GetVR(707));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABTOTAL));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABTOTAL), GetVR(708));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABPALLET));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABPALLET), GetVR(709));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABBOXREL));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABBOXREL), GetVR(710));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABTOTALTM));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSTATUS_LABTOTALTM), GetVR(732));

  return TRUE;
}

BX_BOOL formStatusUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formStatus_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, FALSE);
  return FALSE;
}
