//Code generated by bxbuilder (c) LMS 2002 
// formSTMListUser.c
#include "rs.h"
#include "Bx.h"
#include "robostackerBxr.h"
#include "formSTMList.h"
#include "formSTMCtrl.h"

#include "cmd.h"

static BXMENUSTRUCT pBxMenu;
extern int stmcyclespersec;

int setState(int machine, int state);

BX_BOOL formSTMListUserInit(HBOX hBox,BX_LPARAM lParam)
{
  int i;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMLIST_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMLIST_CMDCLOSE), getLanguageLineFromIdx(langptr, 17, "Menu"));

  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMLIST_TEXTLABEL2_2));
	
  for(i=0;i<tworkcell->statemachines.maxidx;i++)
    BxList_AddString(BxGetDlgItem(hBox, FORMSTMLIST_LISTBOX), tworkcell->statemachines.statemachine[i].name);
	
  return TRUE;
}

BX_BOOL formSTMListUserUpdate(HBOX hBox)
{
  BX_CHAR str[1024];
  BX_INT i;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
  sprintf(str, "%s %d",getLanguageLineFromIdx(langptr, 48, "STM samplerate"), stmcyclespersec);
  BxSetStringValue(BxGetDlgItem(hBox, FORMSTMLIST_TEXTLABEL2_2), str);

  for(i=0;i<tworkcell->statemachines.maxidx;i++)
  {
    sprintf(str, "%s %s", tworkcell->statemachines.statemachine[i].name
          ,tworkcell->statemachines.statemachine[i].state[tworkcell->statemachines.statemachine[i].istate].name); 
    BxList_SetString(BxGetDlgItem(hBox, FORMSTMLIST_LISTBOX), i, str);
  }
	BxList_Update(BxGetDlgItem(hBox, FORMSTMLIST_LISTBOX));
  return TRUE;
}

BX_BOOL formSTMList_ResetAllSTM_Click(HBOX hBox)
{
  
  int i, stateidx;  
  for(i=0;i<tworkcell->statemachines.maxidx;i++)
  {
    stateidx=getStateIdx(i,"ST_RESET");
    if (stateidx>=0)
      setState(i, stateidx);
  }
  return TRUE;
}

BX_BOOL formSTMList_StopAllSTM_Click(HBOX hBox)
{
  
  int i;  
  for(i=0;i<tworkcell->statemachines.maxidx;i++)
    setState(i, getStateIdx(i,"ST_HALT"));
  
  return TRUE;
}

BX_BOOL formSTMList_IdleAllSTM_Click(HBOX hBox)
{

  int i;  
  for(i=0;i<tworkcell->statemachines.maxidx;i++)
    setState(i, getStateIdx(i,"ST_IDLE"));
  
  return TRUE;
}

BX_BOOL formSTMList_cmdCloseDlg_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formSTMList_cmdRLoad_Click(HBOX hBox)
{
	mpnexit(9);
	return TRUE;
}

BX_BOOL formSTMList_cmdClose_Click(HBOX hBox)
{
  HBOX hBx;
	extern BxIcon *iconreload;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	
  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMSTMLIST_CMDCLOSE), &pBxMenu);
	
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 49, "Reload program"), MENU, formSTMList_cmdRLoad_Click, TRUE, iconreload);
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 50, "Reset all STM"), MENU, formSTMList_ResetAllSTM_Click, TRUE, NULL);
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 51, "Halt all STM"), MENU, formSTMList_StopAllSTM_Click, TRUE, NULL);
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 52, "Idle all STM"), MENU, formSTMList_IdleAllSTM_Click, TRUE, NULL);
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 5, "Return"), MENU, formSTMList_cmdCloseDlg_Click, TRUE, NULL);
  DoMenu(BxGetDlgItem(hBox, FORMSTMLIST_CMDCLOSE));
  return TRUE;
}

void formSTMCtrl_SetStateMachine(int stmNum);

BX_BOOL formSTMList_listBox_Click(HBOX hBox)
{
  HBOX hBx;
  BX_INT stmNum=0;
	  
  stmNum = BxList_GetSelected(BxGetDlgItem(hBox, FORMSTMLIST_LISTBOX));
	if (stmNum>=0)
	{
		formSTMCtrl_SetStateMachine(stmNum);
		hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formSTMCtrl[0], formSTMCtrlProc);
		DoModal(hBx);
  }
  return TRUE;
}
