//Code generated by bxbuilder (c) LMS 2002 
// formDDIModUser.c
#include "Bx.h"
#include "formDDIMod.h"
#include "cmd.h"

extern volatile int modIndex;

BX_BOOL formDDIModUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABTYPE));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABMODNAME));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT1));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT2));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT3));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT4));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT5));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT6));
  
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABTYPE), "DDI3610");
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABMODNAME),  tworkcell->dios.dio[0].iotab[modIndex].module_name);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT1), tworkcell->dios.dio[0].iotab[modIndex].connect[0].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT2), tworkcell->dios.dio[0].iotab[modIndex].connect[1].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT3), tworkcell->dios.dio[0].iotab[modIndex].connect[2].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT4), tworkcell->dios.dio[0].iotab[modIndex].connect[3].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT5), tworkcell->dios.dio[0].iotab[modIndex].connect[4].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDIMOD_LABCONNECT6), tworkcell->dios.dio[0].iotab[modIndex].connect[5].key);
  
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE1), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0001 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE2), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0002 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE3), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0004 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE4), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0008 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE5), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0010 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE6), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0020 ? TRUE : FALSE);

	return TRUE;
}

BX_BOOL formDDIModUserUpdate(HBOX hBox)
{
  
	BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE1), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0001 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE2), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0002 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE3), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0004 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE4), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0008 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE5), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0010 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE6), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0020 ? TRUE : FALSE);
	
  return TRUE;
}

BX_BOOL formDDIMod_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formDDIMod_chkState1_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE1))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] |= 0x01;
	else
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] &= 0xFE;
  return TRUE;
}

BX_BOOL formDDIMod_chkState2_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE2))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] |= 0x02;
	else
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] &= 0xFD;
  return TRUE;
}

BX_BOOL formDDIMod_chkState3_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE3))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] |= 0x04;
	else
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] &= 0xFB;
  return TRUE;
}

BX_BOOL formDDIMod_chkState4_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE4))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] |= 0x08;
	else
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] &= 0xF7;

  return TRUE;
}

BX_BOOL formDDIMod_chkState5_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE5))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] |= 0x10;
	else
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] &= 0xEF;

  return TRUE;
}

BX_BOOL formDDIMod_chkState6_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDIMOD_CHKSTATE6))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] |= 0x20;
	else
    tworkcell->dios.dio[0].iotab[modIndex].idata[0] &= 0xDF;

  return TRUE;
}

