//Code generated by bxbuilder (c) LMS 2002 
// form2pCalUser.c
#include "Bx.h"
#include "form2pCal.h"
#include "cmd.h"

extern void SetTouchCalibration(float xcal, float ycal);
extern void SetTouchCalibrationOffset(int xoff, int yoff);
extern int GetTouchXOffset(void);
extern int GetTouchYOffset(void);
extern float GetTouchXFactor(void);
extern float GetTouchYFactor(void);

extern unsigned int GetRawX(void);
extern unsigned int GetRawY(void);
static int calState = 0;
char calMsg1[256];
char calMsg2[256];
static int calLeft = 0;
static int calTop = 0;
static int calRight = 0;
static int calBottom = 0;
static int scrLeft = 0;
static int scrTop = 0;
static int scrRight = 0;
static int scrBottom = 0;
BX_BOOL form2pCalUserInit(HBOX hBox,BX_LPARAM lParam)
{
 PBOXSTRUCT pBx = (PBOXSTRUCT)BxGetDlgItem(hBox, FORM2PCAL_TEXTMESSAGE);

 pBx->lpBoxStr = calMsg1;
 pBx = (PBOXSTRUCT)BxGetDlgItem(hBox, FORM2PCAL_TEXTMSG);
 pBx->lpBoxStr = calMsg2;

 BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDRIGHTBOTTOM), BM_SHOWBOX, FALSE, 0);
 BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDCONTINUE), BM_SHOWBOX, FALSE, 0);
 return TRUE;
}

BX_BOOL form2pCalUserUpdate(HBOX hBox)
{
  PBOXSTRUCT b;
  float calValX=0.0, calValY=0.0;
  float x_sfactor, y_sfactor;
  int x_offset = 0, y_offset = 0;
    
  switch(calState) {
   case 0:
      BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDLEFTTOP), BM_SHOWBOX, TRUE, 0);
      BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDRIGHTBOTTOM), BM_SHOWBOX, FALSE, 0);
      BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDCONTINUE), BM_SHOWBOX, FALSE, 0);
     sprintf(calMsg1,"Press left top button.");
     BxRequestPaint(BxGetDlgItem(hBox, FORM2PCAL_TEXTMESSAGE));
   case 1:
   case 2:
   case 3:
   case 4:
   case 5:
   case 6:
   case 7:
   case 8:
   case 9:
   case 10:
     sprintf(calMsg2,"Time left %d sec.", 10-calState);
     calState++;
     BxRequestPaint(BxGetDlgItem(hBox, FORM2PCAL_TEXTMSG));
     break;
   case 11:
     calLeft = GetRawX();
     calTop = GetRawY();
     BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDLEFTTOP), BM_SHOWBOX, FALSE, 0);
     BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDRIGHTBOTTOM), BM_SHOWBOX, TRUE, 0);
     sprintf(calMsg1,"Press right bottom button.");
     BxRequestPaint(BxGetDlgItem(hBox, FORM2PCAL_TEXTMESSAGE));
   case 12:
   case 13:
   case 14:
   case 15:
   case 16:
   case 17:
   case 18:
   case 19:
   case 20:
     sprintf(calMsg2,"Time left %d sec.", 20-calState);
     calState++;
     BxRequestPaint(BxGetDlgItem(hBox, FORM2PCAL_TEXTMSG));
     break;
   case 21:
     calRight = GetRawX();
     calBottom = GetRawY();
     b = (PBOXSTRUCT)BxGetDlgItem(hBox, FORM2PCAL_CMDLEFTTOP);
     scrLeft = BxRectCenterX(&b->rc);
     scrTop = BxRectCenterY(&b->rc);
     b = (PBOXSTRUCT)BxGetDlgItem(hBox, FORM2PCAL_CMDRIGHTBOTTOM);
     scrRight = BxRectCenterX(&b->rc);
     scrBottom = BxRectCenterY(&b->rc);

     if((calRight - calLeft)!=0 && (calBottom - calTop)!=0)
     {
      calValX = (float)(scrRight - scrLeft)/(float)(calRight - calLeft);
      calValY = (float)(scrBottom - scrTop)/(float)(calBottom - calTop);

      x_sfactor = 800.0 / (float)(scrRight - scrLeft);
      y_sfactor = 600.0 / (float)(scrBottom - scrTop);
      
      x_offset = calLeft - (((float)(calRight - calLeft)*x_sfactor)-(float)(calRight - calLeft))/2.0;
      y_offset = calTop - (((float)(calBottom - calTop)*y_sfactor)-(float)(calBottom - calTop))/2.0;
  

      rs_param.touch.calx = x_offset;
      rs_param.touch.caly = y_offset;
      rs_param.touch.calx = calValX;
      rs_param.touch.caly = calValY;
     
      printf("1. ox=%d,oy=%d,fx=%f,fy=%f\n"
            ,rs_param.touch.offx
            ,rs_param.touch.offy
            ,rs_param.touch.calx
            ,rs_param.touch.caly); 

      SetTouchCalibration(calValX, calValY);
      SetTouchCalibrationOffset(x_offset, y_offset);
      
      BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDLEFTTOP), BM_SHOWBOX, TRUE, 0);
      BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDRIGHTBOTTOM), BM_SHOWBOX, TRUE, 0);
      BxSendMessage(BxGetDlgItem(hBox, FORM2PCAL_CMDCONTINUE), BM_SHOWBOX, TRUE, 0);
      calState++;
      sprintf(calMsg1,"Press continue.");
      BxRequestPaint(BxGetDlgItem(hBox, FORM2PCAL_TEXTMESSAGE));
     }
     else
     {
       calState = 0;
       break;
     }
   case 22:
   case 23:
   case 24:
   case 25:
   case 26:
   case 27:
   case 28:
   case 29:
   case 30:
     sprintf(calMsg2,"Time left %d sec.", 30-calState);
     calState++;
     BxRequestPaint(BxGetDlgItem(hBox, FORM2PCAL_TEXTMSG));
     break;
   case 31:
     calState = 0;
     break;
 }
 return TRUE;
}

BX_BOOL form2pCal_cmdLeftTop_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL form2pCal_cmdRightBottom_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL form2pCal_cmdContinue_Click(HBOX hBox)
{

  rs_param.touch.initialized=TRUE;
  rs_param.touch.offx = GetTouchXOffset();
  rs_param.touch.offy = GetTouchYOffset();
  rs_param.touch.calx = GetTouchXFactor();
  rs_param.touch.caly = GetTouchYFactor();

  printf("2. ox=%d,oy=%d,fx=%f,fy=%f\n"
        ,rs_param.touch.offx
        ,rs_param.touch.offy
        ,rs_param.touch.calx
        ,rs_param.touch.caly); 

  SaveRSSystemData(&rs_param); 

  BxEndDialog(hBox, IDOK);
  return FALSE;
}

