//Code generated by bxbuilder (c) LMS 2002 
// formLogger.c
#include "Bx.h"
#include "formLogger.h"

BOXSTRUCT formLogger[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formLogger[1], NULL}
 ,{FORMLOGGER_LISTBOX,{20,10,629,579},STATIC,"",BXS_VISIBLE,&formLogger[2], &formLogger[0]}
 ,{FORMLOGGER_CMDMENU,{650,480,779,579},BUTTON,"Menu",BBS_PUSHBUTTON|BXS_VISIBLE,&formLogger[3], &formLogger[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formLogger[0]}
};

BX_BOOL formLoggerProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formLoggerUpdate(hBox);
				return formLoggerUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formLoggerInit(hBox);
				return formLoggerUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMLOGGER_LISTBOX:
             return formLogger_listBox_Click(hBox);
         case FORMLOGGER_CMDMENU:
             return formLogger_cmdMenu_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
