//Code generated by bxbuilder (c) LMS 2002 
// formNumKeyboardUser.c
#include <string.h>
#include <math.h>
#include "cmd.h"
#include "Bx.h"
#include "formNumKeyboard.h"

static BX_BOOL m_init;
static BX_BOOL m_AsFloat = FALSE;
static BX_BOOL m_limit = FALSE;
static BX_BOOL m_initSet;
static BX_INT m_intHit;
static BX_INT m_kommaHit;
static BX_DOUBLE m_dvalue;
static BX_DOUBLE m_dmin;
static BX_DOUBLE m_dmax;
//static BX_S64 m_value;
//static BX_S64 m_min;
//static BX_S64 m_max;
static BX_INT m_value;
static BX_INT m_min;
static BX_INT m_max;
static BX_BOOL m_float;
static BX_CHAR vStr[256];
static BX_CHAR number[256] = "0";

static BX_VOID IncField(HBOX hBox)
{

	if(m_float)
	{
		switch (m_kommaHit) {
			case 1:	sprintf(vStr,"%0.0f", m_dvalue);	break;
			case 2:	sprintf(vStr,"%0.1f", m_dvalue);	break;
			case 3:	sprintf(vStr,"%0.2f", m_dvalue);	break;
			case 4:	sprintf(vStr,"%0.3f", m_dvalue);	break;
			case 5:	sprintf(vStr,"%0.4f", m_dvalue);	break;
			case 6:	sprintf(vStr,"%0.5f", m_dvalue);	break;
			case 7:	sprintf(vStr,"%0.6f", m_dvalue);	break;
		}
	}
	else
	{
		sprintf(vStr,"%d", m_value);
	}
	BxSetBoxText(BxGetDlgItem(hBox, FORMNUMKEYBOARD_TEXTLABEL1), vStr);
}

static BX_VOID DecField(HBOX hBox)
{
	if(m_float)
	{
		switch (m_kommaHit) {
			case 1:	sprintf(vStr,"%0.0f", m_dvalue);	break;
			case 2:	sprintf(vStr,"%0.1f", m_dvalue);	break;
			case 3:	sprintf(vStr,"%0.2f", m_dvalue);	break;
			case 4:	sprintf(vStr,"%0.3f", m_dvalue);	break;
			case 5:	sprintf(vStr,"%0.4f", m_dvalue);	break;
			case 6:	sprintf(vStr,"%0.5f", m_dvalue);	break;
			case 7:	sprintf(vStr,"%0.6f", m_dvalue);	break;
		}
	}

	else
	{
		sprintf(vStr,"%d", m_value);
	}
	BxSetBoxText(BxGetDlgItem(hBox, FORMNUMKEYBOARD_TEXTLABEL1), vStr);
}


static BX_VOID UpdateField(HBOX hBox, BX_INT val)
{
	BX_DOUBLE dVal = 1.0;
	BX_INT i;

	if(m_initSet)
	{
		m_dvalue = 0.0;
		m_value = 0;
		m_kommaHit=1;
		m_float = FALSE;
		m_intHit = 0;
		m_initSet = FALSE;
	}

	if(m_float)
	{
		for(i=1;i<m_kommaHit;i++)
			dVal *= 0.1;

		m_dvalue = m_dvalue + ((BX_DOUBLE)val * dVal);
		switch (m_kommaHit) {
			case 1:	sprintf(vStr,"%0.0f", m_dvalue);	break;
			case 2:	sprintf(vStr,"%0.1f", m_dvalue);	break;
			case 3:	sprintf(vStr,"%0.2f", m_dvalue);	break;
			case 4:	sprintf(vStr,"%0.3f", m_dvalue);	break;
			case 5:	sprintf(vStr,"%0.4f", m_dvalue);	break;
			case 6:	sprintf(vStr,"%0.5f", m_dvalue);	break;
			case 7:	sprintf(vStr,"%0.6f", m_dvalue);	break;
		}
	}
	else
	{
		if(m_intHit < 1)
			m_value = 0;
		m_value = (m_value*10) + val;
//		sprintf(vStr,"%d", (BX_S64)m_value);
		sprintf(vStr,"%d", (BX_INT)m_value);
		m_dvalue = (double)m_value;
	}
	BxSetBoxText(BxGetDlgItem(hBox, FORMNUMKEYBOARD_TEXTLABEL1), vStr);
}

static int AdjustVal(void)
{
	if(m_kommaHit+m_intHit < 9)
	{
		if(m_float)
		{
			if(m_kommaHit < 5)
				m_kommaHit++;
			else
				return 0;
		}
		else
			m_intHit++;
		return 1;
	}
	return 0;
}


BX_BOOL formNumKeyboardUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	BxAssignStringValue(BxGetDlgItem(hBox, FORMNUMKEYBOARD_CMDENTER));
  BxSetStringValue(BxGetDlgItem(hBox, FORMNUMKEYBOARD_CMDENTER), getLanguageLineFromIdx(langptr, 46, "Enter"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMNUMKEYBOARD_CMDCANCEL));
  BxSetStringValue(BxGetDlgItem(hBox, FORMNUMKEYBOARD_CMDCANCEL), getLanguageLineFromIdx(langptr, 3, "Cancel"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMNUMKEYBOARD_CMSCLEAR));
  BxSetStringValue(BxGetDlgItem(hBox, FORMNUMKEYBOARD_CMSCLEAR), getLanguageLineFromIdx(langptr, 47, "Clear"));
	BOXSTRUCT *b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMNUMKEYBOARD_TEXTLABEL1);
  b->lpBoxStr = number;
  BxSetBoxText(BxGetDlgItem(hBox, FORMNUMKEYBOARD_TEXTLABEL1), vStr);
 return TRUE;
}

BX_BOOL formNumKeyboardUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formNumKeyboard_cmdCancel_Click(HBOX hBox)
{
	m_AsFloat = FALSE;
	m_limit = FALSE;
	BxEndDialog(hBox, IDCANCEL);
  return FALSE;
}

BX_BOOL formNumKeyboard_cmd3_Click(HBOX hBox)
{
	if(AdjustVal())
	  UpdateField(hBox, 3);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd2_Click(HBOX hBox)
{
	if(AdjustVal())
	  UpdateField(hBox, 2);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd1_Click(HBOX hBox)
{
	if(AdjustVal())
	  UpdateField(hBox, 1);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd4_Click(HBOX hBox)
{
	if(AdjustVal())
	  UpdateField(hBox, 4);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd5_Click(HBOX hBox)
{
	if(AdjustVal())
	  UpdateField(hBox, 5);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd6_Click(HBOX hBox)
{
	if(AdjustVal())
	  UpdateField(hBox, 6);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmdMinus_Click(HBOX hBox)
{
	if(m_float)
	{
   	m_dvalue -= 1.0/pow(10,m_kommaHit-1);
	}
	else
	{
		m_value -= 1;
	}
	DecField(hBox);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmdPlus_Click(HBOX hBox)
{
	if(m_float)
    	m_dvalue += 1.0/pow(10,m_kommaHit-1);
	else
		m_value += 1;
	IncField(hBox);
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd7_Click(HBOX hBox)
{
	if(AdjustVal())
		UpdateField(hBox, 7);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd8_Click(HBOX hBox)
{
	if(AdjustVal())
		UpdateField(hBox, 8);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmd9_Click(HBOX hBox)
{
	if(AdjustVal())
		UpdateField(hBox, 9);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmdZero_Click(HBOX hBox)
{
	if(AdjustVal())
		UpdateField(hBox, 0);			
  return TRUE;
}

BX_BOOL formNumKeyboard_cmdComma_Click(HBOX hBox)
{
	if(!m_float)
	{
		m_kommaHit=1;
		m_float = TRUE;
		m_dvalue = (BX_DOUBLE)m_value;
		UpdateField(hBox, 0);			
	}
  return TRUE;
}

BX_BOOL formNumKeyboard_cmsNeg_Click(HBOX hBox)
{
	m_dvalue *= -1.0;
	m_value *= -1;
	IncField(hBox);
  return TRUE;
}

BX_BOOL formNumKeyboard_cmdEnter_Click(HBOX hBox)
{
	BX_CHAR msgstr[256];
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];

	if(m_limit)
	{
		if(m_AsFloat)
		{
			if(m_dvalue >= m_dmin && m_dvalue <= m_dmax)
			{
				m_AsFloat = FALSE;
				m_limit = FALSE;
				BxEndDialog(hBox, IDOK);
        return FALSE;
			}
			else
			{
				//sprintf(msgstr, GetLabelMessageFromID(FORMLABELS_M104_FLOAT), m_dmin, m_dmax);
				sprintf(msgstr, "%s %f %f", getLanguageLineFromIdx(langptr, 119, "Value is outside range"),m_dmin, m_dmax);
				//BxMsgBox( hBox, msgstr, GetLabelMessageFromID(FORMLABELS_MESSAGE), 0 );
				BxMsgBox( hBox, msgstr, "Error", 0, getLanguageLineFromIdx(langptr, 74,"Ok") ,getLanguageLineFromIdx(langptr, 3,"Cancel"));
			}
		}
		else
		{
			if(m_value >= m_min && m_value <= m_max)
			{
				m_AsFloat = FALSE;
				m_limit = FALSE;
				BxEndDialog(hBox, IDOK);
        return FALSE;
			}
			else
			{
				//sprintf(msgstr, GetLabelMessageFromID(FORMLABELS_M104), m_dmin, m_dmax);
				sprintf(msgstr, "%s %d %d",getLanguageLineFromIdx(langptr, 119, "Value is outside range"), m_min, m_max);
				//BxMsgBox( hBox, msgstr, GetLabelMessageFromID(FORMLABELS_MESSAGE), 0 );
				BxMsgBox( hBox, msgstr, "Error", 0, getLanguageLineFromIdx(langptr, 74,"Ok") ,getLanguageLineFromIdx(langptr, 3,"Cancel"));
			}
		}
	}
	else
	{
		m_AsFloat = FALSE;
		m_limit = FALSE;
		BxEndDialog(hBox, IDOK);
    return FALSE;
	}
  return TRUE;
}

BX_BOOL formNumKeyboard_cmsClear_Click(HBOX hBox)
{
	m_kommaHit=0;
	m_intHit=0;
	m_float=FALSE;
	m_dvalue = 0.0;
	m_value = 0;
	UpdateField(hBox, 0);			
  return TRUE;
}


static void PutPCT(char* str, char* format, double tal)
{
	char temp[256];
	int i;
	sprintf(temp,format,tal);
	for(i=strlen(temp)-1;i>0&&temp[i]=='0';i--);
	if(i>0&&temp[i]=='.') i--;
	*str='\0';
	if(i>=0) memcpy(str,temp,i+1);
	str[i+1]='\0';
}

BX_VOID BxVirtNumBox_SetFloatValue(BX_DOUBLE val)
{
	m_dvalue = val;
	PutPCT(vStr,"%6.4f", m_dvalue);
	m_kommaHit = 1;
	m_float = TRUE;
	m_intHit = 0;
	m_value = 0;
	m_init = FALSE;
	m_initSet = TRUE;
	m_AsFloat = TRUE;
}


BX_DOUBLE BxVirtNumBox_GetFloatValue(BX_VOID)
{
	return m_dvalue;
}

BX_VOID BxVirtNumBox_SetValue(BX_S64 val)
{
	m_value = val;
//	sprintf(vStr,"%d", (BX_S64)m_value);
	sprintf(vStr,"%d", (BX_INT)m_value);
	m_intHit = 0;
	m_float = FALSE;
	m_dvalue = 0.0;
	m_kommaHit = 1;
	m_init = FALSE;
	m_initSet = TRUE;
	m_AsFloat = FALSE;
}

BX_S64 BxVirtNumBox_GetValue(BX_VOID)
{
	return m_value;
}

BX_VOID BxVirtNumBox_SetFloatLimits(BX_DOUBLE min, BX_DOUBLE max)
{
	m_limit = TRUE;
	m_dmin = min;
	m_dmax = max;
}

BX_VOID BxVirtNumBox_SetLimits(BX_S64 min, BX_S64 max)
{
	m_limit = TRUE;
	m_min = min;
	m_max = max;
}

BX_INT VirtNumKeyBox( HBOX hBox)
{
  HBOX hvkeybox;
  BX_INT rtnVal;

  if(m_init)
  {
    m_float = FALSE;
    m_dvalue = 0.0;
    m_value = 0;
    m_kommaHit = 1;
    m_intHit = 0;
  }

  if(hBox == NULL)
    return -1;

  formNumKeyboard[0].bParent = (PBOXSTRUCT)hBox;

  hvkeybox = BxCreateDialog(GetAppInstance(hBox), &formNumKeyboard[0], (BXDLGPROC)formNumKeyboardProc);
  rtnVal = DoModal(hvkeybox);

  m_init = TRUE;

  formNumKeyboard[0].bParent = NULL;

  ShowDialogBox(hBox);
  BxUpdateView(hBox);

  return rtnVal;
}
