//Code generated by bxbuilder (c) LMS 2002 
// formLoggerCode.c
#include "Bx.h"
#include "formLogger.h"

BXLISTSTRUCT formLogger_listBoxList;
BX_VOID formLoggerInit(HBOX hBox)
{
  BxList_Create(BxGetDlgItem(hBox, FORMLOGGER_LISTBOX), &formLogger_listBoxList, 0);
}

BX_VOID formLoggerUpdate(HBOX hBox)
{
}

