//Code generated by bxbuilder (c) LMS 2002 
// formOffsetPathUser.c
#include "Bx.h"
#include "formOffsetPath.h"
#include "formJogIk.h"

#include "tmpnrobot.h"

BX_BOOL formOffsetPathUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDX));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDY));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDZ));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDV));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDW));
  return TRUE;
}

BX_BOOL formOffsetPathUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formOffsetPath_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDCANCEL);
  return TRUE;
}

BX_BOOL formOffsetPath_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);

  return TRUE;
}

BX_BOOL formOffsetPath_cmdJogIk_Click(HBOX hBox)
{
  HBOX hBx;
  
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formJogIk[0], formJogIkProc);
  if(DoModal(hBx)==IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDX), trobot->m_worldPoint.x);
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDY), trobot->m_worldPoint.y);
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDZ), trobot->m_worldPoint.z);
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDV), trobot->m_worldPoint.v);
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDW), trobot->m_worldPoint.w);

  }
  return TRUE;
}

BX_BOOL formOffsetPath_cmdZ_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDZ)));
  BxVirtNumBox_SetFloatLimits(trobot->m_min.z, trobot->m_max.z);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDZ), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formOffsetPath_cmdX_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDX)));
  BxVirtNumBox_SetFloatLimits(trobot->m_min.x, trobot->m_max.x);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDX), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formOffsetPath_cmdV_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDV)));
  BxVirtNumBox_SetFloatLimits(trobot->m_min.v, trobot->m_max.v);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDV), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formOffsetPath_cmdY_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDY)));
  BxVirtNumBox_SetFloatLimits(trobot->m_min.y, trobot->m_max.y);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDY), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formOffsetPath_cmdW_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDW)));
  BxVirtNumBox_SetFloatLimits(trobot->m_min.w, trobot->m_max.w);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMOFFSETPATH_CMDW), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

