//Copyright (C) 2005 by MPN A/S - Guided by vision(R)
// formLoadCell.h
#if !defined(FORMLOADCELL_H)
#define FORMLOADCELL_H
#include "Bx.h"
#include "formLoadCellUser.h"
#define FORMLOADCELL_TEXTLABEL2_2_2 1
#define FORMLOADCELL_CMDCLOSE 2
extern BX_BOOL formLoadCell_cmdClose_Click(HBOX hBox);
#define FORMLOADCELL_LABTYPE 3
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_6 4
#define FORMLOADCELL_TEXTLABEL2_2_2_2_3 5
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_2_2 6
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_3_2 7
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_4_2 8
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_4_2_2 9
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_4_2_3 10
#define FORMLOADCELL_TEXTLABEL2_2_2_2_2_4_2_4 11
#define FORMLOADCELL_LABMODNAME 12
#define FORMLOADCELL_IWORD1 13
#define FORMLOADCELL_IWORD2 14
#define FORMLOADCELL_IWORD3 15
#define FORMLOADCELL_IWORD4 16
#define FORMLOADCELL_IWORD5 17
#define FORMLOADCELL_IWORD8 18
#define FORMLOADCELL_IWORD7 19
#define FORMLOADCELL_IWORD6 20
#define FORMLOADCELL_LABIWORD1 21
#define FORMLOADCELL_LABIWORD2 22
#define FORMLOADCELL_LABIWORD3 23
#define FORMLOADCELL_LABIWORD4 24
#define FORMLOADCELL_LABIWORD5 25
#define FORMLOADCELL_LABIWORD6 26
#define FORMLOADCELL_LABIWORD7 27
#define FORMLOADCELL_LABIWORD8 28
extern BX_CHAR formLoadCellText[][MAXLANGUAGE][255];
extern BOXSTRUCT formLoadCell[];
extern BX_BOOL formLoadCellProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formLoadCellUpdate(HBOX hBox);
extern BX_VOID formLoadCellInit(HBOX hBox);
#endif // FORMLOADCELL_H
