//Code generated by bxbuilder (c) LMS 2002
// formPathEditorUser.c
#include "Bx.h"
#include "formPathEditor.h"
#include "formPathView.h"
#include "formJogIk.h"

#include "tmclnx.h"
#include "rs.h"
#include "tmpnrobot.h"


static BXMENUSTRUCT pBxMenu;
BX_CHAR pathFileName[256] = "";
static BX_INT pathIndex = -1;

static BX_VOID setupList(HBOX hBox)
{
//  BX_CHAR cmd[256];
//  BX_INT i;
//  BX_INT lineNum = 1;
    
  while(BxList_GetCount(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))>0)
    BxList_DeleteString(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), 0);
/*
  for(i=0;i<tpathdef.maxidx;i++)
  {
    sprintf(cmd,"%d WSP %.4f, %.4f, %.4f, %.4f, %.4f",
            lineNum,
            tpathdef.keypoint[i].x,
            tpathdef.keypoint[i].y,
            tpathdef.keypoint[i].z,
            tpathdef.keypoint[i].v,
            tpathdef.keypoint[i].w
            );
    lineNum++;
    BxList_AddString(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), cmd);
  }
*/
//  BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), GetActualNumber());
  BxRequestPaint(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX));
}

BX_VOID DeletePathPosition(BX_INT index)
{
//  BX_INT i;
/*
  for(i=index;i<tpathdef.maxidx;i++)
  {
    tpathdef.keypoint[i].x = tpathdef.keypoint[i+1].x;
    tpathdef.keypoint[i].y = tpathdef.keypoint[i+1].y;
    tpathdef.keypoint[i].z = tpathdef.keypoint[i+1].z;
    tpathdef.keypoint[i].v = tpathdef.keypoint[i+1].v;
    tpathdef.keypoint[i].w = tpathdef.keypoint[i+1].w;
  }
  tpathdef.maxidx--;
*/
}

BX_BOOL SavePathFile(BX_PSTRING filename)
{
  FILE *fp;
  unsigned short cmd_version = 0x0001;
//  BX_INT i;

  fp = fopen(filename,"w");
  if(fp==NULL)
    return FALSE;

  fprintf(fp,"VERSION %X\n", cmd_version);
/*
  fprintf(fp,"MAXIDX %d\n", tpathdef.maxidx);

  for(i=0;i<tpathdef.maxidx;i++)
  {
    fprintf(fp,"WSP %lf, %lf, %lf, %lf, %lf %d %d %d\n",
      tpathdef.keypoint[i].x,
      tpathdef.keypoint[i].y,
      tpathdef.keypoint[i].z,
      tpathdef.keypoint[i].v,
      tpathdef.keypoint[i].w,
      tpathdef.numofsamples,
      tpathdef.keypoint[i].tanxyz,
      tpathdef.keypoint[i].tanw
      );
  }
*/
  fclose(fp);
  return TRUE;
}

BX_BOOL LoadPathFile(BX_PSTRING filename)
{
  FILE *fp;
  unsigned int v;
//  BX_INT i;

  fp = fopen(filename,"r");
  if(fp==NULL)
    return FALSE;

  fscanf(fp,"VERSION %X\n", &v);
/*
  fscanf(fp,"MAXIDX %d\n", &tpathdef.maxidx);

  for(i=0;i<tpathdef.maxidx;i++)
  {
    fscanf(fp,"WSP %lf, %lf, %lf, %lf, %lf %d %d %d\n",
      &tpathdef.keypoint[i].x,
      &tpathdef.keypoint[i].y,
      &tpathdef.keypoint[i].z,
      &tpathdef.keypoint[i].v,
      &tpathdef.keypoint[i].w,
      &tpathdef.numofsamples,
      &tpathdef.keypoint[i].tanxyz,
      &tpathdef.keypoint[i].tanw
      );
  }
*/
  fclose(fp);
  return TRUE;
}

BX_BOOL formPathEditorUserInit(HBOX hBox,BX_LPARAM lParam)
{
  PBOXSTRUCT b = (PBOXSTRUCT)BxGetDlgItem(hBox, FORMPATHEDITOR_TEXTNAME);

  b->lpBoxStr = pathFileName;
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDSPEED));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDSPEED), (BX_INT)GetAktuelSpeed(axis_t));

  BxAssignIntValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDRATE));

  if(LoadPathFile(pathFileName)==FALSE)
  {
//    tpathdef.maxidx=0;
    pathIndex = -1;
  }
  else
    pathIndex = 0;
  setupList(hBox);
  BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), pathIndex);
//  BxSetIntValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDRATE), tpathdef.numofsamples);
  return TRUE;
}

BX_BOOL formPathEditorUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formPathEditor_cmdPrev_Click(HBOX hBox)
{
  if(pathIndex > 0)
  {
    pathIndex--;
//    BxSetIntValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDRATE), tpathdef.numofsamples);
    BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), pathIndex);
//    SetPosition(tpathdef.keypoint[pathIndex].x,tpathdef.keypoint[pathIndex].y,tpathdef.keypoint[pathIndex].z,tpathdef.keypoint[pathIndex].v, tpathdef.keypoint[pathIndex].w);
//    WaitIdle();
  }
  return TRUE;
}

BX_BOOL formPathEditor_cmdNext_Click(HBOX hBox)
{
/*
  if(pathIndex < tpathdef.maxidx-1)
  {
    pathIndex++;
    BxSetIntValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDRATE), tpathdef.numofsamples);
    BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), pathIndex);
    SetPosition(tpathdef.keypoint[pathIndex].x,tpathdef.keypoint[pathIndex].y,tpathdef.keypoint[pathIndex].z, tpathdef.keypoint[pathIndex].v,tpathdef.keypoint[pathIndex].w);
    WaitIdle();
  }
*/
  return TRUE;
}

BX_BOOL formPathEditor_listBox_Click(HBOX hBox)
{
  BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), pathIndex);
  return TRUE;
}

BX_BOOL formPathEditor_cmdAdd_Click(HBOX hBox)
{
/*
  HBOX hBx;
  BX_INT i;
  BX_INT idx = BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX));
  
  if(tpathdef.maxidx < MAXKEYPOINTS)
  {
    hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formJogIk[0], formJogIkProc);
    if(DoModal(hBx)==IDOK)
    {
      if(idx > -1 && idx < tpathdef.maxidx)
      {
        for(i=tpathdef.maxidx;i>=idx;i--)
        {
          tpathdef.keypoint[i+1].x =  tpathdef.keypoint[i].x;
          tpathdef.keypoint[i+1].y =  tpathdef.keypoint[i].y;
          tpathdef.keypoint[i+1].z =  tpathdef.keypoint[i].z;
          tpathdef.keypoint[i+1].v =  tpathdef.keypoint[i].v;
          tpathdef.keypoint[i+1].w =  tpathdef.keypoint[i].w;
          tpathdef.keypoint[i+1].tanxyz =  tpathdef.keypoint[i].tanxyz;
          tpathdef.keypoint[i+1].tanw =  tpathdef.keypoint[i].tanw;
        }
        tpathdef.keypoint[idx+1].x =  trobot.m_worldPoint.x;
        tpathdef.keypoint[idx+1].y =  trobot.m_worldPoint.y;
        tpathdef.keypoint[idx+1].z =  trobot.m_worldPoint.z;
        tpathdef.keypoint[idx+1].v =  trobot.m_worldPoint.v;
        tpathdef.keypoint[idx+1].w =  trobot.m_worldPoint.w;
        tpathdef.keypoint[idx+1].tanxyz =  50;
        tpathdef.keypoint[idx+1].tanw =  50;
        tpathdef.maxidx++;
        BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), idx+1);
      }
      else
      {
        tpathdef.keypoint[tpathdef.maxidx].x =  trobot.m_worldPoint.x;
        tpathdef.keypoint[tpathdef.maxidx].y =  trobot.m_worldPoint.y;
        tpathdef.keypoint[tpathdef.maxidx].z =  trobot.m_worldPoint.z;
        tpathdef.keypoint[tpathdef.maxidx].v =  trobot.m_worldPoint.v;
        tpathdef.keypoint[tpathdef.maxidx].w =  trobot.m_worldPoint.w;
        tpathdef.keypoint[tpathdef.maxidx].tanxyz =  50;
        tpathdef.keypoint[tpathdef.maxidx].tanw =  50;
        tpathdef.maxidx++;
      }
      setupList(hBox);
      BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), tpathdef.maxidx-1);
    }
  }
*/
  return TRUE;
}

BX_BOOL formPathEditor_cmdEdit_Click(HBOX hBox)
{
//  HBOX hBx;
/*
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formJogIk[0], formJogIkProc);
  if(DoModal(hBx)==IDOK)
  {
    tpathdef.keypoint[BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))].x =  trobot.m_worldPoint.x;
    tpathdef.keypoint[BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))].y =  trobot.m_worldPoint.y;
    tpathdef.keypoint[BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))].z =  trobot.m_worldPoint.z;
    tpathdef.keypoint[BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))].v =  trobot.m_worldPoint.v;
    tpathdef.keypoint[BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))].w =  trobot.m_worldPoint.w;
    setupList(hBox);
  }
*/
  return TRUE;
}

BX_BOOL formPathEditor_cmdCopy_Click(HBOX hBox)
{
/*
  BX_INT idx, i;
  BX_INT selidx = BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX));
  
  if(tpathdef.maxidx < MAXKEYPOINTS)
  {
    BxVirtNumBox_SetLimits(1, tpathdef.maxidx);
    if(VirtNumKeyBox( hBox ) == IDOK)
    {
      idx = BxVirtNumBox_GetValue();
      idx--;
      
      if(selidx > -1 && selidx < tpathdef.maxidx)
      {
        for(i=tpathdef.maxidx;i>=selidx;i--)
        {
          tpathdef.keypoint[i+1].x =  tpathdef.keypoint[i].x;
          tpathdef.keypoint[i+1].y =  tpathdef.keypoint[i].y;
          tpathdef.keypoint[i+1].z =  tpathdef.keypoint[i].z;
          tpathdef.keypoint[i+1].v =  tpathdef.keypoint[i].v;
          tpathdef.keypoint[i+1].w =  tpathdef.keypoint[i].w;
          tpathdef.keypoint[i+1].tanxyz =  tpathdef.keypoint[i].tanxyz;
          tpathdef.keypoint[i+1].tanw =  tpathdef.keypoint[i].tanw;
        }
        if(idx > selidx)
        {
          tpathdef.keypoint[selidx+1].x =  tpathdef.keypoint[idx+1].x;
          tpathdef.keypoint[selidx+1].y =  tpathdef.keypoint[idx+1].y;
          tpathdef.keypoint[selidx+1].z =  tpathdef.keypoint[idx+1].z;
          tpathdef.keypoint[selidx+1].v =  tpathdef.keypoint[idx+1].v;
          tpathdef.keypoint[selidx+1].w =  tpathdef.keypoint[idx+1].w;
          tpathdef.keypoint[selidx+1].tanxyz =  tpathdef.keypoint[idx+1].tanxyz;
          tpathdef.keypoint[selidx+1].tanw =  tpathdef.keypoint[idx+1].tanw;
        }
        else
        {
          tpathdef.keypoint[selidx+1].x =  tpathdef.keypoint[idx].x;
          tpathdef.keypoint[selidx+1].y =  tpathdef.keypoint[idx].y;
          tpathdef.keypoint[selidx+1].z =  tpathdef.keypoint[idx].z;
          tpathdef.keypoint[selidx+1].v =  tpathdef.keypoint[idx].v;
          tpathdef.keypoint[selidx+1].w =  tpathdef.keypoint[idx].w;
          tpathdef.keypoint[selidx+1].tanxyz =  tpathdef.keypoint[idx].tanxyz;
          tpathdef.keypoint[selidx+1].tanw =  tpathdef.keypoint[idx].tanw;
        }
        tpathdef.maxidx++;
        BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), selidx+1);
      }
      else
      {
        tpathdef.keypoint[tpathdef.maxidx].x =  tpathdef.keypoint[idx].x;
        tpathdef.keypoint[tpathdef.maxidx].y =  tpathdef.keypoint[idx].y;
        tpathdef.keypoint[tpathdef.maxidx].z =  tpathdef.keypoint[idx].z;
        tpathdef.keypoint[tpathdef.maxidx].v =  tpathdef.keypoint[idx].v;
        tpathdef.keypoint[tpathdef.maxidx].w =  tpathdef.keypoint[idx].w;
        tpathdef.keypoint[tpathdef.maxidx].tanxyz =  tpathdef.keypoint[idx].tanxyz;
        tpathdef.keypoint[tpathdef.maxidx].tanw =  tpathdef.keypoint[idx].tanw;
        tpathdef.maxidx++;
      }
      setupList(hBox);
      BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), tpathdef.maxidx-1);
    }
  }
*/
  return TRUE;
}

BX_BOOL formPathEditor_cmdDel_Click(HBOX hBox)
{
/*
  int index = BxList_GetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX));

  if(index > -1)
  {
    if(BxMsgBox(hBox, "nsker du at slette aktuelle kommando?", "Slette Kommando", 0)==IDOK)
    {
      DeletePathPosition(index);
      setupList(hBox);
      if(index <= tpathdef.maxidx)
        BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), index);
      else
        BxList_SetSelected(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), tpathdef.maxidx - 1);
    }
  }
*/
  return TRUE;
}

BX_BOOL formPathEditor_cmdSpeed_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDSPEED)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDSPEED), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formPathEditor_cmdRun_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPathEditor_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);

  while(BxList_GetCount(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))>0)
    BxList_DeleteString(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), 0);

  SavePathFile(pathFileName);
  
  return TRUE;
}

BX_BOOL formPathEditor_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDCANCEL);

  while(BxList_GetCount(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX))>0)
    BxList_DeleteString(BxGetDlgItem(hBox, FORMPATHEDITOR_LISTBOX), 0);

  return TRUE;
}

BX_BOOL formPathEditor_cmdMenu_Click(HBOX hBox)
{
  HBOX hBx, hCmd, hAdd, hRtn;

  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDMENU), &pBxMenu);
  hCmd = BxMenu_Add(hBx ,"Command", SUB, NULL, TRUE, NULL);
  hAdd = BxMenu_Add(hCmd ,"Add", SUB, NULL, TRUE, NULL);
  BxMenu_Add(hAdd ,"X,Y,Z", MENU, formPathEditor_cmdAdd_Click, TRUE, NULL);
  BxMenu_Add(hCmd ,"Edit", MENU, formPathEditor_cmdEdit_Click, TRUE, NULL);
  BxMenu_Add(hCmd ,"Copy", MENU, formPathEditor_cmdCopy_Click, TRUE, NULL);
  BxMenu_Add(hCmd ,"Del", MENU, formPathEditor_cmdDel_Click, TRUE, NULL);
  hRtn = BxMenu_Add(hBx ,"Return", SUB, NULL, TRUE, NULL);
  BxMenu_Add(hRtn ,"Ok", MENU, formPathEditor_cmdReturn_Click, TRUE, NULL);
  BxMenu_Add(hRtn ,"Cancel", MENU, formPathEditor_cmdCancel_Click, TRUE, NULL);
  DoMenu(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDMENU));
  return TRUE;
}

BX_BOOL SetPathEditorFileName(BX_PSTRING pstr)
{
  BxStringCopy(pathFileName, pstr);
  return TRUE;
}

BX_PSTRING GetPathEditorFileName(BX_VOID)
{
  return pathFileName;
}

BX_BOOL formPathEditor_cmdRate_Click(HBOX hBox)
{
/*
  BxVirtNumBox_SetFloatValue(BxGetIntValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDRATE)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetIntValue(BxGetDlgItem(hBox, FORMPATHEDITOR_CMDRATE), BxVirtNumBox_GetValue());
    tpathdef.numofsamples = BxVirtNumBox_GetValue();
  }
*/
  return TRUE;
}

BX_BOOL formPathEditor_cmdView_Click(HBOX hBox)
{
  HBOX hBx;
  
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formPathView[0], formPathViewProc);
  if(DoModal(hBx)==IDOK)
  {
  }
  return TRUE;
}

