//Code generated by bxbuilder (c) LMS 2002 
// formAVIMod.c
#include "Bx.h"
#include "formAVIMod.h"

BOXSTRUCT formAVIMod[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formAVIMod[1], NULL}
 ,{FORMAVIMOD_TEXTLABEL2_2_2,{20,70,99,104},STATIC,"Name :",BXS_VISIBLE,&formAVIMod[2], &formAVIMod[0]}
 ,{FORMAVIMOD_CMDCLOSE,{650,480,779,579},BUTTON,"Close",BBS_PUSHBUTTON|BXS_VISIBLE,&formAVIMod[3], &formAVIMod[0]}
 ,{FORMAVIMOD_LABMODNAME,{190,70,619,104},STATIC,"2D4 - Module",BXS_BORDER|BXS_VISIBLE,&formAVIMod[4], &formAVIMod[0]}
 ,{FORMAVIMOD_LABTYPE,{280,10,529,44},STATIC,"Advantys modules",BSS_CENTER|BXS_VISIBLE,&formAVIMod[5], &formAVIMod[0]}
 ,{FORMAVIMOD_TEXTLABEL1,{20,160,49,194},STATIC,"1",BXS_VISIBLE,&formAVIMod[6], &formAVIMod[0]}
 ,{FORMAVIMOD_DATA1,{60,160,169,194},STATIC,"Data1",BXS_BORDER|BXS_VISIBLE,&formAVIMod[7], &formAVIMod[0]}
 ,{FORMAVIMOD_TEXTLABEL2,{20,210,49,244},STATIC,"2",BXS_VISIBLE,&formAVIMod[8], &formAVIMod[0]}
 ,{FORMAVIMOD_DATA2,{60,210,169,244},STATIC,"Data2",BXS_BORDER|BXS_VISIBLE,&formAVIMod[9], &formAVIMod[0]}
 ,{FORMAVIMOD_TEXTLABEL2_2,{20,260,49,294},STATIC,"2",BXS_VISIBLE,&formAVIMod[10], &formAVIMod[0]}
 ,{FORMAVIMOD_TEXTLABEL2_3,{20,310,49,344},STATIC,"2",BXS_VISIBLE,&formAVIMod[11], &formAVIMod[0]}
 ,{FORMAVIMOD_LABCONNECT1,{190,160,619,194},STATIC,"Connect1",BXS_BORDER|BXS_VISIBLE,&formAVIMod[12], &formAVIMod[0]}
 ,{FORMAVIMOD_LABCONNECT2,{190,210,619,244},STATIC,"Connect2",BXS_BORDER|BXS_VISIBLE,&formAVIMod[13], &formAVIMod[0]}
 ,{FORMAVIMOD_LABCONNECT4,{190,310,619,344},STATIC,"Connect4",BXS_BORDER|BXS_VISIBLE,&formAVIMod[14], &formAVIMod[0]}
 ,{FORMAVIMOD_LABCONNECT3,{190,260,619,294},STATIC,"Connect3",BXS_BORDER|BXS_VISIBLE,&formAVIMod[15], &formAVIMod[0]}
 ,{FORMAVIMOD_DATA3,{60,260,169,294},STATIC,"Data3",BXS_BORDER|BXS_VISIBLE,&formAVIMod[16], &formAVIMod[0]}
 ,{FORMAVIMOD_DATA4,{60,310,169,344},STATIC,"Data4",BXS_BORDER|BXS_VISIBLE,&formAVIMod[17], &formAVIMod[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formAVIMod[0]}
};

BX_BOOL formAVIModProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formAVIModUpdate(hBox);
				return formAVIModUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formAVIModInit(hBox);
				return formAVIModUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMAVIMOD_CMDCLOSE:
             return formAVIMod_cmdClose_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
