//Code generated by bxbuilder (c) LMS 2002 
// formPMCtrl.h
#if !defined(FORMPMCTRL_H)
#define FORMPMCTRL_H
#include "Bx.h"
#include "formPMCtrlUser.h"
#define FORMPMCTRL_TEXTLABEL2_2 1
#define FORMPMCTRL_CHKGRIPOUT 2
extern BX_BOOL formPMCtrl_chkGripOut_Click(HBOX hBox);
#define FORMPMCTRL_LABOUT_2_2 3
#define FORMPMCTRL_CHKGRIPIN 4
extern BX_BOOL formPMCtrl_chkGripIn_Click(HBOX hBox);
#define FORMPMCTRL_LABPHOTO2 5
#define FORMPMCTRL_CHKGRIP_OUT 6
extern BX_BOOL formPMCtrl_chkGrip_Out_Click(HBOX hBox);
#define FORMPMCTRL_CHKPHOTO1 7
extern BX_BOOL formPMCtrl_chkPhoto1_Click(HBOX hBox);
#define FORMPMCTRL_CHKPHOTO2 8
extern BX_BOOL formPMCtrl_chkPhoto2_Click(HBOX hBox);
#define FORMPMCTRL_LABPHOTO1 9
#define FORMPMCTRL_CHKGRIP_IN 10
extern BX_BOOL formPMCtrl_chkGrip_In_Click(HBOX hBox);
#define FORMPMCTRL_LABOUT_2 11
#define FORMPMCTRL_LABOUT 12
#define FORMPMCTRL_CHKCYL1UP 13
extern BX_BOOL formPMCtrl_chkCyl1Up_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL1DOWN 14
extern BX_BOOL formPMCtrl_chkCyl1Down_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL1BOTTOM 15
extern BX_BOOL formPMCtrl_chkCyl1Bottom_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL1MID 16
extern BX_BOOL formPMCtrl_chkCyl1Mid_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL1TOP 17
extern BX_BOOL formPMCtrl_chkCyl1Top_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL2TOP 18
extern BX_BOOL formPMCtrl_chkCyl2Top_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL2MID 19
extern BX_BOOL formPMCtrl_chkCyl2Mid_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL2BOTTOM 20
extern BX_BOOL formPMCtrl_chkCyl2Bottom_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL2UP 21
extern BX_BOOL formPMCtrl_chkCyl2Up_Click(HBOX hBox);
#define FORMPMCTRL_CHKCYL2DOWN 22
extern BX_BOOL formPMCtrl_chkCyl2Down_Click(HBOX hBox);
#define FORMPMCTRL_CMDCLOSE 23
extern BX_BOOL formPMCtrl_cmdClose_Click(HBOX hBox);
#define FORMPMCTRL_CMDRESET 24
extern BX_BOOL formPMCtrl_cmdReset_Click(HBOX hBox);
extern BX_CHAR formPMCtrlText[][MAXLANGUAGE][255];
extern BOXSTRUCT formPMCtrl[];
extern BX_BOOL formPMCtrlProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formPMCtrlUpdate(HBOX hBox);
extern BX_VOID formPMCtrlInit(HBOX hBox);
#endif // FORMPMCTRL_H
