//Code generated by bxbuilder (c) LMS 2002 
// formSTMCtrlUser.c

#include <unistd.h>

#include "Bx.h"
#include "robostackerBxr.h"
#include "formSTMCtrl.h"
#include "formScopeData.h"
#include "formEditFrame.h"
#include "formItemEdit.h"
#include "formEditCPPattern.h"
#include "cmd.h"

extern char *fixpointsFrameName;
extern tmpnCPPattern *editcppattern;
extern char *itemName;

//tmpnScopeData scopeitem[10];

static int stateMachineNum = 0;

BX_BOOL formSTMCtrlUserInit(HBOX hBox,BX_LPARAM lParam)
{
  int i;
  char s[128];
  tmpnStateMachine *stm;
	extern BxIcon *iconscope;
  s[0]=0;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDHALT));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDCLOSE), getLanguageLineFromIdx(langptr, 54, "Close"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDRESTART));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDRESTART), getLanguageLineFromIdx(langptr, 84, "Restart"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDSCOPE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDSCOPE), getLanguageLineFromIdx(langptr, 85, "Scope"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_GROUPBOX2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_GROUPBOX2), getLanguageLineFromIdx(langptr, 86, "State"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_GROUPBOX1));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_GROUPBOX1), getLanguageLineFromIdx(langptr, 87, "Name"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDEDIT));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDEDIT), getLanguageLineFromIdx(langptr, 80, "Edit"));
	BxSendMessage(BxGetDlgItem(hBox, FORMSTMCTRL_CMDSCOPE), BBM_SETICON, (BX_WPARAM)iconscope, 0);
  stm=&tworkcell->statemachines.statemachine[stateMachineNum];
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_LABNAME));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_LABSTATE));
  for(i=0;i<stm->numinput;i++)
    BxList_AddString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), s);
  for(i=0;i<stm->numoutput;i++)
    BxList_AddString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), s);
  for(i=0;i<stm->numtimeout;i++)
    BxList_AddString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), s);
  for(i=0;i<stm->numvalue;i++)
    BxList_AddString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), s);
  for(i=0;i<stm->numlink;i++)
    BxList_AddString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), s);
  return TRUE;
}

BX_BOOL formSTMCtrl_BuildValueString(struct tmpnStateMachineValue *value, char* s)
{
  if(value->type == CONSTANT)
  {
    if(value->subtype==0)
      sprintf(s, "Const %s %d", value->name, value->data );
    else
      sprintf(s, "Const %s %0.4f", value->name, value->fdata );
  }
  else if(value->type == LINKVALUE)
  {
    if(value->linkvalue != NULL)
    {
      char s2[128];
      if(formSTMCtrl_BuildValueString(value->linkvalue, s2))
        sprintf(s,"linkValue %s %s", value->name, s2);
      else
        return FALSE;
    }
    else //remotevalue
    {
			int dummy;
      if(value->subtype==0)
        sprintf(s, "linkValue(remote) %s %d", value->name, getArgValueInt(value,"",&dummy));
      else
        sprintf(s, "linkValue(remote) %s %0.4f", value->name, getArgValueFloat(value,"",&dummy));
    }
  }
  else if(value->type == TABLE)
  {
    if(value->subtype==0)
      sprintf(s, "Table %s %d", value->name, value->data );
    else
      sprintf(s, "Table %s %0.4f", value->name, value->fdata );
  }
  else if(value->type == PATHHANDLE)
  {
    tmpnStateMachineValue *val=value;
    sprintf(s,"Path %s state=%s mode=%d type=%d",val->name,getStateString(val->path->state),val->path->key.mode,val->path->key.type);
  }
  else if(value->type == FRAME)
  {
    tmpnStateMachineValue *val=value;
    sprintf(s,"Frame %s x=%0.1f y=%0.1f z=%0.1f v=%0.1f w=%0.1f",val->name,val->frame->x,val->frame->y,val->frame->z,val->frame->v,val->frame->w);
  }
  else if(value->type == ITEM)
  {
    tmpnStateMachineValue *val=value;
    sprintf(s,"Item %s sy=%0.2f gy=%0.2f my=%0.2f gx=%0.2f",val->name,val->item->sy,val->item->gy,val->item->my,val->item->gx);
  }
  else if(value->type == PATTERN)
  {
    tmpnStateMachineValue *val=value;
    sprintf(s,"Pattern %s idx=%d",val->name,val->data);
  }
  else if(value->type == CPPATTERN)
  {
    tmpnStateMachineValue *val=value;
    if(val->cppattern != NULL)
      sprintf(s,"CPPattern %s layeridx=%d pppidx=%d",val->name,val->cppattern->selectedItem, val->cppattern->selectedPPP);
    else
      return FALSE;
  }
  else
  {
    if(value->subtype==0)
      sprintf(s, "Value %s %d", value->name, value->data );
    else
      sprintf(s, "Value %s %0.4f", value->name, value->fdata );
  }
  return TRUE;
}

//if string format is changed remember to change format in formSTMCtrl_cmdEdit_Click
BX_BOOL formSTMCtrlUserUpdate(HBOX hBox)
{
  char s[1024];
  int sn=0, i;
  tmpnStateMachine *stm;
  tmpnStateMachine *link;
    
	stm=&tworkcell->statemachines.statemachine[stateMachineNum];
	
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_LABNAME), stm->name);
	BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_LABSTATE), stm->state[stm->istate].name);

	if(!strcmp(stm->state[stm->istate].name,"ST_HALT"))
  { 
    BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDHALT), "Idle");
  }
  else
  {
    BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDHALT), "Halt");
  }
	
	for(i=0;i<stm->numinput;i++)
	{
		if (stm->input[i].iotype==INPUT)
		{
			if(stm->input[i].connect->connectType==IBITDATA
				 ||stm->input[i].connect->connectType==LEGACYDATA)
				sprintf(s, "Input %s %s", stm->input[i].name, *stm->input[i].connect->udata & stm->input[i].connect->bitidx ? "ON" : "OFF" );
			else if(stm->input[i].connect->connectType==ISHORTDATA)
				sprintf(s, "Input %s %d", stm->input[i].name, *stm->input[i].connect->sdata);
			else 
				sprintf(s, "Input %s %d", stm->input[i].name, *stm->input[i].connect->udata);
		}
		else if (stm->input[i].iotype==INCOMSK)
			sprintf(s, "Input %s %0.4f", stm->input[i].name, *stm->input[i].comskconnect->data/stm->input[i].comskconnect->factor);
		else if (stm->input[i].iotype==INLC)
			sprintf(s, "Input %s %0.4f", stm->input[i].name, stm->input[i].loadcellconnect->fdata);
		else if (stm->input[i].iotype==INMAC)
		{
			if (stm->input[i].macconnect->type==MAC_LONGINT||stm->input[i].macconnect->type==MAC_SHORTINT||stm->input[i].macconnect->type==MAC_SHORTUINT)
				sprintf(s, "Input %s %d", stm->input[i].name, stm->input[i].macconnect->data);
			else
				sprintf(s, "Input %s %0.4f", stm->input[i].name, stm->input[i].macconnect->fdata);
		}
		else if (stm->input[i].iotype==INICPCON)
			sprintf(s, "Input %s %s", stm->input[i].name, *stm->input[i].icpconnect->udata & (1<<stm->input[i].icpconnect->bitpos) ? "ON" : "OFF" );
		BxList_SetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), sn++, s);
	}
	for(i=0;i<stm->numoutput;i++)
	{
		if (stm->output[i].iotype==OUTPUT)
		{
			if(stm->output[i].connect->connectType==OBITDATA
				 ||stm->output[i].connect->connectType==LEGACYDATA)
				sprintf(s,"Output %s %s", stm->output[i].name, *stm->output[i].connect->udata & stm->output[i].connect->bitidx ? "ON" : "OFF" );
			else if(stm->output[i].connect->connectType==OSHORTDATA)
				sprintf(s,"Output %s %d", stm->output[i].name, *stm->output[i].connect->sdata);
			else
				sprintf(s,"Output %s %d", stm->output[i].name, *stm->output[i].connect->udata);
		}
		else if (stm->output[i].iotype==OUTCOMSK)
			sprintf(s,"Output %s %0.4f", stm->output[i].name, stm->output[i].comskconnect->fdata);
		else if (stm->output[i].iotype==OUTMAC)
		{
			if (stm->output[i].macconnect->type==MAC_LONGINT||stm->output[i].macconnect->type==MAC_SHORTINT||stm->output[i].macconnect->type==MAC_SHORTUINT)
				sprintf(s,"Output %s %d", stm->output[i].name, stm->output[i].macconnect->data);
			else
				sprintf(s,"Output %s %0.4f", stm->output[i].name, stm->output[i].macconnect->fdata);
		}
		else if (stm->output[i].iotype==OUTICPCON)
			sprintf(s,"Output %s %s", stm->output[i].name, *stm->output[i].icpconnect->udata & (1<<stm->output[i].icpconnect->bitpos) ? "ON" : "OFF" );
		BxList_SetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), sn++, s);
	}
	for(i=0;i<stm->numtimeout;i++)
	{
		sprintf(s, "Timeout %s %d", stm->timeout[i].name, stm->timeout[i].timeout);
		BxList_SetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), sn++, s);
	}
	for(i=0;i<stm->numvalue;i++)
	{
    if(formSTMCtrl_BuildValueString(&stm->value[i], s))
      BxList_SetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), sn++, s);
    else{
      char str[512];
      sprintf(str,"Error: %s is unknown",stm->value[i].name);
      BxList_SetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), sn++, str);
    }
	}
	for(i=0;i<stm->numlink;i++)
	{
		char *linkstate=NULL;
		if (stm->link[i].stmidx==-1)
		{
			int remidx;
			remidx = getRemoteStatemachineIdx((tmpnWorkcell *)tworkcell,stm->link[i].name);
			if (remidx>=0)
			{
				linkstate = (char *)tworkcell->remotestatemachines.remotestatemachine[remidx].state;
			}
		}
		else
		{
			link=&tworkcell->statemachines.statemachine[stm->link[i].stmidx];
			link=&tworkcell->statemachines.statemachine[stm->link[i].stmidx];
			linkstate = link->state[link->istate].name;
		}
		if(strcmp(stm->link[i].localname, stm->link[i].name)==0)
			sprintf(s, "Link %s %s", stm->link[i].localname, linkstate);
		else
			sprintf(s, "Link %s(%s) %s", stm->link[i].localname, stm->link[i].name, linkstate);
		BxList_SetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), sn++, s);
	}
	BxList_Update(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX));
  return TRUE;
}

void setState(int machine, int state);
int stmStop(void);
int stmStart(void);
void SetupSTMLink(void);

BX_BOOL formSTMCtrl_cmdHalt_Click(HBOX hBox)
{
  int stateidx;
  tmpnStateMachine *stm;
  
	stm=&tworkcell->statemachines.statemachine[stateMachineNum];
	
	if(!strcmp(stm->state[stm->istate].name,"ST_HALT"))
  {
    stateidx=getStateIdx(stateMachineNum,"ST_IDLE");
    if (stateidx>=0)
      setState(stateMachineNum, stateidx);
    
    BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDHALT), "Halt");
  }
  else
  {
    stateidx=getStateIdx(stateMachineNum,"ST_HALT");
    if (stateidx>=0)
      setState(stateMachineNum, stateidx);
    
    BxSetStringValue(BxGetDlgItem(hBox, FORMSTMCTRL_CMDHALT), "Idle");
  }
  return TRUE;
}

BX_BOOL formSTMCtrl_cmdRestart_Click(HBOX hBox)
{
	int stateidx;
	stateidx=getStateIdx(stateMachineNum,"ST_RESET");
	if (stateidx>=0)
		setState(stateMachineNum, stateidx);
  return TRUE;
}

BX_BOOL formSTMCtrl_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formSTMCtrl_listBox_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSTMCtrl_cmdEdit_Click(HBOX hBox)
{
  int i;
  tmpnStateMachine *stm;
  BX_PSTRING str;
  BX_PSTRING tname[256];
  BX_INT valnum=0;
  BX_INT outval=0;
	BX_FLOAT foutval=0.0;
    
  valnum = BxList_GetSelected(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX));
  if (valnum<0) return TRUE;

  stm=&tworkcell->statemachines.statemachine[stateMachineNum];

  str = BxList_GetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), valnum);
  if (!strncmp(str,"Timeout",7))
  {
    sscanf(str, "Timeout %s %d",(char*)tname,&outval);
    for(i=0;i<stm->numtimeout;i++)
    {
      if (!strncmp(stm->timeout[i].name,(char*)tname,256))
      {
        BxVirtNumBox_SetValue(outval);
        if(VirtNumKeyBox( hBox ) == IDOK)
        {
          stm->timeout[i].timeout = BxVirtNumBox_GetValue();
          if (!SaveTimeVal(stm->name,(char*)tname,stm->timeout[i].timeout))
          {
            if(rs_param.statemachine_debug>0)
              printf("New timeout-val could not be saved.\n");
            stm->timeout[i].timeout = outval;  //revert
          }  
        }
      }
    }
  }
  else if (!strncmp(str,"Const",5))
  {
    sscanf(str,"Const %s",(char*)tname);
    for(i=0;i<stm->numvalue;i++)
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256))
      {
				if(stm->value[i].subtype==0)
				{
					sscanf(str, "Const %s %d",(char*)tname,&outval);
					BxVirtNumBox_SetValue(outval);
					if(VirtNumKeyBox( hBox ) == IDOK)
					{
						stm->value[i].data = BxVirtNumBox_GetValue();
						if (!SaveConstVal(stm->name,(char*)tname,&stm->value[i]))
						{
							if(rs_param.statemachine_debug>0)
								printf("New Const-val could not be saved.\n");
							stm->value[i].data = outval;  //revert
						}  
					}
				}
				else
				{
					sscanf(str, "Const %s %f",(char*)tname,&foutval);
					BxVirtNumBox_SetFloatValue(foutval);
					if(VirtNumKeyBox( hBox ) == IDOK)
					{
						stm->value[i].fdata = BxVirtNumBox_GetFloatValue();
						if (!SaveConstVal(stm->name,(char*)tname,&stm->value[i]))
						{
							if(rs_param.statemachine_debug>0)
								printf("New Const-val could not be saved.\n");
							stm->value[i].fdata = foutval;  //revert
						}  
					}
				}
			}
		}
	}
  else if (!strncmp(str,"Frame",5))
  {
		HBOX hBx;
		tmpnFrame *fr;
		sscanf(str,"Frame %s",(char*)tname);
    for(i=0;i<stm->numvalue;i++)
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256)&&stm->value[i].type==FRAME)
      {
				fr=stm->value[i].frame;
				if (fr!=NULL)
				{
					fixpointsFrameName=(char*)tname;
					hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditFrame[0], formEditFrameProc);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX), fr->x);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY), fr->y);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ), fr->z);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV), fr->v);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW), fr->w);
					if(DoModal(hBx)==IDOK)
					{
						fr->x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX));
						fr->y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY));
						fr->z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ));
						fr->v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV));
						fr->w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW));
						SaveFrameVal(stm->name,fr);
					}
				}
			}
		}
	} 
   else if (!strncmp(str,"Item",4))
  {
		HBOX hBx;
    tmpnItem *item;
    sscanf(str,"Item %s",(char*)tname);
    tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
    for(i=0;i<stm->numvalue;i++) //there are for types of variables - item is of type value
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256)&&stm->value[i].type==ITEM)
      {
        item=stm->value[i].item;
				if (item!=NULL)
				{
          itemName=(char*)tname;
          hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formItemEdit[0], formItemEditProc);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDDX), item->dim.x);
				  BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDDY), item->dim.y);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDDZ), item->dim.z);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDSY), item->sy);
					BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDGY), item->gy);
          BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDMY), item->my);
          BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDGX), item->gx);
          BxSetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDWEIGHT), item->weight);
					if(DoModal(hBx)==IDOK)
					{
            item->dim.x = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDDX));
					  item->dim.y = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDDY));
				  	item->dim.z = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDDZ));
				   	item->sy = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDSY));
				  	item->gy = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDGY));
            item->my = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDMY));
            item->gx = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDGX));
            item->weight = BxGetFloatValue(BxGetDlgItem(hBx, FORMITEMEDIT_CMDWEIGHT));
						//SaveItemVal(stm->name,item, item);//saving to file but what about program STM?
          }
				}
			}
		}
    }
  else if (!strncmp(str,"CPPattern",9))
  {
		HBOX hBx;
    //		tmpnCPPattern *cppattern;
    char buf[256];
		sscanf(str,"CPPattern %s %s",(char*)tname, buf);
    for(i=0;i<stm->numvalue;i++)
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256)&&stm->value[i].type==CPPATTERN)
      {
        //printf("name of the game: %s\n",(char*)tname);

				if ((editcppattern=stm->value[i].cppattern) != NULL)
				{
					//fixpointsFrameName=(char*)tname;
					hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditCPPattern[0], formEditCPPatternProc);
					//BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX), fr->x);
          //...
					if(DoModal(hBx)==IDOK)
					{
          /*
						fr->x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX));
						fr->y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY));
						fr->z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ));
						fr->v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV));
						fr->w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW));
						SaveFrameVal(stm->name,fr);
          */
					}
				}
			}
		}
	}
/*  else if (!strncmp(str,"Table",5))
  {
    sscanf(str, "Table %s %d",(char*)tname,&outval);
    for(i=0;i<stm->numvalue;i++)
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256))
      {
        BxVirtNumBox_SetValue(outval);
        if(VirtNumKeyBox( hBox ) == IDOK)
        {
          stm->value[i].table->newtablesize = BxVirtNumBox_GetValue();
          if (!SaveTableVal(stm->name,(char*)tname,stm->value[i].table->newtablesize))
          {
            if(rs_param.statemachine_debug>0)
              printf("New Table-size could not be saved.\n");
            stm->value[i].data = outval;  //revert
          }  
        }
      }
    }
  }*/
  else if (!strncmp(str,"Value",5))
  {
    sscanf(str, "Value %s",(char*)tname);
    for(i=0;i<stm->numvalue;i++)
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256))
      {
				if(stm->value[i].subtype==0)
				{
					sscanf(str, "Value %s %d",(char*)tname,&outval);
					BxVirtNumBox_SetValue(outval);
					if(VirtNumKeyBox( hBox ) == IDOK)
					{
						stm->value[i].data = BxVirtNumBox_GetValue();
					}
				}
				else
				{
					sscanf(str, "Value %s %f",(char*)tname,&foutval);
					BxVirtNumBox_SetFloatValue(foutval);
					if(VirtNumKeyBox( hBox ) == IDOK)
					{
						stm->value[i].fdata = BxVirtNumBox_GetFloatValue();
					}	
				}
			}
		}
	}
  else if (!strncmp(str,"Input",5))
  {
    sscanf(str, "Input %s",(char*)tname);
    for(i=0;i<stm->numinput;i++)
    {
      if (!strncmp(stm->input[i].name,(char*)tname,256))
      {
				if (stm->input[i].iotype==INPUT)
				{
					if(stm->input[i].connect->connectType==IBITDATA||stm->input[i].connect->connectType==LEGACYDATA)
						if(connectSimulated(stm->input[i].connect)==1)
							setConnectValueInt(stm->input[i].connect, !getConnectValueInt(stm->input[i].connect));
				}
		  }	
		}
	}
  else if (!strncmp(str,"Output",6))
  {
    sscanf(str, "Output %s",(char*)tname);
    for(i=0;i<stm->numoutput;i++)
    {
      if (!strncmp(stm->output[i].name,(char*)tname,256))
      {
				if (stm->output[i].iotype==OUTPUT)
				{	
					if(stm->output[i].connect->connectType==OBITDATA||stm->output[i].connect->connectType==LEGACYDATA)
						setConnectValueInt(stm->output[i].connect, !getConnectValueInt(stm->output[i].connect));
          else if(stm->output[i].connect->connectType==OSHORTDATA)
  				{
					  sscanf(str, "Output %s %d",(char*)tname,&outval);
					  BxVirtNumBox_SetValue(outval);
					  if(VirtNumKeyBox( hBox ) == IDOK)
					  {
              *stm->output[i].connect->sdata = BxVirtNumBox_GetValue();
				  	}
          }
        }
		    else if (stm->output[i].iotype==OUTCOMSK)
        {
				  sscanf(str, "Output %s %f",(char*)tname,&foutval);
				  BxVirtNumBox_SetFloatValue(foutval);
				  if(VirtNumKeyBox( hBox ) == IDOK)
					{
						stm->output[i].comskconnect->fdata = BxVirtNumBox_GetFloatValue();
					}	
				}
				else if (stm->output[i].iotype==OUTMAC)
        {
					if (stm->output[i].macconnect->type==MAC_LONGINT||stm->output[i].macconnect->type==MAC_SHORTINT||stm->output[i].macconnect->type==MAC_SHORTUINT)
					{
						sscanf(str, "Output %s %d",(char*)tname,&outval);
						BxVirtNumBox_SetValue(outval);
						if(VirtNumKeyBox( hBox ) == IDOK)
						{
							stm->output[i].macconnect->data = BxVirtNumBox_GetValue();
							stm->output[i].macconnect->userchange=1;
						}
					}
					else
					{
						sscanf(str, "Output %s %f",(char*)tname,&foutval);
						BxVirtNumBox_SetFloatValue(foutval);
						if(VirtNumKeyBox( hBox ) == IDOK)
						{
							stm->output[i].macconnect->fdata = BxVirtNumBox_GetFloatValue();
							stm->output[i].macconnect->userchange=1;
						}
					}	
				}
				else if (stm->output[i].iotype==OUTICPCON)
        {
					BxVirtNumBox_SetValue(1&(*stm->output[i].icpconnect->udata>>stm->output[i].icpconnect->bitpos));
					BxVirtNumBox_SetLimits(0, 1);
					if(VirtNumKeyBox( hBox ) == IDOK)
					{
						*stm->output[i].icpconnect->udata&=~(1<<stm->output[i].icpconnect->bitpos);
						*stm->output[i].icpconnect->udata|=BxVirtNumBox_GetValue()<<stm->output[i].icpconnect->bitpos;
					}
				}
			}
		}
	}
  else if (!strncmp(str,"linkValue",9))
  {
    char buf[256];
    sscanf(str, "linkValue %s %s",(char*)tname, buf);
    for(i=0;i<stm->numvalue;i++)
    {
      if (!strncmp(stm->value[i].name,(char*)tname,256))
      {
        if (!strncmp(buf,"Value",5)) //edit only if linkValue is a Value
        {
          if(stm->value[i].subtype==0)
          {
            sscanf(str, "Value %s %d",(char*)tname,&outval);
            BxVirtNumBox_SetValue(outval);
            if(VirtNumKeyBox( hBox ) == IDOK)
            {
              setArgValueInt(&stm->value[i],"",BxVirtNumBox_GetValue());
            }
          }
          else
          {
            sscanf(str, "Value %s %f",(char*)tname,&foutval);
            BxVirtNumBox_SetFloatValue(foutval);
            if(VirtNumKeyBox( hBox ) == IDOK)
            {
              setArgValueFloat(&stm->value[i],"",BxVirtNumBox_GetFloatValue());
            }	
          }
        }
			}
		}
	}
	return TRUE;
}

BX_BOOL formSTMCtrl_cmdScope_Click(HBOX hBox)
{
  tmpnStateMachine *stm;
  BX_PSTRING str;
  char tname[256];
  BX_INT valnum=0;
	HBOX hBx;
    
  valnum = BxList_GetSelected(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX));
  if (valnum<0) return TRUE;

  stm=&tworkcell->statemachines.statemachine[stateMachineNum];

  str = BxList_GetString(BxGetDlgItem(hBox, FORMSTMCTRL_LISTBOX), valnum);
  
  if (!strncmp(str,"Timeout",7))
  {
    sscanf(str, "Timeout %s",(char*)tname);
  } 
  else if (!strncmp(str,"Const",5))
  {
    sscanf(str, "Const %s",(char*)tname);
  }
  else if (!strncmp(str,"Value",5))
  {
    sscanf(str, "Value %s",(char*)tname);
  }
	else if (!strncmp(str,"Table",5))
  {
    sscanf(str, "Table %s",(char*)tname);
  }
	else if (!strncmp(str,"Path",4))
  {
    sscanf(str, "Path %s",(char*)tname);
  }
	else if (!strncmp(str,"Frame",5))
  {
    sscanf(str, "Frame %s",(char*)tname);
  }
  else
    return TRUE;
  //TODO more than one scopeitem
  scopeitem[0].sampling = getMachineValue(stateMachineNum,&tname[0]);
  
	if (scopeitem[0].sampling!=NULL)
	{
		hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formScopeData[0], formScopeDataProc);
		DoModal(hBx);
  }
  return TRUE;
}
void formSTMCtrl_SetStateMachine(int stmNum)
{
  stateMachineNum = stmNum;
}

