//Code generated by bxbuilder (c) LMS 2002 
// formHomeUser.c
#include "Bx.h"
#include "formHome.h"
#include "rs.h"
#include "tmpnrobot.h"

BX_BOOL formHomeUserInit(HBOX hBox,BX_LPARAM lParam)
{
 return TRUE;
}

BX_BOOL formHomeUserUpdate(HBOX hBox)
{
 return TRUE;
}

extern int supervisorLogin(HBOX hBox);

BX_BOOL formHome_cmdLogin_Click(HBOX hBox)
{

  if(supervisorLogin(hBox)>MANAGERLEVEL)
  {
    BxEndDialog(hBox, IDOK);
    return TRUE;
  }
  return TRUE;
}

