//Code generated by bxbuilder (c) LMS 2002 
// formPathViewUser.c
#include "Bx.h"
#include "formPathView.h"

#include "tmclnx.h"
#include "rs.h"
#include "tmpnrobot.h"

static BXMENUSTRUCT pBxMenu;
static BX_INT pathIndex = -1;

static void PaintPath(HBOX hBox)
{
/*
  BOXSTRUCT *m_Bar = (BOXSTRUCT *)BxGetDlgItem(hBox, FORMPATHVIEW_LABVIEW);
  BxDC* pDC;
  BX_RECT hlRc, kfRc = {0, 0, 10, 10};
  BX_INT i;
  float xScale, yScale, zScale;
    
  SetRect(&hlRc, m_Bar->rc.left+1, m_Bar->rc.top+1, m_Bar->rc.right-1, m_Bar->rc.bottom-1);
  pDC = GetBoxDC(BxGetDlgItem(hBox, FORMPATHVIEW_LABVIEW));
  SetPen(pDC, 0xFFFFFF);
  SetBrush(pDC, 0x000000);
  BxRectangle(pDC, &hlRc);
  SetRect(&hlRc, m_Bar->rc.left+20, m_Bar->rc.top+20, m_Bar->rc.right-20, m_Bar->rc.bottom-20);

//  generatePath(&trobot, &tpathdef, &tpath);

  if(BxGetCheck(BxGetDlgItem(hBox, FORMPATHVIEW_RADIOXY)))
  {
    xScale = trobot.m_max.x / RectWidth(&hlRc);
    yScale = trobot.m_max.y / RectHeight(&hlRc);

    for(i=0;i<tpath.maxidx-1;i++)
    {
      BxLine(pDC,
        hlRc.left + (tpath.position[i].taskSpace.x/xScale), hlRc.top + BxRectHeight(&hlRc) - (tpath.position[i].taskSpace.y/yScale),
        hlRc.left + (tpath.position[i+1].taskSpace.x/xScale), hlRc.top + BxRectHeight(&hlRc) - (tpath.position[i+1].taskSpace.y/yScale));
    }
    for(i=0;i<tpathdef.maxidx-1;i++)
    {
      BxSetRect(&kfRc,
              hlRc.left + (tpathdef.keypoint[i].x/xScale)-5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)-5,
              hlRc.left + (tpathdef.keypoint[i].x/xScale)+5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)+5);
      if(pathIndex == i)
        BxFrame(pDC, &kfRc, 0x00ff00, 0x00ff00);
      else
        BxFrame(pDC, &kfRc, 0xffff, 0xffff);
    }
    BxSetRect(&kfRc,
              hlRc.left + (tpathdef.keypoint[i].x/xScale)-5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)-5,
              hlRc.left + (tpathdef.keypoint[i].x/xScale)+5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)+5);
    if(pathIndex == i)
      BxFrame(pDC, &kfRc, 0x00ff00, 0x00ff00);
    else
      BxFrame(pDC, &kfRc, 0xffff, 0xffff);
  }

  if(BxGetCheck(BxGetDlgItem(hBox, FORMPATHVIEW_RADIOXZ)))
  {
    xScale = trobot.m_max.x / RectHeight(&hlRc);
    zScale = trobot.m_max.z / RectWidth(&hlRc);
    for(i=0;i<tpath.maxidx-1;i++)
    {
      BxLine(pDC,
        hlRc.left + (tpath.position[i].taskSpace.z/zScale), hlRc.top + BxRectHeight(&hlRc) - (tpath.position[i].taskSpace.x/xScale),
        hlRc.left + (tpath.position[i+1].taskSpace.z/zScale), hlRc.top + BxRectHeight(&hlRc) - (tpath.position[i+1].taskSpace.x/xScale));
    }
    for(i=0;i<tpathdef.maxidx-1;i++)
    {
      BxSetRect(&kfRc,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)-5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].x/xScale)-5,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)+5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].x/xScale)+5);
      if(pathIndex == i)
        BxFrame(pDC, &kfRc, 0x00ff00, 0x00ff00);
      else
        BxFrame(pDC, &kfRc, 0xffff, 0xffff);
    }
    BxSetRect(&kfRc,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)-5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].x/xScale)-5,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)+5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].x/xScale)+5);
    if(pathIndex == i)
      BxFrame(pDC, &kfRc, 0x00ff00, 0x00ff00);
    else
      BxFrame(pDC, &kfRc, 0xffff, 0xffff);
  }
  
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPATHVIEW_RADIOYZ)))
  {
    yScale = trobot.m_max.y / RectHeight(&hlRc);
    zScale = trobot.m_max.z / RectWidth(&hlRc);
    for(i=0;i<tpath.maxidx-1;i++)
    {
      BxLine(pDC,
        hlRc.left + (tpath.position[i].taskSpace.z/zScale), hlRc.top + BxRectHeight(&hlRc) - (tpath.position[i].taskSpace.y/yScale),
        hlRc.left + (tpath.position[i+1].taskSpace.z/zScale), hlRc.top + BxRectHeight(&hlRc) - (tpath.position[i+1].taskSpace.y/yScale));
    }
    for(i=0;i<tpathdef.maxidx-1;i++)
    {
      BxSetRect(&kfRc,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)-5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)-5,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)+5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)+5);
      if(pathIndex == i)
        BxFrame(pDC, &kfRc, 0x00ff00, 0x00ff00);
      else
        BxFrame(pDC, &kfRc, 0xffff, 0xffff);
    }
    BxSetRect(&kfRc,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)-5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)-5,
              hlRc.left + (tpathdef.keypoint[i].z/zScale)+5,
              hlRc.top + BxRectHeight(&hlRc) - (tpathdef.keypoint[i].y/yScale)+5);
    if(pathIndex == i)
      BxFrame(pDC, &kfRc, 0x00ff00, 0x00ff00);
    else
      BxFrame(pDC, &kfRc, 0xffff, 0xffff);
  }
  BxSetDirtyArea(&m_Bar->rc);
*/
}

BX_BOOL formPathViewUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxSetCheck(BxGetDlgItem(hBox, FORMPATHVIEW_RADIOXY), TRUE);
  pathIndex = 0;

  BxScrollBar_SetRange(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN1), 0, 100);
  BxScrollBar_SetRange(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN2), 0, 100);
//  BxScrollBar_SetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN1), tpathdef.keypoint[0].tanxyz);
//  BxScrollBar_SetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN2), tpathdef.keypoint[0].tanw);
  
  return TRUE;
}

BX_BOOL formPathViewUserUpdate(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formPathView_cmdPrev_Click(HBOX hBox)
{
  if(pathIndex > 0)
  {
    pathIndex--;
//    BxScrollBar_SetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN1), tpathdef.keypoint[pathIndex].tanxyz);
//    BxScrollBar_SetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN2), tpathdef.keypoint[pathIndex].tanw);
    PaintPath(hBox);
  }
  return TRUE;
}

BX_BOOL formPathView_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);

  return TRUE;
}

BX_BOOL formPathView_cmdMenu_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMPATHVIEW_CMDMENU), &pBxMenu);
  BxMenu_Add(hBx ,"Return", MENU, formPathView_cmdCancel_Click, TRUE, NULL);
  DoMenu(BxGetDlgItem(hBox, FORMPATHVIEW_CMDMENU));
  return TRUE;
}

BX_BOOL formPathView_scrollTan1_Click(HBOX hBox)
{
//  tpathdef.keypoint[pathIndex].tanxyz = BxScrollBar_GetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN1));
  PaintPath(hBox);
  return TRUE;
}

BX_BOOL formPathView_scrollTan2_Click(HBOX hBox)
{
//  tpathdef.keypoint[pathIndex].tanw = BxScrollBar_GetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN2));
  PaintPath(hBox);
  return TRUE;
}

BX_BOOL formPathView_radioXY_Click(HBOX hBox)
{
  PaintPath(hBox);
  return TRUE;
}

BX_BOOL formPathView_radioXZ_Click(HBOX hBox)
{
  PaintPath(hBox);
  return TRUE;
}

BX_BOOL formPathView_radioYZ_Click(HBOX hBox)
{
  PaintPath(hBox);
  return TRUE;
}

BX_BOOL formPathView_cmdNext_Click(HBOX hBox)
{
/*
  if(pathIndex < tpathdef.maxidx-1)
  {
    pathIndex++;
    BxScrollBar_SetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN1), tpathdef.keypoint[pathIndex].tanxyz);
    BxScrollBar_SetPos(BxGetDlgItem(hBox, FORMPATHVIEW_SCROLLTAN2), tpathdef.keypoint[pathIndex].tanw);
    PaintPath(hBox);
  }
*/
  return TRUE;
}

