//Code generated by bxbuilder (c) LMS 2002
// formEditBoxPatternUser.c
#include "Bx.h"
#include "formEditBoxPattern.h"

#include <math.h>
#include "cmd.h"

static int patternindex = 0;
static int itemindex = 0;
static int pindex = 0;
static tmpnPattern *pattern=NULL;
static tmpnItem *item=NULL;

static void drawTab(HBOX hBox)
{
	BX_RECT tRc;
  BX_COLORREF oldPen;
  BX_COLORREF oldBrush;
  BOXSTRUCT *b;
  int WINDOWOFFSETX,WINDOWOFFSETY,WINDOWHEIGHT;
  float wx0,wx1,wx2,wx3,wy0,wy1,wy2,wy3,dx,dy,xscale,yscale;

  b = BxGetDlgItem(hBox,FORMEDITBOXPATTERN_LABVIEW);
  BxDC* bdc = BxGetBoxDC(BxGetDlgItem(hBox,FORMEDITBOXPATTERN_LABVIEW));
	oldPen = BxSetPen(bdc, BXSYSTEM_PALETTE[BXCOLOR_BACKGROUND]);
	oldBrush = BxSetBrush(bdc, BXSYSTEM_PALETTE[BXCOLOR_BACKGROUND]);
	BxSetRect(&tRc, b->rc.left+1, b->rc.top+1, b->rc.right-1, b->rc.bottom-1);
	WINDOWOFFSETX=b->rc.left;
	WINDOWOFFSETY=b->rc.bottom;
	WINDOWHEIGHT=b->rc.bottom-b->rc.top;
	BxRectangle(bdc, &tRc);
	BxSetPen(bdc, oldPen);
	BxSetBrush(bdc, oldBrush);
  
  dx = item->dim.z*0.5;
  dy = item->dim.x*0.5;
  xscale = (b->rc.right-b->rc.left)/pattern->width;
  yscale = (b->rc.bottom-b->rc.top)/pattern->length;
  wx0=(-dx)*cos(DEGTORAD(pattern->item[pindex].wcp.w))-(-dy)*sin(DEGTORAD(pattern->item[pindex].wcp.w));
  wy0=(-dx)*sin(DEGTORAD(pattern->item[pindex].wcp.w))+(-dy)*cos(DEGTORAD(pattern->item[pindex].wcp.w));
  wx1=( dx)*cos(DEGTORAD(pattern->item[pindex].wcp.w))-(-dy)*sin(DEGTORAD(pattern->item[pindex].wcp.w));
  wy1=( dx)*sin(DEGTORAD(pattern->item[pindex].wcp.w))+(-dy)*cos(DEGTORAD(pattern->item[pindex].wcp.w));
  wx2=(-dx)*cos(DEGTORAD(pattern->item[pindex].wcp.w))-( dy)*sin(DEGTORAD(pattern->item[pindex].wcp.w));
  wy2=(-dx)*sin(DEGTORAD(pattern->item[pindex].wcp.w))+( dy)*cos(DEGTORAD(pattern->item[pindex].wcp.w));
  wx3=( dx)*cos(DEGTORAD(pattern->item[pindex].wcp.w))-( dy)*sin(DEGTORAD(pattern->item[pindex].wcp.w));
  wy3=( dx)*sin(DEGTORAD(pattern->item[pindex].wcp.w))+( dy)*cos(DEGTORAD(pattern->item[pindex].wcp.w));

	oldPen = BxSetPen(bdc, BXSYSTEM_PALETTE[BXCOLOR_BACKGROUND]);
	oldBrush = BxSetBrush(bdc, BXSYSTEM_PALETTE[BXCOLOR_BACKGROUND]);
/*	BxSetRect(&tRc, b->rc.left+pattern->item[pindex].wcp.z*xscale+wx0*xscale
                , b->rc.top +pattern->item[pindex].wcp.x*yscale+wy0*yscale
                , b->rc.left+pattern->item[pindex].wcp.z*xscale+wx3*xscale                         
                , b->rc.top +pattern->item[pindex].wcp.x*yscale+wy3*yscale);
	BxRectangle(bdc, &tRc);*/
	BxSetPen(bdc, oldPen);
	BxSetBrush(bdc, oldBrush);

  BxLine(bdc,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx0*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy0*yscale
            ,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx1*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy1*yscale);
  BxLine(bdc,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx1*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy1*yscale
            ,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx2*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy2*yscale);
  BxLine(bdc,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx2*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy2*yscale
            ,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx3*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy3*yscale);
  BxLine(bdc,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx3*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy3*yscale
            ,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx0*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy0*yscale);
  BxLine(bdc,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx1*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy1*yscale
            ,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx3*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy3*yscale);
  BxLine(bdc,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx0*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy0*yscale
            ,b->rc.right -pattern->item[pindex].wcp.z*xscale-wx2*xscale
            ,b->rc.top   +pattern->item[pindex].wcp.x*yscale+wy2*yscale);
}
static void updateDisplay(HBOX hBox)
{
  if(patternindex>=tworkcell->patterns.maxidx) patternindex=tworkcell->patterns.maxidx-1;
  if(patternindex<0) patternindex=0;
  pattern = (tmpnPattern*)&tworkcell->patterns.pattern[patternindex];
  if(pindex>=pattern->maxidx) pindex=pattern->maxidx-1;
  if(pindex<0) pindex=0; 
  if(itemindex>=tworkcell->items.maxidx) itemindex=tworkcell->items.maxidx-1;
  if(itemindex<0) itemindex=0;
  item = (tmpnItem*)&tworkcell->items.item[itemindex];

  BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_LABPATTERN), pattern->name);
  BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_LABITEM), item->name);
  
  BxSetIntValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDLAYER), pattern->item[pindex].layer);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDX), pattern->item[pindex].wcp.x);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDY), pattern->item[pindex].wcp.y);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDZ), pattern->item[pindex].wcp.z);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDV), pattern->item[pindex].wcp.v);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDW), pattern->item[pindex].wcp.w);
  BxSetIntValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDINDEX), pindex);
  drawTab(hBox);
}

BX_BOOL formEditBoxPatternUserInit(HBOX hBox,BX_LPARAM lParam)
{
  patternindex = 0;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
  BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXPATTERN));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXPATTERN), getLanguageLineFromIdx(langptr, 262, "Pattern"));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDCANCEL), getLanguageLineFromIdx(langptr, 54, "Close"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXPOSITION));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXPOSITION), getLanguageLineFromIdx(langptr, 258, "Position"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_TEXTLABEL_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_TEXTLABEL_2), getLanguageLineFromIdx(langptr, 259, "Layer"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXITEM));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXITEM), getLanguageLineFromIdx(langptr, 260, "Item"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXINDEX));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_GROUPBOXINDEX), getLanguageLineFromIdx(langptr, 89, "Index"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDSAVE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDSAVE), getLanguageLineFromIdx(langptr, 261, "Save"));

  BxAssignIntValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDLAYER));

	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_LABPATTERN));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_LABITEM));

	BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDX));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDY));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDZ));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDV));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDW));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDINDEX));
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPatternUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formEditBoxPattern_cmdSave_Click(HBOX hBox)
{
  tmpnPatternSave(pattern);
 return TRUE;
}

BX_BOOL formEditBoxPattern_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, FALSE);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdW_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDW)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    pattern->item[pindex].wcp.w = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDW), pattern->item[pindex].wcp.w);
  }
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdY_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDY)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    pattern->item[pindex].wcp.y = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDY), pattern->item[pindex].wcp.y);
  }
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdX_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDX)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    pattern->item[pindex].wcp.x = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDX), pattern->item[pindex].wcp.x);
  }
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdZ_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDZ)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    pattern->item[pindex].wcp.z = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDZ), pattern->item[pindex].wcp.z);
  }
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdV_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDV)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    pattern->item[pindex].wcp.v = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDV), pattern->item[pindex].wcp.v);
  }
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdIndex_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMEDITBOXPATTERN_CMDINDEX)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  { 
    pindex = BxVirtNumBox_GetValue();
  }
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdLayer_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdPatternPrev_Click(HBOX hBox)
{
  patternindex--;
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdPatternNext_Click(HBOX hBox)
{
  patternindex++;
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdItemPrev_Click(HBOX hBox)
{
  itemindex--;
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdItemNext_Click(HBOX hBox)
{
  itemindex++;
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdIndexPrev_Click(HBOX hBox)
{
  pindex--;
  updateDisplay(hBox);
  return TRUE;
}

BX_BOOL formEditBoxPattern_cmdIndexNext_Click(HBOX hBox)
{
  pindex++;
  updateDisplay(hBox);
  return TRUE;
}

