//Code generated by bxbuilder (c) LMS 2002 
// formJogAxisUser.c
#include "Bx.h"
#include "formJogAxis.h"

#include "rs.h"
#include "cmd.h"
#include "tmpnrobot.h"

extern int GetAxisValues(int axis, int tabel, AXIS_PARAMETER *ap);
float SpeedBU[7];
float AccelBU[7];
float DecelBU[7];
float FastStep[7] = {10.0,10.0,10.0,10.0,10.0,10.0,10.0};
float SlowStep[7] = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0,1.0};
float JogSpeed[7] = {10.0, 10.0, 1.0, 1.0, 1.0, 1.0,10.0};


static BX_BOOL MoveAndWait(int axis, float pos)
{
  float val;

  val = GetEndMove(axis);

  if (MoveModify(axis, val+pos))
    return FALSE;

  return TRUE;
}

static BX_BOOL MoveAbsAndWait(int axis, float pos)
{
  if (MoveAbs(axis, pos))
    return FALSE;
  return TRUE;
}

static int GetActiveAxis(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_RADIOA)))
    return axis_a;
  if(BxGetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_RADIOB)))
    return axis_b;
  if(BxGetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_RADIOC)))
    return axis_c;
  if(BxGetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_RADIOD)))
    return axis_d;
  if(BxGetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_RADIOE)))
    return axis_e;
  return axis_f;
}

static void EnableAxis(HBOX hBox, int axis)
{
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDSLOWSTEP), SlowStep[axis]);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFASTSTEP), FastStep[axis]);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDJOGSPEED), JogSpeed[axis]);

  if(rs_param.workcellid==319
   ||rs_param.workcellid==320
   ||rs_param.workcellid==321)
  {
    SetSpeed(axis, JogSpeed[axis]);
    SetAccel(axis, JogSpeed[axis]*0.5);
    SetDecel(axis, JogSpeed[axis]*0.5);
  }
   else
  {
    SetSpeed(axis, JogSpeed[axis]);
    SetAccel(axis, JogSpeed[axis]*2);
    SetDecel(axis, JogSpeed[axis]*2);
	}

  if(axis==axis_a)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGFWDFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGREVFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGFWDSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGREVSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGFWDFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGREVFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGFWDSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDAJOGREVSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS), FALSE);
  }
  if(axis==axis_b)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGFWDFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGREVFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGFWDSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGREVSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGFWDFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGREVFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGFWDSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDBJOGREVSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS), FALSE);
  }
  if(axis==axis_c)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGFWDFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGREVFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGFWDSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGREVSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGFWDFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGREVFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGFWDSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCJOGREVSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS), FALSE);
  }
  if(axis==axis_d)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGFWDFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGREVFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGFWDSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGREVSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGFWDFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGREVFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGFWDSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDDJOGREVSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS), FALSE);
  }
  if(axis==axis_e)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGFWDFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGREVFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGFWDSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGREVSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGFWDFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGREVFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGFWDSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDEJOGREVSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS), FALSE);
  }
  if(axis==axis_f)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGFWDFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGREVFAST), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGFWDSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGREVSLOW), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGFWDFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGREVFAST), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGFWDSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFJOGREVSLOW), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS), FALSE);
  }
}

BX_BOOL formJogAxisUserInit(HBOX hBox,BX_LPARAM lParam)
{
  int i;
  float val;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDRETURN));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDRETURN), getLanguageLineFromIdx(langptr, 74, "Ok"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDCANCEL), getLanguageLineFromIdx(langptr, 3, "Cancel"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXTLABEL2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXTLABEL2_2_2), getLanguageLineFromIdx(langptr, 15, "Speed"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXTLABEL2_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXTLABEL2_2_2_2), getLanguageLineFromIdx(langptr, 8, "Small"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXTLABEL2_2_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXTLABEL2_2_2_2_2), getLanguageLineFromIdx(langptr, 9, "Big"));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS));

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDSLOWSTEP));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFASTSTEP));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDJOGSPEED));

  for(i=1;i<7;i++)
  {
    SpeedBU[i] = GetAktuelSpeed(i);
    AccelBU[i] = GetAktuelAccel(i);
    DecelBU[i] = GetAktuelDecel(i);
  }
  
  val = GetMPos(axis_a);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS), val);

  val = GetMPos(axis_b);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS), val);

  val = GetMPos(axis_c);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS), val);

  val = GetMPos(axis_d);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS), val);

  val = GetMPos(axis_e);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS), val);

  val = GetMPos(axis_f);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS), val);

  EnableAxis(hBox, axis_a);

  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDSLOWSTEP), SlowStep[GetActiveAxis(hBox)]);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFASTSTEP), FastStep[GetActiveAxis(hBox)]);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDJOGSPEED), JogSpeed[GetActiveAxis(hBox)]);
  
  return TRUE;
}

BX_BOOL formJogAxisUserUpdate(HBOX hBox)
{
  float val;
  unsigned val2;

  val2 = (unsigned)GetInput();
  BxSetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_CHECK_B), val2 & 0x00000020 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMJOGAXIS_CHECK_C), val2 & 0x00000040 ? TRUE : FALSE);

  val = GetMPos(axis_a);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS), val);

  val = GetMPos(axis_b);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS), val);

  val = GetMPos(axis_c);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS), val);

  val = GetMPos(axis_d);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS), val);

  val = GetMPos(axis_e);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS), val);

  val = GetMPos(axis_f);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS), val);

  return TRUE;
}

BX_BOOL formJogAxis_cmdReturn_Click(HBOX hBox)
{
  int i;

  BxEndDialog(hBox, IDOK);

  for(i=1;i<7;i++)
  {
    SetSpeed(i, SpeedBU[i]);
    SetAccel(i, AccelBU[i]);
    SetDecel(i, DecelBU[i]);
  }
  return TRUE;
}

BX_BOOL formJogAxis_cmdCancel_Click(HBOX hBox)
{
  int i;

  BxEndDialog(hBox, IDCANCEL);

  for(i=1;i<7;i++)
  {
    SetSpeed(i, SpeedBU[i]);
    SetAccel(i, AccelBU[i]);
    SetDecel(i, DecelBU[i]);
  }
  return TRUE;
}

BX_BOOL formJogAxis_cmdAJogFwdSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_a, SlowStep[axis_a]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdAJogFwdFast_Click(HBOX hBox)
{
  MoveAndWait(axis_a, FastStep[axis_a]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdAJogRevSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_a, -SlowStep[axis_a]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdAJogRevFast_Click(HBOX hBox)
{
  MoveAndWait(axis_a, -FastStep[axis_a]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdBJogFwdSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_b, SlowStep[axis_b]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdBJogFwdFast_Click(HBOX hBox)
{
  MoveAndWait(axis_b, FastStep[axis_b]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdBJogRevSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_b, -SlowStep[axis_b]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdBJogRevFast_Click(HBOX hBox)
{
  MoveAndWait(axis_b, -FastStep[axis_b]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdCJogFwdSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_c, -SlowStep[axis_c]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdCJogFwdFast_Click(HBOX hBox)
{
  MoveAndWait(axis_c, -FastStep[axis_c]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdCJogRevSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_c, SlowStep[axis_c]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdCJogRevFast_Click(HBOX hBox)
{
  MoveAndWait(axis_c, FastStep[axis_c]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdDJogFwdSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_d, SlowStep[axis_d]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdDJogFwdFast_Click(HBOX hBox)
{
  MoveAndWait(axis_d, FastStep[axis_d]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdDJogRevSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_d, -SlowStep[axis_d]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdDJogRevFast_Click(HBOX hBox)
{
  MoveAndWait(axis_d, -FastStep[axis_d]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdEJogFwdSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_e, SlowStep[axis_e]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdEJogFwdFast_Click(HBOX hBox)
{
  MoveAndWait(axis_e, FastStep[axis_e]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdEJogRevSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_e, -SlowStep[axis_e]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdEJogRevFast_Click(HBOX hBox)
{
  MoveAndWait(axis_e, -FastStep[axis_e]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdFJogFwdSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_f, SlowStep[axis_f]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdFJogFwdFast_Click(HBOX hBox)
{
  MoveAndWait(axis_f, FastStep[axis_f]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdFJogRevSlow_Click(HBOX hBox)
{
  MoveAndWait(axis_f, -SlowStep[axis_f]);
  return TRUE;
}

BX_BOOL formJogAxis_cmdFJogRevFast_Click(HBOX hBox)
{
  MoveAndWait(axis_f, -FastStep[axis_f]);
  return TRUE;
}

BX_BOOL formJogAxis_check_B_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formJogAxis_check_C_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formJogAxis_cmdFastStep_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(FastStep[GetActiveAxis(hBox)]);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    FastStep[GetActiveAxis(hBox)] = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDFASTSTEP), FastStep[GetActiveAxis(hBox)]);
  }
  return TRUE;
}

BX_BOOL formJogAxis_cmdSlowStep_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(SlowStep[GetActiveAxis(hBox)]);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    SlowStep[GetActiveAxis(hBox)] = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDSLOWSTEP), SlowStep[GetActiveAxis(hBox)]);
  }
  return TRUE;
}

BX_BOOL formJogAxis_cmdJogSpeed_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(JogSpeed[GetActiveAxis(hBox)]);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    JogSpeed[GetActiveAxis(hBox)] = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_CMDJOGSPEED), JogSpeed[GetActiveAxis(hBox)]);


    if(rs_param.workcellid==319
     ||rs_param.workcellid==320
     ||rs_param.workcellid==321)
    {
      SetSpeed(GetActiveAxis(hBox), JogSpeed[GetActiveAxis(hBox)]);
      SetAccel(GetActiveAxis(hBox), JogSpeed[GetActiveAxis(hBox)]*0.5);
      SetDecel(GetActiveAxis(hBox), JogSpeed[GetActiveAxis(hBox)]*0.5);
    }
    else
    {
      SetSpeed(GetActiveAxis(hBox), JogSpeed[GetActiveAxis(hBox)]);
      SetAccel(GetActiveAxis(hBox), JogSpeed[GetActiveAxis(hBox)]*2);
      SetDecel(GetActiveAxis(hBox), JogSpeed[GetActiveAxis(hBox)]*2);
    }
    

  }

  return TRUE;
}

BX_BOOL formJogAxis_radioA_Click(HBOX hBox)
{
  EnableAxis(hBox, axis_a);
  return TRUE;
}

BX_BOOL formJogAxis_radioB_Click(HBOX hBox)
{
  EnableAxis(hBox, axis_b);
  return TRUE;
}

BX_BOOL formJogAxis_radioC_Click(HBOX hBox)
{
  EnableAxis(hBox, axis_c);
  return TRUE;
}

BX_BOOL formJogAxis_radioD_Click(HBOX hBox)
{
  EnableAxis(hBox, axis_d);
  return TRUE;
}

BX_BOOL formJogAxis_radioE_Click(HBOX hBox)
{
  EnableAxis(hBox, axis_e);
  return TRUE;
}

BX_BOOL formJogAxis_radioF_Click(HBOX hBox)
{
  EnableAxis(hBox, axis_f);
  return TRUE;
}

BX_BOOL formJogAxis_TexAMPOS_Click(HBOX hBox)
{
  float vpos;
  
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vpos = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXAMPOS), vpos);
    MoveAbsAndWait(axis_a, vpos);
  }

  return TRUE;
}

BX_BOOL formJogAxis_TexBMPOS_Click(HBOX hBox)
{
  float vpos;

  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vpos = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXBMPOS), vpos);
    MoveAbsAndWait(axis_b, vpos);
  }

  return TRUE;
}

BX_BOOL formJogAxis_TexCMPOS_Click(HBOX hBox)
{
  float vpos;

  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vpos = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXCMPOS), vpos);
    MoveAbsAndWait(axis_c, vpos);
  }

  return TRUE;
}

BX_BOOL formJogAxis_TexDMPOS_Click(HBOX hBox)
{
  float vpos;

  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vpos = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXDMPOS), vpos);
    MoveAbsAndWait(axis_d, vpos);
  }

  return TRUE;
}

BX_BOOL formJogAxis_TexEMPOS_Click(HBOX hBox)
{
  float vpos;

  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vpos = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXEMPOS), vpos);
    MoveAbsAndWait(axis_e, vpos);
  }

  return TRUE;
}

BX_BOOL formJogAxis_TexFMPOS_Click(HBOX hBox)
{
  float vpos;

  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vpos = BxVirtNumBox_GetFloatValue();
    BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGAXIS_TEXFMPOS), vpos);
    MoveAbsAndWait(axis_f, vpos);
  }

  return TRUE;
}

