//Code generated by bxbuilder (c) LMS 2002
// formTomatoInBoxUser.c
#include "Bx.h"
#include "formTomatoInBox.h"
#include "formAxisParm.h"
#include "formJogAxis.h"
#include "formJogIk.h"
#include "formFixPoints.h"
//#include "formOffsetPath.h"
#include "formSetIO.h"
#include "formVision.h"
#include "formEditSysParam.h"
#include "formSysParam.h"
#include "formEditTcp.h"
//#include "formAdjBoxFrames.h"
#include "formLogger.h"
#include "formSetDebug.h"
#include "formStatus.h"
#include "formContinue.h"

#include "robostackerBxr.h"

#include "tmclnx.h"
#include "tmpnrobot.h"
#include "rslib.h"
#include "rs.h"

#include <time.h>
#include <sys/timeb.h>

static BXMENUSTRUCT pBxMainMenu;
static int antalKasser=9999, santalKasser=0;
static int antalPakket=0;
static int antalPaller=0;
static time_t starttid;
static time_t sluttid;

BX_BOOL formTomatoInBoxUserInit(HBOX hBox,BX_LPARAM lParam)
{
  GuidedByVision(FALSE);

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSPEED));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSPEED), 100.0 * GetSpeedFactor());

  BxAssignIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG));
  BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG), rs_param.lag);
  
  BxAssignStringValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABINFO));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABINFOTYPE));

  BxAssignIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDNUMBOX));
  BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDNUMBOX), antalKasser);
  
  BxAssignIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABNUMBOX));
  BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABNUMBOX), antalPakket);

  BxAssignIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABNUMPALLET));
  BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABNUMPALLET), antalPaller);

  BxAssignStringValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABTIME));
//  BxSetCheck(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN), isRunning());
  time(&starttid);
  return TRUE;
}

BX_BOOL formTomatoInBoxUserUpdate(HBOX hBox)
{
  HBOX hBx;
  int state=0, t, m, s;
  char msgstr[256], msgtype[256], tidstr[256];
  char msgstrstate[256];
  
  roboCheckForException(hBox);

  switch(RoboError()) {
    case 4: // pause over baandet => start kasse forfra
        hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formContinue[0], formContinueProc);
  	sprintf(msgtype,"Der er opstået en vacuumfejl.");
	BxSetBoxText(BxGetDlgItem(hBx, FORMCONTINUE_LABINFOTYPE), msgtype);
  	sprintf(msgstr,"Ret produktet og fjern kassen, tryk Fortsæt eller Stop");
	BxSetBoxText(BxGetDlgItem(hBx, FORMCONTINUE_LABINFO), msgstr);
        BxShowBox(BxGetDlgItem(hBx, FORMCONTINUE_CMDCONTINUE), TRUE);
        DoModal(hBx);
      break;
    case 5: // stop over kasse => start kasse forfra
        hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formContinue[0], formContinueProc);
  	sprintf(msgtype,"Der er opstået en vacuumfejl.");
	BxSetBoxText(BxGetDlgItem(hBx, FORMCONTINUE_LABINFOTYPE), msgtype);
  	sprintf(msgstr,"Ret produktet og fjern kassen, tryk Fortsæt eller Stop");
	BxSetBoxText(BxGetDlgItem(hBx, FORMCONTINUE_LABINFO), msgstr);
        BxShowBox(BxGetDlgItem(hBx, FORMCONTINUE_CMDCONTINUE), TRUE);
        DoModal(hBx);
      break;
    case 6: // 
    case 7: //  start helt forfra
        hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formContinue[0], formContinueProc);
  	sprintf(msgtype,"Der er opstået en fejl - robotten er STOPPET.");
	BxSetBoxText(BxGetDlgItem(hBx, FORMCONTINUE_LABINFOTYPE), msgtype);
  	sprintf(msgstr,"Ret produktet, fjern kassen og flyt robotten til start position, tryk Stop");
	BxSetBoxText(BxGetDlgItem(hBx, FORMCONTINUE_LABINFO), msgstr);
        BxShowBox(BxGetDlgItem(hBx, FORMCONTINUE_CMDCONTINUE), FALSE);
	DoModal(hBx);
      break;
    default:
      break;
  }
  
  state = GetRunningState();
  switch(state) {
    case -1:
      sprintf(msgstrstate,"Kommunikationsfejl med Trio....");
      break;
    case 0:
      sprintf(msgstrstate,"Fri");
      break;
    case 3:
      sprintf(msgstrstate,"Venter kommando");
      break;
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      sprintf(msgstrstate,"Klargør robot");
      break;
    case 9:
      sprintf(msgstrstate,"Igang");
      
    case 10:
      sprintf(msgstrstate,"Skaffer palle");
      break;
    case 12:
      sprintf(msgstrstate,"Venter på kasse");
      break;
    case 13:
      sprintf(msgstrstate,"Venter på at håndtag er inde");
      break;
    case 14:
      sprintf(msgstrstate,"Venter på at palle er klar");
      break;
    case 19:
      sprintf(msgstrstate,"Skaffer palle");
      break;
    case 20:
    case 21:
    case 22:
    case 23:
      sprintf(msgstrstate,"Afvikler macro");
      break;
    case 24:
      sprintf(msgstrstate,"Igang - flytter kasse");
      break;
    case 25:
      sprintf(msgstrstate,"Afviser kasse");
      break;
    case 26:
      sprintf(msgstrstate,"Depot til afviste kasse er fyldt");
      break;
    case 1000:
      sprintf(msgstrstate,"LAG 1: Igang - fyld kasse");
      break;
    case 1010:
      sprintf(msgstrstate,"LAG 1: Venter på bakker");
      break;
    case 1020:
      sprintf(msgstrstate,"LAG 1: Igang - stop bånd");
      break;
    case 1030:
    case 1031:
    case 1032:
      sprintf(msgstrstate,"LAG 1: Igang - sug bakker");
      break;
    case 1040:
      sprintf(msgstrstate,"LAG 1: Igang - sug igen");
      break;
    case 1050:
      sprintf(msgstrstate,"LAG 1: Igang - start bånd");
      break;
    case 1060:
      sprintf(msgstrstate,"LAG 1: Igang - test vacuum");
      break;
    case 1061:
    case 1062:
      sprintf(msgstrstate,"LAG 1: Stopper - vacuum fejl");
      break;
    case 1070:
      sprintf(msgstrstate,"LAG 1: Igang - slip bakker");
      break;
    case 1080:
      sprintf(msgstrstate,"LAG 1: Igang - fyld kasse");
      break;

    case 2000:
      sprintf(msgstrstate,"LAG 2: Igang - fyld kasse");
      break;
    case 2010:
      sprintf(msgstrstate,"LAG 2: Venter på bakker");
      break;
    case 2020:
      sprintf(msgstrstate,"LAG 2: Igang - stop bånd");
      break;
    case 2030:
    case 2031:
    case 2032:
      sprintf(msgstrstate,"LAG 2: Igang - sug bakker");
      break;
    case 2040:
      sprintf(msgstrstate,"LAG 2: Igang - sug igen");
      break;
    case 2050:
      sprintf(msgstrstate,"LAG 2: Igang - start bånd");
      break;
    case 2060:
      sprintf(msgstrstate,"LAG 2: Igang - test vacuum");
      break;
    case 2061:
    case 2062:
      sprintf(msgstrstate,"LAG 2: Stopper - vacuum fejl");
      break;
    case 2070:
      sprintf(msgstrstate,"LAG 2: Igang - slip bakker");
      break;
    case 2080:
      sprintf(msgstrstate,"LAG 2: Igang - fyld kasse");
      break;
    
    case 3000:
      sprintf(msgstrstate,"LAG 3: Igang - fyld kasse");
      break;
    case 3010:
      sprintf(msgstrstate,"LAG 3: Venter på bakker");
      break;
    case 3020:
      sprintf(msgstrstate,"LAG 3: Igang - stop bånd");
      break;
    case 3030:
    case 3031:
    case 3032:
      sprintf(msgstrstate,"LAG 3: Igang - sug bakker");
      break;
    case 3040:
      sprintf(msgstrstate,"LAG 3: Igang - sug igen");
      break;
    case 3050:
      sprintf(msgstrstate,"LAG 3: Igang - start bånd");
      break;
    case 3060:
      sprintf(msgstrstate,"LAG 3: Igang - test vacuum");
      break;
    case 3061:
    case 3062:
      sprintf(msgstrstate,"LAG 3: Stopper - vacuum fejl");
      break;
    case 3070:
      sprintf(msgstrstate,"LAG 3: Igang - slip bakker");
      break;
    case 3080:
      sprintf(msgstrstate,"LAG 3: Igang - fyld kasse");
      break;
    
    case 4001:
      sprintf(msgstrstate,"Flytter kasse");
      break;
    default:
      sprintf(msgstrstate,"...");
      break;
  }
  
  sprintf(msgstr,"%s (%d)",msgstrstate,state);
    

//  BxSetStringValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_TEXTLABEL1), GetRSVersion());
  BxSetBoxText(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABINFO), msgstr);     

  switch(RobotState()) {
    case ROBOSTATE_IDLE:
      sprintf(msgtype,"Klar.");
      break;
    case ROBOSTATE_STARTING:
      sprintf(msgtype,"Opstarter.");
      break;
    case ROBOSTATE_RUNNING:
      sprintf(msgtype,"Afvikling af program.");
      break;
    case ROBOSTATE_STOPPING:
      sprintf(msgtype,"Stopper.");
      break;
    case ROBOSTATE_PAUSED:
      sprintf(msgtype,"Pause.");
      break;
    case ROBOSTATE_WDOGOFF:
      sprintf(msgtype,"ROBOSTATE=%d",RobotState());
      break;
    case ROBOSTATE_ERROR:
      sprintf(msgtype,"ROBOSTATE=%d",RobotState());
      break;
    default:
      sprintf(msgtype,"ROBOSTATE=%d",RobotState());
      break;
  }

  BxSetBoxText(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABINFOTYPE), msgtype);

  if(!isRunning())
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDMENU), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSTOP), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG), TRUE);
  }

  if(isRunning())
  {
  	antalPakket = GetVR(701) - santalKasser;
    if(rs_param.lag!=0)
      antalPaller = antalPakket/(rs_param.lag*4);
    else
      antalPaller = 0;
	  time(&sluttid);
  	t = difftime(sluttid, starttid)/3600.0;
  	m = (difftime(sluttid, starttid)-(t*3600.0))/60.0;
  	s = (difftime(sluttid, starttid)-(t*3600.0))-(m*60.0);
  	sprintf(tidstr, "%02d:%02d:%02d", t, m, s);
  	BxSetBoxText(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABTIME), tidstr);
  	BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABNUMBOX), antalPakket);
  	BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_LABNUMPALLET), antalPaller);
	  if(antalPakket >= antalKasser)
      GoRobot(FALSE);
  }
  
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdSpeed_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSPEED)));
  BxVirtNumBox_SetFloatLimits(1.0, 100.0);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSPEED), BxVirtNumBox_GetFloatValue());
    SetSpeedFactor(BxVirtNumBox_GetFloatValue()/100.0);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdRun_Click(HBOX hBox)
{
  if(!isRunning())
  {
    BxSendMessage(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN), BM_PAINT, 0, 0);
    BxUpdateView(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN));
    if(accesslevel<MANAGERLEVEL)
      BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDMENU), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSTOP), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG), FALSE);
    time(&starttid);
    antalPakket = 0;
    antalPaller = 0;
    santalKasser = GetVR(701);
    GoRobot(TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN), FALSE);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdStop_Click(HBOX hBox)
{
  if(isRunning())
  {
    BxSendMessage(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN), BM_PAINT, 0, 0);
    BxUpdateView(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN));
    GoRobot(FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDMENU), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDRUN), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDSTOP), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG), TRUE);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdLag_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG)));
  BxVirtNumBox_SetLimits(1, 9);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDLAG), BxVirtNumBox_GetValue());
    rs_param.lag=BxVirtNumBox_GetValue();
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdNumBox_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDNUMBOX)));
  BxVirtNumBox_SetLimits(0, 10000);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetIntValue(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDNUMBOX), BxVirtNumBox_GetValue());
    antalKasser=BxVirtNumBox_GetValue();
    antalPakket = 0;
    antalPaller = 0;
    santalKasser = GetVR(701);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdAxis_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formAxisParm[0], formAxisParmProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdInOut_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formSetIO[0], formSetIOProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdJogAxis_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formJogAxis[0], formJogAxisProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdJogIk_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formJogIk[0], formJogIkProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdFixPoints_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formFixPoints[0], formFixPointsProc);
  DoModal(hBx);
  return TRUE;
}

/*BX_BOOL formTomatoInBox_cmdAdjBoxFrames_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formAdjBoxFrames[0], formAdjBoxFramesProc);
  DoModal(hBx);
  return TRUE;
}*/

BX_BOOL formTomatoInBox_cmdDebug_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formSetDebug[0], formSetDebugProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdStatus_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formStatus[0], formStatusProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdSystem_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formSysParam[0], formSysParamProc);
  if(DoModal(hBx)==IDOK)
  {
    SaveRSSystemData(&rs_param);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdLog_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formLogger[0], formLoggerProc);
  DoModal(hBx);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdSetupVision_Click(HBOX hBox)
{
  HBOX hBx;
  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formVision[0], formVisionProc);
  DoModal(hBx);
  return TRUE;
}

/*BX_BOOL formTomatoInBox_cmdCalOffset_Click(HBOX hBox)
{
  HBOX hBx;
  tmpnVector aktpos;

  aktpos.x = trobot->m_worldPoint.x;
  aktpos.y = trobot->m_worldPoint.y;
  aktpos.z = trobot->m_worldPoint.z;
  aktpos.v = trobot->m_worldPoint.v;
  aktpos.w = trobot->m_worldPoint.w;

  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formOffsetPath[0], formOffsetPathProc);

  BxSetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDX), aktpos.x);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDY), aktpos.y);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDZ), aktpos.z);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDV), aktpos.v);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDW), aktpos.w);

  if(DoModal(hBx)==IDOK)
  {
    CalOffset.x =  BxGetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDX)) - aktpos.x;
    CalOffset.y =  BxGetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDY)) - aktpos.y;
    CalOffset.z =  BxGetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDZ)) - aktpos.z;
    CalOffset.v =  BxGetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDV)) - aktpos.v;
    CalOffset.w =  BxGetFloatValue(BxGetDlgItem(hBx, FORMOFFSETPATH_CMDW)) - aktpos.w;
  }
  return TRUE;
} */

BX_BOOL formTomatoInBox_cmdAutoHome_Click(HBOX hBox)
{
  if(autoHomeSensor()==0)
    SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdMoveHomeA_Click(HBOX hBox)
{
  trobot->m_mpnhome.a=moveToHomeSensor(axis_a);
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdMoveHomeB_Click(HBOX hBox)
{
  trobot->m_mpnhome.b=moveToHomeSensor(axis_b);
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdMoveHomeC_Click(HBOX hBox)
{
  trobot->m_mpnhome.c=moveToHomeSensor(axis_c);
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdMoveHomeD_Click(HBOX hBox)
{
  trobot->m_mpnhome.d=moveToHomeSensor(axis_d);
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdMoveHomeE_Click(HBOX hBox)
{
  trobot->m_mpnhome.e=moveToHomeSensor(axis_e);
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdMoveHomeF_Click(HBOX hBox)
{
  trobot->m_mpnhome.f=moveToHomeSensor(axis_f);
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdSetZeroA_Click(HBOX hBox)
{
  float currentposition;
  currentposition = GetMPos(axis_a); //or DPos?
  trobot->m_jointCalib.a=0.0-trobot->m_sign.name.a*currentposition;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdSetZeroB_Click(HBOX hBox)
{
  float currentposition;
  currentposition = GetMPos(axis_b); //or DPos?
  trobot->m_jointCalib.b=90.0-trobot->m_sign.name.b*currentposition;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdSetZeroC_Click(HBOX hBox)
{
  float currentposition;
  currentposition = GetMPos(axis_c); //or DPos?
  trobot->m_jointCalib.c=trobot->m_sign.name.c*currentposition;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdSetZeroD_Click(HBOX hBox)
{
  float a,b,c,d,e,f;
  a = GetMPos(axis_a); //or DPos?
  b = GetMPos(axis_b); //or DPos?
  c = GetMPos(axis_c); //or DPos?
  d = GetMPos(axis_d); //or DPos?
  e = GetMPos(axis_e); //or DPos?
  f = GetMPos(axis_f); //or DPos?
  trobot->m_jointCalib.d=0.0;
  trobot->m_jointCalib.e=0.0;
  trobot->m_jointCalib.f=0.0;
  tmpnComputeFK((tmpnRobot*)trobot,a,b,c,d,e,f,2); //use tcp "zero"
  trobot->m_jointCalib.d=trobot->m_sign.name.d*trobot->m_worldPoint.v;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdSetZeroTool_Click(HBOX hBox)
{
  float a,b,c,d,e,f;
  a = GetMPos(axis_a); //or DPos?
  b = GetMPos(axis_b); //or DPos?
  c = GetMPos(axis_c); //or DPos?
  d = GetMPos(axis_d); //or DPos?
  e = GetMPos(axis_e); //or DPos?
  f = GetMPos(axis_f); //or DPos?
  trobot->m_jointCalib.d=0.0;
  trobot->m_jointCalib.e=0.0;
  trobot->m_jointCalib.f=0.0;
  tmpnComputeFK((tmpnRobot*)trobot,a,b,c,d,e,f,2); //use tcp "zero"
  trobot->m_jointCalib.d=trobot->m_sign.name.d*trobot->m_worldPoint.v;
  tmpnComputeFK((tmpnRobot*)trobot,a,b,c,d,e,f,2); //use tcp "zero"
  trobot->m_jointCalib.e=trobot->m_sign.name.e*trobot->m_worldPoint.w;
  tmpnComputeFK((tmpnRobot*)trobot,a,b,c,d,e,f,2); //use tcp "zero"
  trobot->m_jointCalib.f=trobot->m_sign.name.f*trobot->m_worldPoint.u;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}


BX_BOOL formTomatoInBox_cmdSetZeroE_Click(HBOX hBox)
{
  float a,b,c,d,e,f;
  a = GetMPos(axis_a); //or DPos?
  b = GetMPos(axis_b); //or DPos?
  c = GetMPos(axis_c); //or DPos?
  d = GetMPos(axis_d); //or DPos?
  e = GetMPos(axis_e); //or DPos?
  f = GetMPos(axis_f); //or DPos?
  trobot->m_jointCalib.e=0.0;
  trobot->m_jointCalib.f=0.0;
  tmpnComputeFK((tmpnRobot*)trobot,a,b,c,d,e,f,2); //use tcp "zero"
  trobot->m_jointCalib.e=trobot->m_sign.name.e*trobot->m_worldPoint.w;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}
BX_BOOL formTomatoInBox_cmdSetZeroF_Click(HBOX hBox)
{
  float a,b,c,d,e,f;
  a = GetMPos(axis_a); //or DPos?
  b = GetMPos(axis_b); //or DPos?
  c = GetMPos(axis_c); //or DPos?
  d = GetMPos(axis_d); //or DPos?
  e = GetMPos(axis_e); //or DPos?
  f = GetMPos(axis_f); //or DPos?
  trobot->m_jointCalib.f=0.0;
  tmpnComputeFK((tmpnRobot*)trobot,a,b,c,d,e,f,2); //use tcp "zero"
  trobot->m_jointCalib.f=trobot->m_sign.name.f*trobot->m_worldPoint.u;
  SaveCalibrationParam(&rs_param);
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdSetupSysParam_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditSysParam[0], formEditSysParamProc);

  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDAMIN), trobot->m_min.x);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBMIN), trobot->m_min.y);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCMIN), trobot->m_min.z);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDMIN), trobot->m_min.v);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDEMIN), trobot->m_min.w);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDAMAX), trobot->m_max.x);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBMAX), trobot->m_max.y);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCMAX), trobot->m_max.z);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDMAX), trobot->m_max.v);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDEMAX), trobot->m_max.w);

  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDAROFF), trobot->m_localTrans.x);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBROFF), trobot->m_localTrans.y);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCROFF), trobot->m_localTrans.z);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDROFF), trobot->m_localTrans.v);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDEROFF), trobot->m_localTrans.w);

  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDACOFF), trobot->m_jointCalib.a);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBCOFF), trobot->m_jointCalib.b);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCCOFF), trobot->m_jointCalib.c);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDCOFF), trobot->m_jointCalib.d);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDECOFF), trobot->m_jointCalib.e);

  if(DoModal(hBx)==IDOK)
  {
    trobot->m_min.x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDAMIN));
    trobot->m_min.y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBMIN));
    trobot->m_min.z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCMIN));
    trobot->m_min.v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDMIN));
    trobot->m_min.w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDEMIN));
    trobot->m_max.x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDAMAX));
    trobot->m_max.y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBMAX));
    trobot->m_max.z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCMAX));
    trobot->m_max.v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDMAX));
    trobot->m_max.w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDEMAX));

    trobot->m_localTrans.x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDAROFF));
    trobot->m_localTrans.y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBROFF));
    trobot->m_localTrans.z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCROFF));
    trobot->m_localTrans.v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDROFF));
    trobot->m_localTrans.w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDEROFF));

    trobot->m_jointCalib.a = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDACOFF));
    trobot->m_jointCalib.b = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDBCOFF));
    trobot->m_jointCalib.c = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDCCOFF));
    trobot->m_jointCalib.d = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDDCOFF));
    trobot->m_jointCalib.e = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITSYSPARAM_CMDECOFF));

    SaveCalibrationParam(&rs_param);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdCalTcp_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditTcp[0], formEditTcpProc);

  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDAROFF), trobot->m_tcp[caseGripper].x);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDBROFF), trobot->m_tcp[caseGripper].y);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDCROFF), trobot->m_tcp[caseGripper].z);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDDROFF), trobot->m_tcp[caseGripper].v);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDEROFF), trobot->m_tcp[caseGripper].w);

  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDACOFF), trobot->m_tcp[bagGripper].x);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDBCOFF), trobot->m_tcp[bagGripper].y);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDCCOFF), trobot->m_tcp[bagGripper].z);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDDCOFF), trobot->m_tcp[bagGripper].v);
  BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDECOFF), trobot->m_tcp[bagGripper].w);

  if(DoModal(hBx)==IDOK)
  {

    trobot->m_tcp[caseGripper].x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDAROFF));
    trobot->m_tcp[caseGripper].y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDBROFF));
    trobot->m_tcp[caseGripper].z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDCROFF));
    trobot->m_tcp[caseGripper].v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDDROFF));
    trobot->m_tcp[caseGripper].w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDEROFF));

    trobot->m_tcp[bagGripper].x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDACOFF));
    trobot->m_tcp[bagGripper].y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDBCOFF));
    trobot->m_tcp[bagGripper].z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDCCOFF));
    trobot->m_tcp[bagGripper].v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDDCOFF));
    trobot->m_tcp[bagGripper].w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITTCP_CMDECOFF));

    SaveCalibrationParam(&rs_param);
  }
  return TRUE;
}

BX_BOOL formTomatoInBox_cmdMenu_Click(HBOX hBox)
{
  HBOX hBx, ToolBx, ToolJogBx, hOptions, hCalib, hInfo, hSetHome,hSetZero;

  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDMENU), &pBxMainMenu);
  hOptions = BxMenu_Add(hBx ,"Setup", SUB, NULL, TRUE, BxResourceLoadBxIcon(FORMICON_LABOPTION_ICON, "data/robostacker.bxr"));
  BxMenu_Add(hOptions ,"Login", MENU, formTools_cmdSupervisor_Click, TRUE, BxResourceLoadBxIcon(FORMICON_LABUNLOCK_ICON, "data/robostacker.bxr"));
  ToolBx = BxMenu_Add(hBx , "Tools", SUB, NULL, TRUE, BxResourceLoadBxIcon(FORMICON_LABTOOLS_2_ICON, "data/robostacker.bxr"));
  ToolJogBx = BxMenu_Add(ToolBx ,"Jog axis", SUB, NULL, TRUE, NULL);
  BxMenu_Add(ToolJogBx ,"Jog I.K.", MENU, formTomatoInBox_cmdJogIk_Click, TRUE, NULL);
  if(accesslevel>OPERATORLEVEL)
  {
    BxMenu_Add(ToolBx ,"In/Out", MENU, formTomatoInBox_cmdInOut_Click, TRUE, NULL);
   
    hInfo = BxMenu_Add(hOptions , "Info", SUB, NULL, TRUE, NULL);
    BxMenu_Add(hInfo ,"Stat", MENU, formTomatoInBox_cmdStatus_Click, TRUE, NULL);
    BxMenu_Add(hInfo ,"Log", MENU, formTomatoInBox_cmdLog_Click, TRUE, NULL);
    BxMenu_Add(hInfo ,"Debug", MENU, formTomatoInBox_cmdDebug_Click, TRUE, NULL);
    BxMenu_Add(ToolBx ,"Axis parameter", MENU, formTomatoInBox_cmdAxis_Click, TRUE, NULL);
    BxMenu_Add(ToolJogBx ,"Jog Manuel", MENU, formTomatoInBox_cmdJogAxis_Click, TRUE, NULL);
    BxMenu_Add(hOptions ,"Setup vision ", MENU, formTomatoInBox_cmdSetupVision_Click, TRUE, BxResourceLoadBxIcon(FORMICON_LABVISION_ICON, "data/robostacker.bxr"));
    BxMenu_Add(hOptions ,"System", MENU, formTomatoInBox_cmdSystem_Click, TRUE, NULL);
    hCalib = BxMenu_Add(hOptions ,"Calibrate", SUB, NULL, TRUE, NULL);
    BxMenu_Add(hCalib ,"Adjust frames", MENU, formTomatoInBox_cmdFixPoints_Click, TRUE, NULL);
//    BxMenu_Add(hCalib ,"Adjust box frames", MENU, formTomatoInBox_cmdAdjBoxFrames_Click, TRUE, NULL);
//      BxMenu_Add(hCalib ,"Calibrate offset", MENU, formTomatoInBox_cmdCalOffset_Click, TRUE, NULL);
    BxMenu_Add(hCalib ,"Calibrate tcp", MENU, formTomatoInBox_cmdCalTcp_Click, TRUE, NULL);
    BxMenu_Add(hCalib ,"Setup system parameters ", MENU, formTomatoInBox_cmdSetupSysParam_Click, TRUE, NULL);
    BxMenu_Add(hCalib ,"AutoHome", MENU, formTomatoInBox_cmdAutoHome_Click, TRUE, NULL);
    BxMenu_Add(hCalib ,"ZeroTool", MENU, formTomatoInBox_cmdSetZeroTool_Click, TRUE, NULL);
    if(accesslevel>SERVICELEVEL)
    {
      hSetHome = BxMenu_Add(hCalib ,"Home", SUB, NULL, TRUE, NULL);
      hSetZero = BxMenu_Add(hCalib ,"Zero", SUB, NULL, TRUE, NULL);
      BxMenu_Add(hSetHome ,"A", MENU, formTomatoInBox_cmdMoveHomeA_Click, TRUE, NULL);
      BxMenu_Add(hSetHome ,"B", MENU, formTomatoInBox_cmdMoveHomeB_Click, TRUE, NULL);
      BxMenu_Add(hSetHome ,"C", MENU, formTomatoInBox_cmdMoveHomeC_Click, TRUE, NULL);
      BxMenu_Add(hSetHome ,"D", MENU, formTomatoInBox_cmdMoveHomeD_Click, TRUE, NULL);
      BxMenu_Add(hSetHome ,"E", MENU, formTomatoInBox_cmdMoveHomeE_Click, TRUE, NULL);
      BxMenu_Add(hSetHome ,"F", MENU, formTomatoInBox_cmdMoveHomeF_Click, TRUE, NULL);
      BxMenu_Add(hSetZero ,"A", MENU, formTomatoInBox_cmdSetZeroA_Click, TRUE, NULL);
      BxMenu_Add(hSetZero ,"B", MENU, formTomatoInBox_cmdSetZeroB_Click, TRUE, NULL);
      BxMenu_Add(hSetZero ,"C", MENU, formTomatoInBox_cmdSetZeroC_Click, TRUE, NULL);
      BxMenu_Add(hSetZero ,"D", MENU, formTomatoInBox_cmdSetZeroD_Click, TRUE, NULL);
      BxMenu_Add(hSetZero ,"E", MENU, formTomatoInBox_cmdSetZeroE_Click, TRUE, NULL);
      BxMenu_Add(hSetZero ,"F", MENU, formTomatoInBox_cmdSetZeroF_Click, TRUE, NULL);
    }
  }
  DoMenu(BxGetDlgItem(hBox, FORMTOMATOINBOX_CMDMENU));

  return TRUE;
}
