//Copyright (C) 2005 by MPN A/S - Guided by vision(R)
// formEHCMod.h
#if !defined(FORMEHCMOD_H)
#define FORMEHCMOD_H
#include "Bx.h"
#include "formEHCModUser.h"
#define FORMEHCMOD_LABTYPE 1
#define FORMEHCMOD_LABMODNAME 2
#define FORMEHCMOD_TEXTLABEL2_2_2 3
#define FORMEHCMOD_IWORD4 4
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_5 5
#define FORMEHCMOD_LABIWORD3 6
#define FORMEHCMOD_LABIWORD2 7
#define FORMEHCMOD_IWORD5 8
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_4 9
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2 10
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_2 11
#define FORMEHCMOD_IWORD3 12
#define FORMEHCMOD_LABIWORD1 13
#define FORMEHCMOD_LABIWORD5 14
#define FORMEHCMOD_LABIWORD4 15
#define FORMEHCMOD_IWORD2 16
#define FORMEHCMOD_TEXTLABEL2_2_2_2 17
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_3 18
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_2_2 19
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_6 20
#define FORMEHCMOD_TEXTLABEL2_2_2_2_3 21
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_3_2 22
#define FORMEHCMOD_TEXTLABEL2_2_2_2_2_4_2 23
#define FORMEHCMOD_CMDCLOSE 24
extern BX_BOOL formEHCMod_cmdClose_Click(HBOX hBox);
#define FORMEHCMOD_IWORD1 25
#define FORMEHCMOD_IWORD6 26
#define FORMEHCMOD_OWORD1 27
extern BX_BOOL formEHCMod_OWord1_Click(HBOX hBox);
#define FORMEHCMOD_OWORD2 28
extern BX_BOOL formEHCMod_OWord2_Click(HBOX hBox);
#define FORMEHCMOD_OWORD3 29
extern BX_BOOL formEHCMod_OWord3_Click(HBOX hBox);
#define FORMEHCMOD_OWORD4 30
extern BX_BOOL formEHCMod_OWord4_Click(HBOX hBox);
#define FORMEHCMOD_OWORD5 31
extern BX_BOOL formEHCMod_OWord5_Click(HBOX hBox);
#define FORMEHCMOD_LABOWORD1 32
#define FORMEHCMOD_LABOWORD2 33
#define FORMEHCMOD_LABOWORD3 34
#define FORMEHCMOD_LABOWORD4 35
#define FORMEHCMOD_LABOWORD5 36
#define FORMEHCMOD_LABIWORD6 37
extern BX_CHAR formEHCModText[][MAXLANGUAGE][255];
extern BOXSTRUCT formEHCMod[];
extern BX_BOOL formEHCModProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formEHCModUpdate(HBOX hBox);
extern BX_VOID formEHCModInit(HBOX hBox);
#endif // FORMEHCMOD_H
