//Code generated by bxbuilder (c) LMS 2002
// formEditTcpUser.c
#include "Bx.h"
#include "cmd.h"
#include "formEditTcp.h"

static void EditValues(HBOX hBox, int indx)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, indx)));

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, indx), BxVirtNumBox_GetFloatValue());
  }
}

BX_BOOL formEditTcpUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
		BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDRETURN));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDRETURN), getLanguageLineFromIdx(langptr, 74, "Ok"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDCANCEL), getLanguageLineFromIdx(langptr, 3, "Cancel"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITTCP_GROUPBOX1));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITTCP_GROUPBOX1), getLanguageLineFromIdx(langptr, 112, "TCP"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITTCP_TEXTLABEL2_5_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITTCP_TEXTLABEL2_5_2), getLanguageLineFromIdx(langptr, 110, "Case"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMEDITTCP_TEXTLABEL2_5_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMEDITTCP_TEXTLABEL2_5_2_2), getLanguageLineFromIdx(langptr, 111, "Bag"));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDAROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDBROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDCROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDDROFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDEROFF));

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDACOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDBCOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDCCOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDDCOFF));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMEDITTCP_CMDECOFF));
  return TRUE;
}

BX_BOOL formEditTcpUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formEditTcp_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDCANCEL);
  return TRUE;
}

BX_BOOL formEditTcp_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);
  return TRUE;
}

BX_BOOL formEditTcp_cmdEROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDEROFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdDROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDDROFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdCROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDCROFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdBROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDBROFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdAROff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDAROFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdACOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDACOFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdBCOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDBCOFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdCCOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDCCOFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdDCOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDCCOFF);
  return TRUE;
}

BX_BOOL formEditTcp_cmdECOff_Click(HBOX hBox)
{
  EditValues(hBox, FORMEDITTCP_CMDECOFF);
  return TRUE;
}

