//Code generated by bxbuilder (c) LMS 2002 
// formAdjBoxFramesUser.c
#include "Bx.h"
#include "formAdjBoxFrames.h"
#include "formEditBoxPattern.h"

#include "tmclnx.h"
#include "rs.h"

static BXMENUSTRUCT pBxMenu;

BX_BOOL formAdjBoxFramesUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMADJBOXFRAMES_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMADJBOXFRAMES_TEXTLABEL2_2), GetRSType());

  BxList_AddString(BxGetDlgItem(hBox, FORMADJBOXFRAMES_LISTBOX), "Intercrate - IC2 - 3Kg.");
  return TRUE;
}

BX_BOOL formAdjBoxFramesUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formAdjBoxFrames_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, TRUE);
  return TRUE;
}

BX_BOOL formAdjBoxFrames_cmdEdit_Click(HBOX hBox)
{
  HBOX hBx;
  
  switch(BxList_GetSelected(BxGetDlgItem(hBox, FORMADJBOXFRAMES_LISTBOX)))
  {
    case 0:
//      bagPatternLoad("bagpatternNr1.dat", &tbagpattern);
      hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditBoxPattern[0], formEditBoxPatternProc);
      if(DoModal(hBx)==IDOK)
      {
//        bagPatternSave("bagpatternNr1.dat", &tbagpattern);
      }
      break;          
  }
  return TRUE;
}

BX_BOOL formAdjBoxFrames_cmdMenu_Click(HBOX hBox)
{
  HBOX hBx;

  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMADJBOXFRAMES_CMDMENU), &pBxMenu);
  BxMenu_Add(hBx ,"Edit", MENU, formAdjBoxFrames_cmdEdit_Click, TRUE, NULL);
  BxMenu_Add(hBx ,"Return", MENU, formAdjBoxFrames_cmdReturn_Click, TRUE, NULL);
  DoMenu(BxGetDlgItem(hBox, FORMADJBOXFRAMES_CMDMENU));
  return TRUE;
}

BX_BOOL formAdjBoxFrames_listBox_Click(HBOX hBox)
{
  return TRUE;
}
