//Code generated by bxbuilder (c) LMS 2002
// formFixPointsUser.c
#include "Bx.h"
#include "formFixPoints.h"
#include "formEditFrame.h"

#include "rs.h"
#include"tmpnrobot.h"
#include"cmd.h"

static BXMENUSTRUCT pBxMenu;

static int newframes = 0;
static tmpnStateMachine *stm=NULL;
char *fixpointsFrameName=NULL;

BX_BOOL formFixPointsUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
  int i;
	int idx=-1;
	BxAssignStringValue(BxGetDlgItem(hBox, FORMFIXPOINTS_CMDMENU));
	BxSetStringValue(BxGetDlgItem(hBox, FORMFIXPOINTS_CMDMENU), getLanguageLineFromIdx(langptr, 17, "Menu"));
	if ((idx=getMachineIdx("Frames")) != -1)
	{
		newframes=1;
		stm=&tworkcell->statemachines.statemachine[idx];
		for (i=0;i<stm->numvalue;i++)
		{
			if (stm->value[i].type==FRAME)
			{
				BxList_AddString(BxGetDlgItem(hBox, FORMFIXPOINTS_LISTBOX), stm->value[i].frame->name);
			}
		}
	}
	else
	{
		for(i=0;i<trobot->m_frames.maxidx;i++)
			BxList_AddString(BxGetDlgItem(hBox, FORMFIXPOINTS_LISTBOX), (char*)trobot->m_frames.frame[i].name);
	}
	return TRUE;
}

BX_BOOL formFixPointsUserUpdate(HBOX hBox)
{                               
 return TRUE;
}

BX_BOOL formFixPoints_listBox_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formFixPoints_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, TRUE);
  return TRUE;
}

BX_BOOL formFixPoints_cmdEdit_Click(HBOX hBox)
{
  HBOX hBx;
  int index = BxList_GetSelected(BxGetDlgItem(hBox, FORMFIXPOINTS_LISTBOX));
	if(index >= 0)
	{
		if (newframes)
		{
			tmpnFrame *fr;
			fr=getStmFrame((char *)BxList_GetString(BxGetDlgItem(hBox, FORMFIXPOINTS_LISTBOX),index));
			if (fr!=NULL)
			{
				fixpointsFrameName=(char *)BxList_GetString(BxGetDlgItem(hBox, FORMFIXPOINTS_LISTBOX),index);
				hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditFrame[0], formEditFrameProc);
				BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX), fr->x);
				BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY), fr->y);
				BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ), fr->z);
				BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV), fr->v);
				BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW), fr->w);
				if(DoModal(hBx)==IDOK)
				{
					fr->x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX));
					fr->y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY));
					fr->z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ));
					fr->v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV));
					fr->w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW));
					SaveFrameVal(stm->name,fr);
					//TODO tell LOADER to recalculate all relavent paths
				}
			}
		}
	}
	else
	{
		fixpointsFrameName=(char*)trobot->m_frames.frame[index].name;
		hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEditFrame[0], formEditFrameProc);
		BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX), trobot->m_frames.frame[index].x);
		BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY), trobot->m_frames.frame[index].y);
		BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ), trobot->m_frames.frame[index].z);
		BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV), trobot->m_frames.frame[index].v);
		BxSetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW), trobot->m_frames.frame[index].w);
		if(DoModal(hBx)==IDOK)
		{
			trobot->m_frames.frame[index].x = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDX));
			trobot->m_frames.frame[index].y = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDY));
			trobot->m_frames.frame[index].z = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDZ));
			trobot->m_frames.frame[index].v = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDV));
			trobot->m_frames.frame[index].w = BxGetFloatValue(BxGetDlgItem(hBx, FORMEDITFRAME_CMDW));
			updatecmdPoints(NULL);
			SaveCalibrationParam(&rs_param);
		}
	}
  return TRUE;
}

BX_BOOL formFixPoints_cmdMenu_Click(HBOX hBox)
{
  HBOX hBx;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMFIXPOINTS_CMDMENU), &pBxMenu);
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 80, "Edit"), MENU, formFixPoints_cmdEdit_Click, TRUE, NULL);
  BxMenu_Add(hBx ,getLanguageLineFromIdx(langptr, 5, "Return"), MENU, formFixPoints_cmdReturn_Click, TRUE, NULL);
  DoMenu(BxGetDlgItem(hBox, FORMFIXPOINTS_CMDMENU));
  return TRUE;
}

BX_BOOL formFixPoints_cmdBoxFix_Click(HBOX hBox)
{
  return TRUE;
}

