//Code generated by bxbuilder (c) LMS 2002 
// formAVOMod.h
#if !defined(FORMAVOMOD_H)
#define FORMAVOMOD_H
#include "Bx.h"
#include "formAVOModUser.h"
#define FORMAVOMOD_TEXTLABEL2_2_2 1
#define FORMAVOMOD_CMDCLOSE 2
extern BX_BOOL formAVOMod_cmdClose_Click(HBOX hBox);
#define FORMAVOMOD_LABMODNAME 3
#define FORMAVOMOD_LABTYPE 4
#define FORMAVOMOD_TEXTLABEL1 5
#define FORMAVOMOD_TEXTLABEL2 6
#define FORMAVOMOD_LABCONNECT2 7
#define FORMAVOMOD_LABCONNECT1 8
#define FORMAVOMOD_DATA1 9
extern BX_BOOL formAVOMod_Data1_Click(HBOX hBox);
#define FORMAVOMOD_DATA2 10
extern BX_BOOL formAVOMod_Data2_Click(HBOX hBox);
extern BX_CHAR formAVOModText[][MAXLANGUAGE][255];
extern BOXSTRUCT formAVOMod[];
extern BX_BOOL formAVOModProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formAVOModUpdate(HBOX hBox);
extern BX_VOID formAVOModInit(HBOX hBox);
#endif // FORMAVOMOD_H
