//Code generated by bxbuilder (c) LMS 2002 
// formSetDebug.c
#include "Bx.h"
#include "formSetDebug.h"

BOXSTRUCT formSetDebug[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formSetDebug[1], NULL}
 ,{FORMSETDEBUG_CMDOK,{500,480,629,579},BUTTON,"Ok",BBS_PUSHBUTTON|BXS_VISIBLE,&formSetDebug[2], &formSetDebug[0]}
 ,{FORMSETDEBUG_CMDCANCEL,{650,480,779,579},BUTTON,"Cancel",BBS_PUSHBUTTON|BXS_VISIBLE,&formSetDebug[3], &formSetDebug[0]}
 ,{FORMSETDEBUG_TEXTLABEL2_2,{20,10,269,44},STATIC,"Debug settings",BXS_VISIBLE,&formSetDebug[4], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKLOOP,{310,280,369,339},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[5], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKWITHPALLET,{310,140,369,199},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[6], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKWITHPRODUCT,{310,70,369,129},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[7], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB,{20,80,279,129},STATIC,"With products",BXS_VISIBLE,&formSetDebug[8], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_2,{20,150,279,199},STATIC,"With pallet",BXS_VISIBLE,&formSetDebug[9], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_2_2_2,{20,290,279,339},STATIC,"Loop mode",BXS_VISIBLE,&formSetDebug[10], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_2_2,{20,220,279,269},STATIC,"With box",BXS_VISIBLE,&formSetDebug[11], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_2_2_3,{20,360,279,409},STATIC,"With reject",BXS_VISIBLE,&formSetDebug[12], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKWITHBOX,{310,210,369,269},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[13], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_3,{430,80,689,129},STATIC,"Simulate",BXS_VISIBLE,&formSetDebug[14], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKONLINE,{720,70,779,129},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[15], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKWITHREJECT,{310,350,369,409},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[16], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_3_2,{430,150,689,199},STATIC,"Reset status",BXS_VISIBLE,&formSetDebug[17], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKRESETSTAT,{720,140,779,199},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[18], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_3_2_2,{430,220,689,269},STATIC,"Reset current limits",BXS_VISIBLE,&formSetDebug[19], &formSetDebug[0]}
 ,{FORMSETDEBUG_LAB_3_2_2_2,{430,290,689,339},STATIC,"Reset follow error",BXS_VISIBLE,&formSetDebug[20], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKRESETCURRENT,{720,210,779,269},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[21], &formSetDebug[0]}
 ,{FORMSETDEBUG_CHKRESETFOLLOWERR,{720,280,779,339},BUTTON,"",BBS_CHECKBOX|BXS_VISIBLE,&formSetDebug[22], &formSetDebug[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formSetDebug[0]}
};

BX_BOOL formSetDebugProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formSetDebugUpdate(hBox);
				return formSetDebugUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formSetDebugInit(hBox);
				return formSetDebugUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMSETDEBUG_CMDOK:
             return formSetDebug_cmdOk_Click(hBox);
         case FORMSETDEBUG_CMDCANCEL:
             return formSetDebug_cmdCancel_Click(hBox);
         case FORMSETDEBUG_CHKLOOP:
             return formSetDebug_chkLoop_Click(hBox);
         case FORMSETDEBUG_CHKWITHPALLET:
             return formSetDebug_chkWithPallet_Click(hBox);
         case FORMSETDEBUG_CHKWITHPRODUCT:
             return formSetDebug_chkWithProduct_Click(hBox);
         case FORMSETDEBUG_CHKWITHBOX:
             return formSetDebug_chkWithBox_Click(hBox);
         case FORMSETDEBUG_CHKONLINE:
             return formSetDebug_chkOnline_Click(hBox);
         case FORMSETDEBUG_CHKWITHREJECT:
             return formSetDebug_chkWithReject_Click(hBox);
         case FORMSETDEBUG_CHKRESETSTAT:
             return formSetDebug_chkResetStat_Click(hBox);
         case FORMSETDEBUG_CHKRESETCURRENT:
             return formSetDebug_chkResetCurrent_Click(hBox);
         case FORMSETDEBUG_CHKRESETFOLLOWERR:
             return formSetDebug_chkResetFollowErr_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
