//Code generated by bxbuilder (c) LMS 2002 
// formInterruptUser.c
#include <unistd.h>
#include "Bx.h"
#include "formInterrupt.h"
#include "rs.h"

static int state = 0;
char mc_alert[256];
char mc_reason[256];
char mc_solution[256];

BX_BOOL formInterruptUserInit(HBOX hBox,BX_LPARAM lParam)
{
  char cmd[256] = "";
  int val, err;
  
  BxAssignStringValue(BxGetDlgItem(hBox, FORMINTERRUPT_TEXTLABEL2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMINTERRUPT_TEXTLABEL2), GetRSVersion());
  BxAssignStringValue(BxGetDlgItem(hBox, FORMINTERRUPT_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMINTERRUPT_TEXTLABEL2_2), GetRSType());

  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMINTERRUPT_TXTALERT))->lpBoxStr = mc_alert;
  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMINTERRUPT_TXTREASON))->lpBoxStr = mc_reason;
  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION))->lpBoxStr = mc_solution;

  // hvad er get galt?
  // check for noedstop
  if(emergency())
  {
    BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTALERT), "roboStacker er stoppet!");
    BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTREASON), "Nødstop er trykket.");
    BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Frigiv nødstop og tryk reset.");
    BxSendMessage(BxGetDlgItem(hBox, FORMINTERRUPT_CMDCONTINUE), BM_SHOWBOX, FALSE, 0);
    state = 1; // emergency brake pressed.
    return TRUE;
  }

  // check for basic error.
  val = GetBasicError();
  if(val)
  {
    err = GetBasicLineError();

    BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTALERT), "roboStacker er stoppet!");
    sprintf(cmd, "TRIO Basic error on line %d, %d.", err, val);
    BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTREASON), cmd);
    BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Frigiv nødstop og tryk reset");
    BxSendMessage(BxGetDlgItem(hBox, FORMINTERRUPT_CMDCONTINUE), BM_SHOWBOX, TRUE, 0);
    state = 0; // press continue.
    return TRUE;
  }

  // check for follow error.
  val = GetErrorAxis();
  BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTALERT), "roboStacker er stoppet!");
  sprintf(cmd, "Follow error on axis %d.", val);
  BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTREASON), cmd);
  BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Frigiv nødstop og tryk reset.");
  BxSendMessage(BxGetDlgItem(hBox, FORMINTERRUPT_CMDCONTINUE), BM_SHOWBOX, TRUE, 0);
  state = 0; // press continue.
  return TRUE;

  BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTALERT), "roboStacker er stoppet!");
  BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTREASON), "Watchdog off - Unknown reason.");
  BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Call expert.");
  BxSendMessage(BxGetDlgItem(hBox, FORMINTERRUPT_CMDCONTINUE), BM_SHOWBOX, TRUE, 0);

  return TRUE;
}

BX_BOOL formInterruptUserUpdate(HBOX hBox)
{
  int val;

  switch(state) {
    case 0 : // press reset
      if(emergency())
        state++;
      break;
    case 1 : // press reset
      if(!emergency())
      {
        CancelMc(1);
        BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Canceling controller...");
        usleep(2000000);
        // start RESET
        if (CmdStartup()==0)
          state++;
          BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Starting up axis...");
      }
      break;
    case 2 :  // reset DONE.
      val = GetReply();
      if(val==1)
      {
        // start mpn_command_set_units_and_defaults
        if(SetUnitsAndDefaults()==0)
        {
          state++;
          BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Setup units and defaults...");
        }
      }
      break;
    case 3 : // is setup units .... done ?
      val = GetReply();
      if(val==1)
      {
        state++;
        BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Setup default position...");
      }
      break;
    case 4 : // is setup units .... done ?
      val = GetReply();
      if(val==1)
      {
        // start mpn_command_resetaxis
        if(ResetAxis()==0)
        {
          state++;
          BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Reset axis...");
        }
      }
      break;
    case 5 : // is reset .... done ?
      val = GetReply();
      if(val==1)
      {
        // start mpn_command_set_mpn_home_all
        if(SetHomeAll()==0)
        {
          state++;
          BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Finding home...");
        }
      }
      break;
    case 6 : // continue
      val = GetReply();
      if(val==1)
      {
        state = 7;
        BxSetBoxText(BxGetDlgItem(hBox, FORMINTERRUPT_TXTSOLUTION), "Press Continue.");
        val = (float)GetRetur();
        if(IsVisible(BxGetDlgItem(hBox, FORMINTERRUPT_CMDCONTINUE))==FALSE)
        {
          if(val==0)   
            BxEndDialog(hBox, IDOK);
          else
            BxEndDialog(hBox, IDCANCEL);
          return FALSE;
        }
      }
      break;
  }
  return TRUE;
}

BX_BOOL formInterrupt_cmdContinue_Click(HBOX hBox)
{
  switch(state) {
    case 7 : // press continue
        BxEndDialog(hBox, IDOK);
        return FALSE;
      break;
  }
  return TRUE;
}

BX_BOOL roboCheckForException(HBOX hBox)
{
  HBOX hBx;
  if(IsWDOGOn()==FALSE||emergency())
  {
    hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formInterrupt[0], formInterruptProc);
    DoModal(hBx);
  }
  return TRUE;
}
