//Code generated by bxbuilder (c) LMS 2002 
// formPathEditorUser.h

extern BX_BOOL formPathEditorUserInit(HBOX hBox,BX_LPARAM lParam);
extern BX_BOOL formPathEditorUserUpdate(HBOX hBox);
extern BX_BOOL SetPathEditorFileName(BX_PSTRING pstr);
extern BX_PSTRING GetPathEditorFileName(BX_VOID);

