//Code generated by bxbuilder (c) LMS 2002 
// formVisionUser.c
#include "Bx.h"
#include "formVision.h"

#include "rs.h"

BX_BOOL formVisionUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTFPS));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMVISION_CMDMINHEIGHT));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMVISION_CMDSMALL));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTLENGTH));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTWIDTH));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTHEIGHT));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMVISION_TEXTANGLE));
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTFPS), vicam.fps);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDMINHEIGHT), vicam.minimum);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDSMALL), vicam.minlen);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTLENGTH), vicam.length);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTWIDTH), vicam.width);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTHEIGHT), vicam.height);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMVISION_TEXTANGLE), vicam.angle);
  BxSetCheck(BxGetDlgItem(hBox, FORMVISION_CHECKCONNECT), vicam.connected);
  BxSetCheck(BxGetDlgItem(hBox, FORMVISION_CHECKGUIDEDBYVISION), GuidedByVision(-1));
  return TRUE;
}

BX_BOOL formVisionUserUpdate(HBOX hBox)
{
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTFPS), vicam.fps);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDMINHEIGHT), vicam.minimum);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDSMALL), vicam.minlen);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTLENGTH), vicam.length);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTWIDTH), vicam.width);
  BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_TEXTHEIGHT), vicam.height);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMVISION_TEXTANGLE), vicam.angle);
  BxSetCheck(BxGetDlgItem(hBox, FORMVISION_CHECKCONNECT), vicam.connected);
  BxSetCheck(BxGetDlgItem(hBox, FORMVISION_CHECKGUIDEDBYVISION), GuidedByVision(-1));
  return TRUE;
}

BX_BOOL formVision_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  SaveVisionParam();
  return FALSE;
}

BX_BOOL formVision_checkConnect_Click(HBOX hBox)
{
  BxSetCheck(BxGetDlgItem(hBox, FORMVISION_CHECKCONNECT), vicam.connected);
  return TRUE;
}

BX_BOOL formVision_checkGuidedByVision_Click(HBOX hBox)
{
  GuidedByVision(BxGetCheck(BxGetDlgItem(hBox, FORMVISION_CHECKGUIDEDBYVISION)));
  return TRUE;
}

BX_BOOL formVision_cmdMinHeight_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDMINHEIGHT)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vicam.minimum = BxVirtNumBox_GetValue();
    BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDMINHEIGHT), vicam.minimum);
  }
  return TRUE;
}

BX_BOOL formVision_cmdIpAddress_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formVision_cmdSmall_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDSMALL)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    vicam.minlen = BxVirtNumBox_GetValue();
    BxSetIntValue(BxGetDlgItem(hBox, FORMVISION_CMDSMALL), vicam.minlen);
  }
  return TRUE;
}

