//Code generated by bxbuilder (c) LMS 2002 
// formJogIkUser.c
#include <unistd.h>
#include "Bx.h"
#include "formJogIk.h"
#include "rs.h"
#include "tmpnrobot.h"
#include "cmd.h"

extern tmpnJoints m_actuator;
extern volatile unsigned int mposupdatecount;
extern pthread_mutex_t actuator_mutex;
extern volatile int jogikscreen;

static char jogspeed[256];
static char ikstep[256];
static char tcpidxstr[256];
float jogikspeed = 50.0; //50mm i sek.
float jogikstep = 50.0;
tmpnStateMachineValue *jogzmax=NULL;
static int framesstm = -1;

void UpdateIkView(HBOX hBox)
{
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXAMPOS), trobot->m_worldPoint.x);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXBMPOS), trobot->m_worldPoint.y);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXCMPOS), trobot->m_worldPoint.z);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTTILTANGLE), trobot->m_worldPoint.v);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTTURNANGLE), trobot->m_worldPoint.w);
}

void WaitForNextMPOS(void)
{
	unsigned int mposcounter;
	if(rs_param.simulateMC!=0) return;
	mposcounter=mposupdatecount;
	while (mposcounter==mposupdatecount)
	{
		usleep(10000);
	}
	return;
}

int MoveToPosition(void)
{
	
  long rc;
	rc=MoveAllAbs(trobot->m_actuator.a,trobot->m_actuator.b,trobot->m_actuator.c,trobot->m_actuator.d,trobot->m_actuator.e);
	usleep(100000);
	while (GetMType(1)!=0)
	{
		usleep(100000);
	}
	WaitForNextMPOS();
	return rc;
}


BX_BOOL formJogIkUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BOXSTRUCT *b;
	jogikscreen=1;
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];

  BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL2_2), GetRSType());

	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL2_2_2), getLanguageLineFromIdx(langptr, 15, "Speed"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL_2_2), getLanguageLineFromIdx(langptr, 75, "Tilt"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL_2), getLanguageLineFromIdx(langptr, 76, "Turn"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTLEFT));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTLEFT), getLanguageLineFromIdx(langptr, 7, "Left"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTRIGHT));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTRIGHT), getLanguageLineFromIdx(langptr, 6, "Right"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNLEFT));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNLEFT), getLanguageLineFromIdx(langptr, 7, "Left"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNRIGHT));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNRIGHT), getLanguageLineFromIdx(langptr, 6, "Right"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABEL2), getLanguageLineFromIdx(langptr, 10, "Step"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_CMDCANCEL), getLanguageLineFromIdx(langptr, 54, "Close"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABELIKTCPIDX));
	BxSetStringValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABELIKTCPIDX), getLanguageLineFromIdx(langptr, 77, "TCP idx"));

  framesstm = getMachineIdx("Frames");
  jogzmax = getMachineValue(framesstm,"jogzmax");

  if(rs_param.workcellid==319
   ||rs_param.workcellid==320
   ||rs_param.workcellid==321)
  {
    SetSpeed(axis_a, jogikspeed);
    SetAccel(axis_a, jogikspeed*0.5);
    SetDecel(axis_a, jogikspeed*0.5);
  }
	else
  {
    SetSpeed(axis_a, jogikspeed);
    SetAccel(axis_a, jogikspeed*2);
    SetDecel(axis_a, jogikspeed*2);
	}


  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMJOGIK_CMDIKTCPIDX);
  sprintf(tcpidxstr,"%i", trobot->m_tcpidx);
  b->lpBoxStr = tcpidxstr;

	pthread_mutex_lock(&actuator_mutex);
  tmpnComputeFK((tmpnRobot*)trobot, m_actuator.a, m_actuator.b, m_actuator.c, m_actuator.d, m_actuator.e, m_actuator.f,trobot->m_tcpidx);
	pthread_mutex_unlock(&actuator_mutex);

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMJOGIK_CMDJOGSPEED);
  sprintf(jogspeed,"%.2f", jogikspeed);
  b->lpBoxStr = jogspeed;

  b = (BOXSTRUCT*)BxGetDlgItem(hBox, FORMJOGIK_CMDIKSTEP);
  sprintf(ikstep,"%.2f", jogikstep);
  b->lpBoxStr = ikstep;

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXAMPOS));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXAMPOS), trobot->m_worldPoint.x);

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXBMPOS));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXBMPOS), trobot->m_worldPoint.y);

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXCMPOS));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXCMPOS), trobot->m_worldPoint.z);

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTTILTANGLE));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTTURNANGLE));

  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTTILTANGLE), trobot->m_worldPoint.v);
  BxSetFloatValue(BxGetDlgItem(hBox, FORMJOGIK_TEXTTURNANGLE), trobot->m_worldPoint.w);

  if(accesslevel>SERVICELEVEL)
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDJOGSPEED), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDIKSTEP), TRUE);
    //    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDZLEFT), TRUE);
    // BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDZRIGHT), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTRIGHT), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNRIGHT), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTLEFT), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNLEFT), TRUE);
    BxShowBox(BxGetDlgItem(hBox, FORMJOGIK_CMDIKTCPIDX), TRUE);
    BxShowBox(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABELIKTCPIDX), TRUE);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDJOGSPEED), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDIKSTEP), FALSE);
    //   BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDZLEFT), FALSE);
    // BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDZRIGHT), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTRIGHT), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNRIGHT), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTILTLEFT), FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMJOGIK_CMDTURNLEFT), FALSE);
    BxShowBox(BxGetDlgItem(hBox, FORMJOGIK_CMDIKTCPIDX), FALSE);
    BxShowBox(BxGetDlgItem(hBox, FORMJOGIK_TEXTLABELIKTCPIDX), FALSE);
  }

  return TRUE;
}

BX_BOOL formJogIkUserUpdate(HBOX hBox)
{
	jogikscreen=1;
	pthread_mutex_lock(&actuator_mutex);
  tmpnComputeFK((tmpnRobot*)trobot, m_actuator.a, m_actuator.b, m_actuator.c, m_actuator.d, m_actuator.e, m_actuator.f,trobot->m_tcpidx);
	pthread_mutex_unlock(&actuator_mutex);
	UpdateIkView(hBox); 
  return TRUE;
}

BX_BOOL formJogIk_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, TRUE);
	jogikscreen=0;
  return FALSE;
}

BX_BOOL formJogIk_cmdZRight_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	z += jogikstep;
  if(jogzmax!=NULL && z>jogzmax->fdata)
  {
    z=jogzmax->fdata;
  }
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u,trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdZLeft_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	z -= jogikstep;
  if(jogzmax!=NULL && z<0.0)
  {
    z=0.0;
  }
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u,trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdIkStep_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(jogikstep);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    jogikstep = BxVirtNumBox_GetFloatValue();
    sprintf(ikstep, "%0.2f", jogikstep);
  }
  BxRequestPaint(BxGetDlgItem(hBox, FORMJOGIK_CMDIKSTEP));
  return TRUE;
}

BX_BOOL formJogIk_cmdJogSpeed_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(jogikspeed);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    jogikspeed = BxVirtNumBox_GetFloatValue();
    sprintf(jogspeed, "%.2f", jogikspeed);
    BxRequestPaint(BxGetDlgItem(hBox, FORMJOGIK_CMDJOGSPEED));

    if(rs_param.workcellid==319
     ||rs_param.workcellid==320
     ||rs_param.workcellid==321)
    {
      SetSpeed(axis_a, jogikspeed);
      SetAccel(axis_a, jogikspeed*0.5);
      SetDecel(axis_a, jogikspeed*0.5);
    }
	  else
    {
      SetSpeed(axis_a, jogikspeed);
      SetAccel(axis_a, jogikspeed*2);
      SetDecel(axis_a, jogikspeed*2);
	  }
  }
  return TRUE;
}

BX_BOOL formJogIk_cmdIkTcpIdx_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(trobot->m_tcpidx);
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    trobot->m_tcpidx = BxVirtNumBox_GetValue();
    sprintf(tcpidxstr, "%i", trobot->m_tcpidx);
    BxRequestPaint(BxGetDlgItem(hBox, FORMJOGIK_CMDIKTCPIDX));
		pthread_mutex_lock(&actuator_mutex);
    tmpnComputeFK((tmpnRobot*)trobot, m_actuator.a, m_actuator.b, m_actuator.c, m_actuator.d, m_actuator.e, m_actuator.f,trobot->m_tcpidx);
		pthread_mutex_unlock(&actuator_mutex);
    UpdateIkView(hBox);
		WaitForNextMPOS();
  }
  return TRUE;
}

BX_BOOL formJogIk_cmdUp_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	y += jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u, trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
  return TRUE;
}

BX_BOOL formJogIk_cmdDown_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	y -= jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u, trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdRight_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	x += jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u, trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdLeft_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	x -= jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u,trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdTiltLeft_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	v -= jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u, trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdTiltRight_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	v += jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u, trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdTurnLeft_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	w -= jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u,trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}

BX_BOOL formJogIk_cmdTurnRight_Click(HBOX hBox)
{
	float x = trobot->m_worldPoint.x;
	float y = trobot->m_worldPoint.y;
	float z = trobot->m_worldPoint.z;
	float v = trobot->m_worldPoint.v;
	float w = trobot->m_worldPoint.w;
	float u = trobot->m_worldPoint.u;
	
	w += jogikstep;
	if(tmpnComputeIK((tmpnRobot*)trobot, x, y, z, v, w, u, trobot->m_tcpidx))
	{
		tmpnJointToActuator((tmpnRobot*)trobot,trobot->m_tcpidx);
		UpdateIkView(hBox);
		MoveToPosition();
	}
	return TRUE;
}
