//Code generated by bxbuilder (c) LMS 2002 
// formSetOutPutUser.c
#include "Bx.h"
#include "formSetOutPut.h"

BX_BOOL formSetOutPutUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignIntValue(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDOUTPUTNUM));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDINPUTNUM));
  return TRUE;
}

BX_BOOL formSetOutPutUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formSetOutPut_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, FALSE);
  return FALSE;
}

BX_BOOL formSetOutPut_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, TRUE);
  return FALSE;
}

BX_BOOL formSetOutPut_cmdOutPutNum_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDOUTPUTNUM)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetIntValue(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDOUTPUTNUM), BxVirtNumBox_GetValue());
  }
//  BxRequestPaint(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDOUTPUTNUM));
  return TRUE;
}

BX_BOOL formSetOutPut_cmdInPutNum_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDINPUTNUM)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetIntValue(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDINPUTNUM), BxVirtNumBox_GetValue());
  }
//  BxRequestPaint(BxGetDlgItem(hBox, FORMSETOUTPUT_CMDINPUTNUM));
  return TRUE;
}

BX_BOOL formSetOutPut_chkOutput_Click(HBOX hBox)
{
//  outputstate = BxGetCheck(BxGetDlgItem(hBox, FORMSETOUTPUT_CHKOUTPUT));
  return TRUE;
}

BX_BOOL formSetOutPut_chkInput_Click(HBOX hBox)
{
//  outputstate = BxGetCheck(BxGetDlgItem(hBox, FORMSETOUTPUT_CHKINPUT));
  return TRUE;
}

BX_BOOL formSetOutPut_radioOutput_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetOutPut_radioInput_Click(HBOX hBox)
{
  return TRUE;
}

