//Code generated by bxbuilder (c) LMS 2002
// formPedalBoxUser.c
#include "Bx.h"
#include "formPedalBox.h"

#include "tmclnx.h"
#include "rs.h"
#include "tmpnrobot.h"

static char pbstr[32];
static char pbstr2[32];
static BXPROGRESSBARSTRUCT pBxBar, pBxBar2;

extern volatile int ppos;
extern volatile float rpos;
extern volatile float rpctpos;

static int __layer = 0;
static int __boxes = 0;

void CalcLayerAndBoxFromPath(void)
{
  COMMANDSTRUCT *pcmd = firstruncmd;
  int box=1;
  int layer=0;

  while(pcmd)
  {
    if(pcmd==ptrruncmd)
      break;
    if(pcmd->type==PATH)
    {
      if(box<4)
        box++;
      else
      {
        layer++;
        box=1;
      }
    }
    pcmd = pcmd->next;
  }
  layer+=1;
  if(layer>16)
    __layer = 1;
  else
    __layer = layer;
  __boxes = box;

  if(layer==17 && box==0)
    __layer=17;
  
}

void SetCurrentPathNum(int n)
{
  COMMANDSTRUCT *pcmd = firstruncmd;
  int i=0;
  while(pcmd)
  {
    if(pcmd->type==PATH)
    {
      if(i==n)
        break;
      i++;
    }
    pcmd = pcmd->next;
  }
  ptrruncmd = pcmd;
}

void SetupScreen(HBOX hBox)
{
  if(__layer >= 9)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA1), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA1), FALSE);
  if(__layer >= 10)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA2), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA2), FALSE);
  if(__layer >= 11)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA3), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA3), FALSE);
  if(__layer >= 12)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA4), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA4), FALSE);
  if(__layer >= 13)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA5), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA5), FALSE);
  if(__layer >= 14)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA6), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA6), FALSE);
  if(__layer >= 15)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA7), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA7), FALSE);
  if(__layer >= 16)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA8), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA8), FALSE);

  if(__layer >= 1)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC1), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC1), FALSE);
  if(__layer >= 2)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC2), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC2), FALSE);
  if(__layer >= 3)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC3), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC3), FALSE);
  if(__layer >= 4)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC4), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC4), FALSE);
  if(__layer >= 5)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC5), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC5), FALSE);
  if(__layer >= 6)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC6), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC6), FALSE);
  if(__layer >= 7)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC7), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC7), FALSE);
  if(__layer >= 8)
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC8), TRUE);
  else
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC8), FALSE);

  if(__layer < 9)
  {
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), FALSE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), FALSE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), FALSE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), FALSE);
    if(__boxes > 0)
    {
      if(__boxes == 1)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), FALSE);
      
    if(__boxes > 1)
    {
      if(__boxes == 2)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), FALSE);

    if(__boxes > 2)
    {
      if(__boxes == 3)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), FALSE);

    if(__boxes > 3)
    {
      if(__boxes == 4)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), FALSE);

  }  
  if(__layer >= 9 && __layer <= 16)
  {
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
    if(__boxes > 0)
    {
      if(__boxes == 1)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), FALSE);

    if(__boxes > 1)
    {
      if(__boxes == 2)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), FALSE);

    if(__boxes > 2)
    {
      if(__boxes == 3)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), FALSE);

    if(__boxes > 3)
    {
      if(__boxes == 4)
      {
        if(RobotState())
        {
          if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3)))
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), FALSE);
          else
            BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), TRUE);
        }
        else
          BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), TRUE);
      }
      else
        BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), TRUE);
    }
    else
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), FALSE);

  }
  if(__layer > 16)
  {
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
    BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
  }
  BxUpdateView(hBox);
}

BX_BOOL formPedalBoxUserInit(HBOX hBox,BX_LPARAM lParam)
{
  GuidedByVision(FALSE);
  BxAssignStringValue(BxGetDlgItem(hBox, FORMPEDALBOX_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMPEDALBOX_TEXTLABEL2_2), GetRSType());

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSPEED));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSPEED), 100.0 * GetSpeedFactor());

  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS))->lpBoxStr = pbstr;
  BxProgressBar_Create(BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS), &pBxBar, BPB_VERTICAL);
  BxProgressBar_SetStep(BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS), 1);

  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS_2))->lpBoxStr = pbstr2;
  BxProgressBar_Create(BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS_2), &pBxBar2, BPB_VERTICAL);
  BxProgressBar_SetStep(BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS_2), 1);

  BxAssignFloatValue(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSPEED));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSPEED), 100.0 * GetSpeedFactor());

  BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDRUN), RobotState());

  CalcLayerAndBoxFromPath();
  SetupScreen(hBox);

  return TRUE;
}

BX_BOOL formPedalBoxUserUpdate(HBOX hBox)
{
  roboCheckForException(hBox);
  BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDRUN), RobotState());

  BxProgressBar_SetPos( BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS), ppos);
  BxProgressBar_Paint( BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS));
  BxUpdateView(BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS));

  BxProgressBar_SetPos( BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS_2), rpctpos);
  BxProgressBar_Paint( BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS_2));
  BxUpdateView(BxGetDlgItem(hBox, FORMPEDALBOX_LABPROGRESS_2));

  if(RobotState())
  {
    CalcLayerAndBoxFromPath();
    SetupScreen(hBox);
  }
  else
  {
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDMENU), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSET), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA4), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA5), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA6), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA7), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA8), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC4), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC5), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC6), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC7), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC8), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
  }

  return TRUE;
}

BX_BOOL formPedalBox_cmdMenu_Click(HBOX hBox)
{
  if(BxMsgBox(hBox, "Do you want to exit box palletizing?", "Attention.", 0)==IDOK)
  {
    BxEndDialog(hBox, IDOK);
  }
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxC0_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0))==TRUE)
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 1;
  }
  else
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxC2_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2))==TRUE)
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 3;
  }
  else
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 2;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxC1_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1))==TRUE)
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 2;
  }
  else
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 1;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxC3_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3))==TRUE)
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 4;
  }
  else
  {
    if(__layer > 8)
      __layer = 1;
    __boxes = 3;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC1_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC1))==TRUE)
  {
    __layer = 1;
    __boxes = 0;
  }
  else
  {
    __layer = 1;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC2_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC2))==TRUE)
  {
    __layer = 2;
    __boxes = 0;
  }
  else
  {
    __layer = 1;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC3_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC3))==TRUE)
  {
    __layer = 3;
    __boxes = 0;
  }
  else
  {
    __layer = 2;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC4_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC4))==TRUE)
  {
    __layer = 4;
    __boxes = 0;
  }
  else
  {
    __layer = 3;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC5_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC5))==TRUE)
  {
    __layer = 5;
    __boxes = 0;
  }
  else
  {
    __layer = 4;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC6_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC6))==TRUE)
  {
    __layer = 6;
    __boxes = 0;
  }
  else
  {
    __layer = 5;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC7_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC7))==TRUE)
  {
    __layer = 7;
    __boxes = 0;
  }
  else
  {
    __layer = 6;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerC8_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC8))==TRUE)
  {
    __layer = 8;
    __boxes = 0;
  }
  else
  {
    __layer = 7;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA6_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA6))==TRUE)
  {
    __layer = 14;
    __boxes = 0;
  }
  else
  {
    __layer = 13;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA2_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA2))==TRUE)
  {
    __layer = 10;
    __boxes = 0;
  }
  else
  {
    __layer = 9;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA5_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA5))==TRUE)
  {
    __layer = 13;
    __boxes = 0;
  }
  else
  {
    __layer = 12;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA1_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA1))==TRUE)
  {
    __layer = 9;
    __boxes = 0;
  }
  else
  {
    __layer = 9;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA8_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA8))==TRUE)
  {
    __layer = 16;
    __boxes = 0;
  }
  else
  {
    __layer = 15;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA3_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA3))==TRUE)
  {
    __layer = 11;
    __boxes = 0;
  }
  else
  {
    __layer = 10;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA7_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA7))==TRUE)
  {
    __layer = 15;
    __boxes = 0;
  }
  else
  {
    __layer = 14;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdLayerA4_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA4))==TRUE)
  {
    __layer = 12;
    __boxes = 0;
  }
  else
  {
    __layer = 11;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxA3_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3))==TRUE)
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 4;
  }
  else
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 3;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxA2_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2))==TRUE)
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 3;
  }
  else
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 2;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxA1_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1))==TRUE)
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 2;
  }
  else
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 1;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdBoxA0_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0))==TRUE)
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 1;
  }
  else
  {
    if(__layer < 9)
      __layer = 9;
    __boxes = 0;
  }
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdSpeed_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSPEED)));
  BxVirtNumBox_SetFloatLimits(1.0, 100.0);

  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSPEED), BxVirtNumBox_GetFloatValue());
    SetSpeedFactor(BxVirtNumBox_GetFloatValue()/100.0);
  }
  return TRUE;
}

BX_BOOL formPedalBox_cmdSet_Click(HBOX hBox)
{
  SetCurrentPathNum(((__layer-1)*4)+__boxes);
  SetupScreen(hBox);
  return TRUE;
}

BX_BOOL formPedalBox_cmdRun_Click(HBOX hBox)
{
  BX_CHAR msgstr[256];
  
  BxSendMessage(BxGetDlgItem(hBox, FORMPEDALBOX_CMDRUN), BM_PAINT, 0, 0);
  BxUpdateView(BxGetDlgItem(hBox, FORMPEDALBOX_CMDRUN));
  if(BxGetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDRUN))==TRUE)
  {
    CalcLayerAndBoxFromPath();
    sprintf(msgstr,"Pallet %s, layer %d, box %d, Start?", __layer < 9 ? "C" : "A", __layer < 9 ? __layer : __layer - 8, __boxes);
    if(BxMsgBox(hBox, msgstr, "Next box is:", 0)==IDOK)
    {
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDMENU), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA1), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA2), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA3), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA4), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA5), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA6), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA7), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA8), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC1), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC2), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC3), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC4), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC5), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC6), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC7), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC8), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), FALSE);
      BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSET), FALSE);
      GoRobot(TRUE);
    }
    else
    {
      BxSetCheck(BxGetDlgItem(hBox, FORMPEDALBOX_CMDRUN), FALSE);
    }
  }
  else
  {
    GoRobot(FALSE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDSET), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA4), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA5), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA6), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA7), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERA8), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA0), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXA3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC4), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC5), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC6), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC7), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDLAYERC8), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC0), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC1), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC2), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDBOXC3), TRUE);
    BxEnableBox(BxGetDlgItem(hBox, FORMPEDALBOX_CMDMENU), TRUE);
  }
  return TRUE;
}
