//Code generated by bxbuilder (c) LMS 2002 
// formSetIOUser.c
#include "Bx.h"
#include "formSetIO.h"

#include "rs.h"

BX_BOOL formSetIOUserUpdate(HBOX hBox)
{
  unsigned val;
  val = (unsigned)GetInput();
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_1), val & 0x00000001 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_2), val & 0x00000002 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_3), val & 0x00000004 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_4), val & 0x00000008 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_5), val & 0x00000010 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_6), val & 0x00000020 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_7), val & 0x00000040 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_8), val & 0x00000080 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_9), val & 0x00000100 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_10), val & 0x00000200 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_11), val & 0x00000400 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_12), val & 0x00000800 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_13), val & 0x00001000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_14), val & 0x00002000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_15), val & 0x00004000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_16), val & 0x00008000 ? TRUE : FALSE);
	/*  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_17), val & 0x00010000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_18), val & 0x00020000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_19), val & 0x00040000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_20), val & 0x00080000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_21), val & 0x00100000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_22), val & 0x00200000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_23), val & 0x00400000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_24), val & 0x00800000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_25), val & 0x01000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_26), val & 0x02000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_27), val & 0x04000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_28), val & 0x08000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_29), val & 0x10000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_30), val & 0x20000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_31), val & 0x40000000 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_32), val & 0x80000000 ? TRUE : FALSE);
	*/
 return TRUE;
}

BX_BOOL formSetIOUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_TEXTLABEL2_2), GetRSType());
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CMDRETURN));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CMDRETURN), getLanguageLineFromIdx(langptr, 5, "Return"));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_1));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_1), getLanguageLineFromIdx(langptr, 58, "i0:  Box-test photo1      "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_2), getLanguageLineFromIdx(langptr, 59, "i1:   Emergency stop      "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_3));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_3), getLanguageLineFromIdx(langptr, 60, "i2:    Crash sensor       "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_4));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_4), getLanguageLineFromIdx(langptr, 61, "i3: Box support readswitch"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_5));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_5), getLanguageLineFromIdx(langptr, 62, "i4:  Box-test photo2      "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_6));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_6), getLanguageLineFromIdx(langptr, 63, "i5:    Home sensor B      "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_7));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_7), getLanguageLineFromIdx(langptr, 64, "i6:    Home sensor C      "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_8));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_8), getLanguageLineFromIdx(langptr, 65, "i7: Doublebox test photo  "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_9));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_9), getLanguageLineFromIdx(langptr, 66,"io8:   avail. "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_10));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_10), getLanguageLineFromIdx(langptr, 67,"io9:   avail. "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_11));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_11), getLanguageLineFromIdx(langptr, 68,"io10: Box support"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_12));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_12), getLanguageLineFromIdx(langptr, 69,"io11:  Grip tool "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_13));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_13), getLanguageLineFromIdx(langptr, 70,"io12:  avail. "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_14));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_14), getLanguageLineFromIdx(langptr, 71,"io13:  avail. "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_15));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_15), getLanguageLineFromIdx(langptr, 72,"io14:  avail. "));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_16));
  BxSetStringValue(BxGetDlgItem(hBox, FORMSETIO_CHECK_16), getLanguageLineFromIdx(langptr, 73,"io15:  avail. "));

  formSetIOUserUpdate(hBox);
  return TRUE;
}

BX_BOOL formSetIO_check_2_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_check_3_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_check_4_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_check_5_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_check_6_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_check_7_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_check_8_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetIO_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, TRUE);
  return FALSE;
}

BX_BOOL formSetIO_check_12_Click(HBOX hBox)
{
  SetOutput(11, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_12)));
  return TRUE;
}

BX_BOOL formSetIO_check_10_Click(HBOX hBox)
{
  SetOutput(9, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_10)));
  return TRUE;
}

BX_BOOL formSetIO_check_11_Click(HBOX hBox)
{
  SetOutput(10, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_11)));
  return TRUE;
}

BX_BOOL formSetIO_check_9_Click(HBOX hBox)
{
  SetOutput(8, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_9)));
  return TRUE;
}

/* BX_BOOL formSetIO_check_18_Click(HBOX hBox) */
/* { */
/*   SetOutput(17, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_18))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_19_Click(HBOX hBox) */
/* { */
/*   SetOutput(18, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_19))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_20_Click(HBOX hBox) */
/* { */
/*   SetOutput(19, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_20))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_21_Click(HBOX hBox) */
/* { */
/*   SetOutput(20, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_21))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_22_Click(HBOX hBox) */
/* { */
/*   SetOutput(21, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_22))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_23_Click(HBOX hBox) */
/* { */
/*   SetOutput(22, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_23))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_24_Click(HBOX hBox) */
/* { */
/*   SetOutput(23, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_24))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_25_Click(HBOX hBox) */
/* { */
/*   SetOutput(24, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_25))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_26_Click(HBOX hBox) */
/* { */
/*   SetOutput(25, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_26))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_27_Click(HBOX hBox) */
/* { */
/*   SetOutput(26, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_27))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_28_Click(HBOX hBox) */
/* { */
/*   SetOutput(27, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_28))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_29_Click(HBOX hBox) */
/* { */
/*   SetOutput(28, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_29))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_30_Click(HBOX hBox) */
/* { */
/*   SetOutput(29, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_30))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_31_Click(HBOX hBox) */
/* { */
/*   SetOutput(30, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_31))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_32_Click(HBOX hBox) */
/* { */
/*   SetOutput(31, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_32))); */
/*   return TRUE; */
/* } */

/* BX_BOOL formSetIO_check_17_Click(HBOX hBox) */
/* { */
/*   SetOutput(16, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_17))); */
/*   return TRUE; */
/* } */

BX_BOOL formSetIO_check_16_Click(HBOX hBox)
{
  SetOutput(15, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_16)));
  return TRUE;
}

BX_BOOL formSetIO_check_15_Click(HBOX hBox)
{
  SetOutput(14, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_15)));
  return TRUE;
}

BX_BOOL formSetIO_check_14_Click(HBOX hBox)
{
  SetOutput(13, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_14)));
  return TRUE;
}

BX_BOOL formSetIO_check_13_Click(HBOX hBox)
{
  SetOutput(12, BxGetCheck(BxGetDlgItem(hBox, FORMSETIO_CHECK_13)));
  return TRUE;
}

BX_BOOL formSetIO_check_1_Click(HBOX hBox)
{
  return TRUE;
}

