//Code generated by bxbuilder (c) LMS 2002 
// formStatus.c
#include "Bx.h"
#include "formStatus.h"

BOXSTRUCT formStatus[] = {
 {10000,{0,0,799,599},DIALOG,"",BXS_VISIBLE,&formStatus[1], NULL}
 ,{FORMSTATUS_TEXTLABEL2_2,{20,10,129,44},STATIC,"Stat",BXS_VISIBLE,&formStatus[2], &formStatus[0]}
 ,{FORMSTATUS_CMDCLOSE,{650,480,779,579},BUTTON,"Close",BBS_PUSHBUTTON|BXS_VISIBLE,&formStatus[3], &formStatus[0]}
 ,{FORMSTATUS_GROUPBOX2,{20,60,359,299},STATIC,"Box",BSS_WHITEFRAME|BXS_VISIBLE,&formStatus[4], &formStatus[0]}
 ,{FORMSTATUS_LAB,{39,110,78,159},STATIC,"Fill",BXS_VISIBLE,&formStatus[5], &formStatus[0]}
 ,{FORMSTATUS_LAB_2,{39,170,108,219},STATIC,"Move",BXS_VISIBLE,&formStatus[6], &formStatus[0]}
 ,{FORMSTATUS_LAB_2_2,{39,230,118,279},STATIC,"Reject",BXS_VISIBLE,&formStatus[7], &formStatus[0]}
 ,{FORMSTATUS_LABFILL,{170,110,349,159},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[8], &formStatus[0]}
 ,{FORMSTATUS_LABMOVE,{170,170,349,219},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[9], &formStatus[0]}
 ,{FORMSTATUS_LABREJECT,{170,230,349,279},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[10], &formStatus[0]}
 ,{FORMSTATUS_GROUPBOX3,{20,320,360,550},STATIC,"Vacuum",BSS_WHITEFRAME|BXS_VISIBLE,&formStatus[11], &formStatus[0]}
 ,{FORMSTATUS_LAB_3,{40,470,139,519},STATIC,"Dropped",BXS_VISIBLE,&formStatus[12], &formStatus[0]}
 ,{FORMSTATUS_LAB_2_2_3,{40,420,99,469},STATIC,"Loss",BXS_VISIBLE,&formStatus[13], &formStatus[0]}
 ,{FORMSTATUS_LAB_2_2_2,{40,360,99,409},STATIC,"Error",BXS_VISIBLE,&formStatus[14], &formStatus[0]}
 ,{FORMSTATUS_LABERROR,{170,350,349,399},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[15], &formStatus[0]}
 ,{FORMSTATUS_LABLOSS,{170,410,349,459},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[16], &formStatus[0]}
 ,{FORMSTATUS_LABDROPPED,{170,470,349,519},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[17], &formStatus[0]}
 ,{FORMSTATUS_GROUPBOX4,{380,41,780,460},STATIC,"Wait",BSS_WHITEFRAME|BXS_VISIBLE,&formStatus[18], &formStatus[0]}
 ,{FORMSTATUS_LAB_3_2,{400,341,460,390},STATIC,"Box",BXS_VISIBLE,&formStatus[19], &formStatus[0]}
 ,{FORMSTATUS_LABPALLET,{590,201,769,250},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[20], &formStatus[0]}
 ,{FORMSTATUS_LABTOTALTM,{590,401,769,450},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[21], &formStatus[0]}
 ,{FORMSTATUS_LABBOX,{590,331,769,380},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[22], &formStatus[0]}
 ,{FORMSTATUS_LAB_3_2_3,{400,401,489,450},STATIC,"Total",BXS_VISIBLE,&formStatus[23], &formStatus[0]}
 ,{FORMSTATUS_LAB_3_2_2_2_2_2,{400,271,539,320},STATIC,"Box release",BXS_VISIBLE,&formStatus[24], &formStatus[0]}
 ,{FORMSTATUS_LABBOXREL,{590,261,769,310},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[25], &formStatus[0]}
 ,{FORMSTATUS_LAB_3_2_2,{400,81,569,130},STATIC,"Product (total)",BXS_VISIBLE,&formStatus[26], &formStatus[0]}
 ,{FORMSTATUS_LABTOTAL,{590,81,769,130},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[27], &formStatus[0]}
 ,{FORMSTATUS_LAB2SEC,{590,141,769,190},STATIC,"0",BXS_BORDER|BSS_RIGHT|BXS_VISIBLE,&formStatus[28], &formStatus[0]}
 ,{FORMSTATUS_LAB_3_2_2_2,{400,141,579,190},STATIC,"Product (>2sec.)",BXS_VISIBLE,&formStatus[29], &formStatus[0]}
 ,{FORMSTATUS_LAB_3_2_2_2_2,{400,201,469,250},STATIC,"Pallet",BXS_VISIBLE,&formStatus[30], &formStatus[0]}
 ,{BXID_STATIC,{0,0,0,0},STATIC,"",0,NULL, &formStatus[0]}
};

BX_BOOL formStatusProc(HBOX hBox, BX_UINT uMsg	,BX_WPARAM wParam, BX_LPARAM lParam)
{
 switch(uMsg)
	{
		case BM_UPDATE:
			{
				formStatusUpdate(hBox);
				return formStatusUserUpdate(hBox);
				break;
			}
		case BM_INITDIALOG:
			{
				formStatusInit(hBox);
				return formStatusUserInit(hBox,lParam);
				break;
			}
		case BM_COMMAND:
			{
				switch(BX_LOWORD(wParam))
				{
         case FORMSTATUS_CMDCLOSE:
             return formStatus_cmdClose_Click(hBox);
				}
				break;
			}
		default:
			return(DefBoxProc(hBox,uMsg,wParam,lParam));
	}
	return 0L;
}
