//Code generated by bxbuilder (c) LMS 2002 
// formUploadProgUser.c
#include "Bx.h"
#include "formUploadProg.h"

#include "tmclnx.h"
#include "rs.h"

static BXPROGRESSBARSTRUCT BxProgBar;
char pbstr[256];

BX_BOOL formUploadProgUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMUPLOADPROG_TEXTLABEL2_2));
  BxSetStringValue(BxGetDlgItem(hBox, FORMUPLOADPROG_TEXTLABEL2_2), GetRSType());
  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMUPLOADPROG_LABPROGRESS))->lpBoxStr = pbstr;
  BxProgressBar_Create(BxGetDlgItem(hBox, FORMUPLOADPROG_LABPROGRESS), &BxProgBar, BPB_HORIZONTAL);
  return TRUE;
}

BX_BOOL formUploadProgUserUpdate(HBOX hBox)
{
 return TRUE;
}

void StepFunc(HBOX hBx)
{
  BxProgressBar_StepIt( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS));
  BxProgressBar_Paint( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS));
  BxUpdateView(BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS));
}

void SetStepPosFunc(HBOX hBx, int pos)
{
  BxProgressBar_SetPos( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS), pos);
  BxProgressBar_Paint( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS));
  BxUpdateView(BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS));
}

int GetStepPosFunc(HBOX hBx)
{
  return BxProgressBar_GetPos( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS));
}

void SetupProgressBar(HBOX hBx, int steps)
{
  BxProgressBar_SetStep( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS), 100/steps );
}

void EndProgressBar(HBOX hBx)
{
  BxProgressBar_SetPos( BxGetDlgItem(hBx, FORMUPLOADPROG_LABPROGRESS), 100 );
}
