//Code generated by bxbuilder (c) LMS 2002 
// formDistIOUser.c
#include "Bx.h"
#include "formDistIO.h"
#include "formDDI3725Mod.h"
#include "formEPIMod.h"
#include "formEHCMod.h"
#include "formAVIMod.h"
#include "formAVOMod.h"
#include "formLoadCell.h"
#include "formComSK.h"
#include "formMac.h"
#include "formICPcon.h"

#include "cmd.h"

volatile int dioIndex=0;
volatile int modIndex=0;

BX_BOOL update(HBOX hBox)
{
  int i,j;

  //empty list
  int maxCount = BxList_GetCount(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX));
  for(i=0; i<maxCount; i++){
    BxList_DeleteString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX),0);
  }
  
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKADVANTYS)))
  {
    for(i=0;i<tworkcell->dios.maxidx;i++)
    {
      for(j=0;j<tworkcell->dios.dio[i].numOfModules;j++)
      {
        switch(tworkcell->dios.dio[i].iotab[j].type)
        {
        case STBEHC3020:
        case STBDDI3420:
        case STBDDI3610:
        case STBDDO3600:
        case STBEPI2145:
        case STBAVI1270:
        case STBAVO1250:
        case STBDDI3725:
        case STBDDO3705:
          {
            char s[256*3];
            sprintf(s,"Adv. %s %s %s",
                    tworkcell->dios.dio[i].iotab[j].module_name,
                    tworkcell->dios.dio[i].iotab[j].typeStr,
                    tworkcell->dios.dio[i].ipaddr);
            BxList_AddString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX), s);
          }
          break;
        }
      }
    }
  }
  
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKLOADCELL)))
  {
    for(i=0;i<tworkcell->loadcells.maxidx;i++)
    {
      /*
        char s[256*3];
        sprintf(s,"LoadCell %s %s 0.4%f",
                tworkcell->loadcells.loadcell[i].ipaddr,
                tworkcell->loadcells.loadcell[i].iotab[j].key,
                tworkcell->loadcells.loadcell[i].iotab[j].fdata
                );
        BxList_AddString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX), s);
      */
        char s[256];
        sprintf(s, "LoadCell %s", tworkcell->loadcells.loadcell[i].ipaddr);
        BxList_AddString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX), s);
    }
  }
  
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKCOMSK)))
  {
    for(i=0; i<tworkcell->comsks.maxidx; i++)
    {
      for(j=0;j<tworkcell->comsks.comsk[i].numOfModules;j++)
      {
        char s[256*2];
        sprintf(s, "ComSK %s %s", 
								tworkcell->comsks.comsk[i].iotab[j].module_name,
                tworkcell->comsks.comsk[i].ipaddr);
        BxList_AddString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX), s);
      }
    }
  }
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKMAC)))
  {
    for(i=0; i<tworkcell->macs.maxidx; i++)
    {
      for(j=0;j<tworkcell->macs.mac[i].numOfMotors;j++)
      {
        char s[256*2];
        sprintf(s, "Mac %s %s", 
								tworkcell->macs.mac[i].iotab[j].module_name,
                tworkcell->macs.mac[i].ipaddr);
        BxList_AddString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX), s);
      }
    }
  }
	if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKICPCON)))
  {
    for(i=0; i<tworkcell->icpcons.maxidx; i++)
    {
      for(j=0;j<tworkcell->icpcons.icpcon[i].numOfModules;j++)
      {
        char s[256*2];
        sprintf(s, "ICPcon %s %s", 
								tworkcell->icpcons.icpcon[i].iotab[j].module_name,
                tworkcell->icpcons.icpcon[i].ipaddr);
        BxList_AddString(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX), s);
      }
    }
  }
  return TRUE;
}

BX_BOOL formDistIOUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	BxSetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKADVANTYS), 1);
  BxSetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKLOADCELL), 1);
  BxSetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKCOMSK), 1);
	BxSetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKMAC), 1);
	BxSetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKICPCON), 1);

	BxAssignStringValue(BxGetDlgItem(hBox, FORMDISTIO_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDISTIO_CMDCLOSE), getLanguageLineFromIdx(langptr, 54, "Close"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMDISTIO_TEXTLABEL2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDISTIO_TEXTLABEL2_2), getLanguageLineFromIdx(langptr, 53, "Modules"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMDISTIO_CHKADVANTYS));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDISTIO_CHKADVANTYS), getLanguageLineFromIdx(langptr, 55, "Advantys"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMDISTIO_CHKLOADCELL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDISTIO_CHKLOADCELL), getLanguageLineFromIdx(langptr, 56, "LoadCell"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMDISTIO_CHKCOMSK));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDISTIO_CHKCOMSK), getLanguageLineFromIdx(langptr, 57, "ComSK"));
  return update(hBox);
}

BX_BOOL formDistIOUserUpdate(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formDistIO_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formDistIO_listBox_Click(HBOX hBox)
{
  HBOX hBx=NULL;
  int sel = BxList_GetSelected(BxGetDlgItem(hBox, FORMDISTIO_LISTBOX));
  int i;
  int dioStartIndex=0;
  int dioSelected=0;
  int loadcellSelected=0;
  int comSKSelected=0;
	int macSelected=0;
	int ICPconSelected=0;
	
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKADVANTYS)))
  {
  	for(i=0;i<tworkcell->dios.maxidx;i++)
    {
      if(dioStartIndex <= sel && sel < dioStartIndex + tworkcell->dios.dio[i].numOfModules)
      {
        dioIndex = i;
        modIndex = sel - dioStartIndex;
        dioSelected = 1;
      }
      dioStartIndex += tworkcell->dios.dio[i].numOfModules;
    }
  }

  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKLOADCELL)))
  {
    if(dioStartIndex <= sel && sel < dioStartIndex + tworkcell->loadcells.maxidx)
    {
      modIndex = sel - dioStartIndex;
      loadcellSelected = 1;
    }
    dioStartIndex += tworkcell->loadcells.maxidx;
  }
  
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKCOMSK)))
  {
    for(i=0; i<tworkcell->comsks.maxidx; i++)
    {
  	  if(dioStartIndex <= sel && sel < dioStartIndex + tworkcell->comsks.comsk[i].numOfModules)
  	  {
        dioIndex = i;
  	    modIndex = sel - dioStartIndex;
  	    comSKSelected = 1;
  	  }
  	  dioStartIndex += tworkcell->comsks.comsk[i].numOfModules;
    }
  }
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKMAC)))
  {
    for(i=0; i<tworkcell->macs.maxidx; i++)
    {
  	  if(dioStartIndex <= sel && sel < dioStartIndex + tworkcell->macs.mac[i].numOfMotors)
  	  {
        dioIndex = i;
  	    modIndex = sel - dioStartIndex;
  	    macSelected = 1;
  	  }
  	  dioStartIndex += tworkcell->macs.mac[i].numOfMotors;
    }
  }
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDISTIO_CHKICPCON)))
  {
    for(i=0; i<tworkcell->icpcons.maxidx; i++)
    {
  	  if(dioStartIndex <= sel && sel < dioStartIndex + tworkcell->icpcons.icpcon[i].numOfModules)
  	  {
        dioIndex = i;
  	    modIndex = sel - dioStartIndex;
  	    ICPconSelected = 1;
  	  }
  	  dioStartIndex += tworkcell->icpcons.icpcon[i].numOfModules;
    }
  }
  if(dioSelected){
    switch(tworkcell->dios.dio[dioIndex].iotab[modIndex].type)
    {
    case STBEHC3020:
      hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEHCMod[0], formEHCModProc);
      break;
    case STBDDI3420:
    case STBDDI3725:
    case STBDDI3610:
    case STBDDO3705:
    case STBDDO3600:
      hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formDDI3725Mod[0], formDDI3725ModProc);
      break;
    case STBEPI2145:
      hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formEPIMod[0], formEPIModProc);
      break;
    case STBAVI1270:
      hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formAVIMod[0], formAVIModProc);
      break;
    case STBAVO1250:
      hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formAVOMod[0], formAVOModProc);
      break;
    }
  }
	else if(loadcellSelected)
	{
    hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formLoadCell[0], formLoadCellProc);
  }
	else if(comSKSelected)
	{
    hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formComSK[0], formComSKProc);
  }
	else if(macSelected)
	{
    hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formMac[0], formMacProc);
  }
	else if(ICPconSelected)
	{
    hBx = BxCreateDialog(((BOXSTRUCT *)hBox)->hInstance, &formICPcon[0], formICPconProc);
  }
	DoModal(hBx);
	return TRUE;
}

BX_BOOL formDistIO_chkAdvantys_Click(HBOX hBox)
{
  return update(hBox);
}

BX_BOOL formDistIO_chkLoadCell_Click(HBOX hBox)
{
  return update(hBox);
}

BX_BOOL formDistIO_chkComSK_Click(HBOX hBox)
{
  return update(hBox);
}

BX_BOOL formDistIO_chkMac_Click(HBOX hBox)
{
  return update(hBox);
}

BX_BOOL formDistIO_chkICPcon_Click(HBOX hBox)
{
  return update(hBox);
}
