//Code generated by bxbuilder (c) LMS 2002 
// formLoggerUser.c
#include "Bx.h"
#include "formLogger.h"
#include "rs.h"

static BX_VOID setupList(HBOX hBox)
{
  BX_CHAR cmd[256];
  FILE *fp;
  char filename[512];  
  while(BxList_GetCount(BxGetDlgItem(hBox, FORMLOGGER_LISTBOX))>0)
    BxList_DeleteString(BxGetDlgItem(hBox, FORMLOGGER_LISTBOX), 0);

  sprintf(filename,"%s/system/rs.log",rs_systempath);
  fp = fopen(filename, "r");
  if(fp==NULL)
    return;
    
  while(!feof(fp))
  {
    fgets(cmd, 255, fp);
    cmd[strlen(cmd)-1] = '\0';
    BxList_AddString(BxGetDlgItem(hBox, FORMLOGGER_LISTBOX), cmd);
  }
  fclose(fp);
}


BX_BOOL formLoggerUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	
	BxAssignStringValue(BxGetDlgItem(hBox, FORMLOGGER_CMDMENU));
	BxSetStringValue(BxGetDlgItem(hBox, FORMLOGGER_CMDMENU), getLanguageLineFromIdx(langptr, 54, "Close"));
  setupList(hBox);
  return TRUE;
}

BX_BOOL formLoggerUserUpdate(HBOX hBox)
{
//  setupList(hBox);
  return TRUE;
}

BX_BOOL formLogger_listBox_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formLogger_cmdMenu_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);
  return TRUE;
}

