//Code generated by bxbuilder (c) LMS 2002 
// formSysParamUser.c
#include "Bx.h"
#include "formSysParam.h"

#include "rs.h"
#include "cmd.h"

BX_BOOL formSysParamUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	

	BxAssignStringValue(BxGetDlgItem(hBox, FORMSYSPARAM_TEXTLABEL2_4));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSYSPARAM_TEXTLABEL2_4), getLanguageLineFromIdx(langptr, 83, "Old ethernet version"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSYSPARAM_CMDRETURN));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSYSPARAM_CMDRETURN), getLanguageLineFromIdx(langptr, 74, "Ok"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSYSPARAM_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSYSPARAM_CMDCANCEL), getLanguageLineFromIdx(langptr, 3, "Cancel"));
 //BxSetCheck(BxGetDlgItem(hBox, FORMSYSPARAM_CHECKETHERNETVERSION), rs_param.new_trio_ether_version);
 return TRUE;
}

BX_BOOL formSysParamUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formSysParam_checkEthernetVersion_Click(HBOX hBox)
{
  //rs_param.new_trio_ether_version = BxGetCheck(BxGetDlgItem(hBox, FORMSYSPARAM_CHECKETHERNETVERSION));
  return TRUE;
}

BX_BOOL formSysParam_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);
  return TRUE;
}

BX_BOOL formSysParam_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDCANCEL);
  return TRUE;
}

