//Code generated by bxbuilder (c) LMS 2002 
// formSetDebugUser.c
#include "Bx.h"
#include "formSetDebug.h"

#include "rs.h"

BX_BOOL formSetDebugUserInit(HBOX hBox,BX_LPARAM lParam)
{
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];
	
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_CMDOK));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_CMDOK), getLanguageLineFromIdx(langptr, 74, "Ok"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_CMDCANCEL));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_CMDCANCEL), getLanguageLineFromIdx(langptr, 3, "Cancel"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_TEXTLABEL2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_TEXTLABEL2_2), getLanguageLineFromIdx(langptr, 239, "Debug settings"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB), getLanguageLineFromIdx(langptr, 240, "With products"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2), getLanguageLineFromIdx(langptr, 241, "With pallet"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2_2_2), getLanguageLineFromIdx(langptr, 242, "Loop mode"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2_2), getLanguageLineFromIdx(langptr, 243, "With box"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2_2_3));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_2_2_3), getLanguageLineFromIdx(langptr, 244, "With reject"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3), getLanguageLineFromIdx(langptr, 245, "Simulate"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3_2), getLanguageLineFromIdx(langptr, 246, "Reset status"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3_2_2), getLanguageLineFromIdx(langptr, 247, "Reset current limits"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3_2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMSETDEBUG_LAB_3_2_2_2), getLanguageLineFromIdx(langptr, 248, "Reset follow error"));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKLOOP), GetVR(801));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHPRODUCT), GetVR(803));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHBOX), GetVR(804));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHPALLET), GetVR(802));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHREJECT), GetVR(805));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKONLINE), GetVR(1023));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKRESETSTAT), GetVR(734));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKRESETCURRENT), GetVR(735));
  BxSetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKRESETFOLLOWERR), GetVR(736));
  return TRUE;
}

BX_BOOL formSetDebugUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formSetDebug_cmdOk_Click(HBOX hBox)
{
  SetVR(801, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKLOOP)));
  SetVR(803, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHPRODUCT)));
  SetVR(804, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHBOX)));
  SetVR(802, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHPALLET)));
  SetVR(805, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKWITHREJECT)));
  SetVR(1023, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKONLINE)));
  SetVR(734, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKRESETSTAT)));
  SetVR(735, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKRESETCURRENT)));
  SetVR(736, BxGetCheck(BxGetDlgItem(hBox, FORMSETDEBUG_CHKRESETFOLLOWERR)));
  BxEndDialog(hBox, TRUE);
  return FALSE;
}

BX_BOOL formSetDebug_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, FALSE);
  return FALSE;
}

BX_BOOL formSetDebug_chkLoop_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkWithPallet_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkWithProduct_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkWithBox_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkOnline_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkWithReject_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkResetStat_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkResetCurrent_Click(HBOX hBox)
{
  return TRUE;
}

BX_BOOL formSetDebug_chkResetFollowErr_Click(HBOX hBox)
{
  return TRUE;
}

