//Code generated by bxbuilder (c) LMS 2002 
// formDDOModUser.c
#include "Bx.h"
#include "formDDOMod.h"
#include "cmd.h"

extern volatile int modIndex;
char namestr[256]="Name :";

BX_BOOL formDDOModUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABTYPE));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABMODNAME));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT1));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT2));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT3));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT4));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT5));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT6));
	tmpnLanguage *langptr=(tmpnLanguage*)&tworkcell->languages.language[tworkcell->languages.currentLanguage];	
	BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_CMDCLOSE));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_CMDCLOSE), getLanguageLineFromIdx(langptr, 54, "Close"));
	sprintf(namestr,"%s :",getLanguageLineFromIdx(langptr, 87, "Name"));
	BxAssignStringValue(BxGetDlgItem(hBox, FORMDDOMOD_TEXTLABEL2_2_2));
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_TEXTLABEL2_2_2), namestr);
	
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABTYPE), "DDO3600");
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABMODNAME), tworkcell->dios.dio[0].iotab[modIndex].module_name);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT1), tworkcell->dios.dio[0].iotab[modIndex].connect[0].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT2), tworkcell->dios.dio[0].iotab[modIndex].connect[1].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT3), tworkcell->dios.dio[0].iotab[modIndex].connect[2].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT4), tworkcell->dios.dio[0].iotab[modIndex].connect[3].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT5), tworkcell->dios.dio[0].iotab[modIndex].connect[4].key);
	BxSetStringValue(BxGetDlgItem(hBox, FORMDDOMOD_LABCONNECT6), tworkcell->dios.dio[0].iotab[modIndex].connect[5].key);
  
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE1), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0001 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE2), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0002 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE3), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0004 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE4), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0008 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE5), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0010 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE6), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0020 ? TRUE : FALSE);
	
 return TRUE;
}

BX_BOOL formDDOModUserUpdate(HBOX hBox)
{
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE1), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0001 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE2), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0002 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE3), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0004 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE4), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0008 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE5), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0010 ? TRUE : FALSE);
  BxSetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE6), tworkcell->dios.dio[0].iotab[modIndex].idata[0] & 0x0020 ? TRUE : FALSE);
	
 return TRUE;
}

BX_BOOL formDDOMod_cmdClose_Click(HBOX hBox)
{
  BxEndDialog(hBox, 0);
  return TRUE;
}

BX_BOOL formDDOMod_chkState2_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE2))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] |= 0x02;
	else
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] &= 0xFD;
  return TRUE;
}

BX_BOOL formDDOMod_chkState3_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE3))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] |= 0x04;
	else
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] &= 0xFB;
  return TRUE;
}

BX_BOOL formDDOMod_chkState4_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE4))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] |= 0x08;
	else
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] &= 0xF7;
  return TRUE;
}

BX_BOOL formDDOMod_chkState5_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE5))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] |= 0x10;
	else
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] &= 0xEF;
  return TRUE;
}

BX_BOOL formDDOMod_chkState6_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE6))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] |= 0x20;
	else
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] &= 0xDF;
  return TRUE;
}

BX_BOOL formDDOMod_chkState1_Click(HBOX hBox)
{
  if(BxGetCheck(BxGetDlgItem(hBox, FORMDDOMOD_CHKSTATE1))==TRUE)
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] |= 0x01;
	else
    tworkcell->dios.dio[0].iotab[modIndex].odata[0] &= 0xFE;
  return TRUE;
}
