//Code generated by bxbuilder (c) LMS 2002 
// formUploadProgUser.h

extern BX_BOOL formUploadProgUserInit(HBOX hBox,BX_LPARAM lParam);
extern BX_BOOL formUploadProgUserUpdate(HBOX hBox);
extern void StepFunc(HBOX hBx);
extern void SetStepPosFunc(HBOX hBx, int pos);
extern int GetStepPosFunc(HBOX hBx);
extern void SetupProgressBar(HBOX hBx, int steps);
extern void EndProgressBar(HBOX hBx);
