//Copyright (C) 2005 by MPN A/S - Guided by vision(R)
// formEditCPPattern.h
#if !defined(FORMEDITCPPATTERN_H)
#define FORMEDITCPPATTERN_H
#include "Bx.h"
#include "formEditCPPatternUser.h"
#define FORMEDITCPPATTERN_CMDCANCEL 1
extern BX_BOOL formEditCPPattern_cmdCancel_Click(HBOX hBox);
#define FORMEDITCPPATTERN_TEXTLABELMAXPUSH 2
#define FORMEDITCPPATTERN_CMDMAXPUSH 3
extern BX_BOOL formEditCPPattern_cmdMaxpush_Click(HBOX hBox);
#define FORMEDITCPPATTERN_TEXTLABELGETTIME 4
#define FORMEDITCPPATTERN_CMDGETTIME 5
extern BX_BOOL formEditCPPattern_cmdGettime_Click(HBOX hBox);
#define FORMEDITCPPATTERN_CMDSAVE 6
extern BX_BOOL formEditCPPattern_cmdSave_Click(HBOX hBox);
#define FORMEDITCPPATTERN_TEXTLABELPPP 7
#define FORMEDITCPPATTERN_LISTBOXPPP 8
extern BX_BOOL formEditCPPattern_listBoxPPP_Click(HBOX hBox);
#define FORMEDITCPPATTERN_GROUPBOXNAME 9
#define FORMEDITCPPATTERN_TEXTLABELCNAME 10
#define FORMEDITCPPATTERN_GROUPBOXLAYERIDX 11
#define FORMEDITCPPATTERN_TEXTLABELLAYERIDX 12
#define FORMEDITCPPATTERN_GROUPBOXPPPIDX 13
#define FORMEDITCPPATTERN_TEXTLABELPPPIDX 14
#define FORMEDITCPPATTERN_GROUPBOXPRODUCTCOUNT 15
#define FORMEDITCPPATTERN_TEXTLABELPRODUCTCOUNT 16
#define FORMEDITCPPATTERN_TEXTLABELMAXLAYERS 17
#define FORMEDITCPPATTERN_CMDLAYER 18
extern BX_BOOL formEditCPPattern_cmdLayer_Click(HBOX hBox);
#define FORMEDITCPPATTERN_CMDNEXTLAYER 19
extern BX_BOOL formEditCPPattern_cmdNextLayer_Click(HBOX hBox);
#define FORMEDITCPPATTERN_TEXTLABELLAYER 20
#define FORMEDITCPPATTERN_CMDPREVLAYER 21
extern BX_BOOL formEditCPPattern_cmdPrevLayer_Click(HBOX hBox);
#define FORMEDITCPPATTERN_CMDMAXLAYERS 22
extern BX_BOOL formEditCPPattern_cmdMaxLayers_Click(HBOX hBox);
extern BX_CHAR formEditCPPatternText[][MAXLANGUAGE][255];
extern BOXSTRUCT formEditCPPattern[];
extern BX_BOOL formEditCPPatternProc(HBOX hBox, BX_UINT uMsg ,BX_WPARAM wParam, BX_LPARAM lParam);
extern BX_VOID formEditCPPatternUpdate(HBOX hBox);
extern BX_VOID formEditCPPatternInit(HBOX hBox);
#endif // FORMEDITCPPATTERN_H
