//Code generated by bxbuilder (c) LMS 2002 
// formSadsUser.c
#include "Bx.h"
#include "formSads.h"

#include "tmclnx.h"
#include "rs.h"

BX_BOOL formSadsUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDSPEEDA));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDACCELA));
  BxAssignFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDDECELA));
  BxAssignIntValue(BxGetDlgItem(hBox, FORMSADS_CMDSRAMA));

  BxSetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDSPEEDA), GetAktuelSpeed(axis_a));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDACCELA), GetAktuelAccel(axis_a));
  BxSetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDDECELA), GetAktuelDecel(axis_a));
  BxSetIntValue(BxGetDlgItem(hBox, FORMSADS_CMDSRAMA), GetAktuelSramp(axis_a));
  return TRUE;
}

BX_BOOL formSadsUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formSads_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, FALSE);
  return FALSE;
}

BX_BOOL formSads_cmdReturn_Click(HBOX hBox)
{
  BxEndDialog(hBox, TRUE);
  return FALSE;
}

BX_BOOL formSads_cmdSramA_Click(HBOX hBox)
{
  BxVirtNumBox_SetValue(BxGetIntValue(BxGetDlgItem(hBox, FORMSADS_CMDSRAMA)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetIntValue(BxGetDlgItem(hBox, FORMSADS_CMDSRAMA), BxVirtNumBox_GetValue());
  }
  return TRUE;
}

BX_BOOL formSads_cmdDecelA_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDDECELA)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDDECELA), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formSads_cmdAccelA_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDACCELA)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDACCELA), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

BX_BOOL formSads_cmdSpeedA_Click(HBOX hBox)
{
  BxVirtNumBox_SetFloatValue(BxGetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDSPEEDA)));
  if(VirtNumKeyBox( hBox ) == IDOK)
  {
    BxSetFloatValue(BxGetDlgItem(hBox, FORMSADS_CMDSPEEDA), BxVirtNumBox_GetFloatValue());
  }
  return TRUE;
}

