//Code generated by bxbuilder (c) LMS 2002 
// formFileDialogUser.c
#include "Bx.h"
#include "formFileDialog.h"

#ifdef WINDOWS
#include "bxscandir.h"
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <dirent.h>

static BXLISTSTRUCT FileDlgList;
static char currentPath[512] = "";
static BX_BOOL FILE_SELECTED = FALSE;
static BXMENUSTRUCT pBxMenu;

static void setupList(HBOX hBox, char *dir, char *type)
{
#ifdef WINDOWS
  struct bxdirent *namelist, *tptr;
#else
  struct dirent **namelist;
  struct stat dstat;
#endif
  int n, i, j;
  char s[512];

  n = BxList_GetCount(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE));
  for(i=0;i<n;i++)
  {
    BxList_DeleteString( BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), 0);
  }

  n = BxList_GetCount(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTDIR));
  for(i=0;i<n;i++)
  {
    BxList_DeleteString( BxGetDlgItem(hBox, FORMFILEDIALOG_LISTDIR), 0);
  }

#ifdef WINDOWS
  j = n = jscandir( dir, &namelist, NULL, NULL );

  if(n >= 0)
  {
/*
    while(j--)
    {
      stat(namelist[j]->d_name, &dstat);
      if(S_ISDIR(dstat.st_mode))
        namelist[j]->d_type=4;
      else
        namelist[j]->d_type=8;
    }
*/

    for(i=0;i<n;i++)
    {
      tptr = &namelist[i];
      if(tptr->d_type==8)
      {
        sprintf(s,"[ %s ]", tptr->d_name);
        BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTDIR), s);
      }
    }

    for(i=0;i<n;i++)
    {
      tptr = &namelist[i];
      if(tptr->d_type==4)
      {
        sprintf(s," %s", tptr->d_name);
        BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), s);
      }
    }

/*
    for(i=0;i<n;i++)
    {
      stat(namelist[j]->d_name, &dstat);
      if(!(S_ISDIR(dstat.st_mode)))
      if(namelist[i]->d_type==8)
      {
        if(type!=NULL)
        {
          if(strcmp(&namelist[i]->d_name[strlen(namelist[i]->d_name)-strlen(type)], type) == 0)
          {
            sprintf(s,"%s", namelist[i]->d_name);
            s[strlen(namelist[i]->d_name)-strlen(type)-1] = '\0';
            BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), s);
          }
        }
        else
        {
          sprintf(s,"%s", namelist[i]->d_name);
          BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), s);
        }
      }
    }
*/
  }

  freedir(&namelist, n);
#else  
  j = n = scandir( dir, &namelist, 0, alphasort );
  if(n >= 0)
  {
    while(j--)
    {
      stat(namelist[j]->d_name, &dstat);
      if(S_ISDIR(dstat.st_mode))
        namelist[j]->d_type=4;
      else
        namelist[j]->d_type=8;
    }

    for(i=0;i<n;i++)
    {
      stat(namelist[j]->d_name, &dstat);
      if(S_ISDIR(dstat.st_mode))
      if(namelist[i]->d_type==4)
      {
        sprintf(s,"[ %s ]", namelist[i]->d_name);
        BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTDIR), s);
      }
    }
    for(i=0;i<n;i++)
    {
      stat(namelist[j]->d_name, &dstat);
      if(!(S_ISDIR(dstat.st_mode)))
      if(namelist[i]->d_type==8)
      {
        if(type!=NULL)
        {
          if(strcmp(&namelist[i]->d_name[strlen(namelist[i]->d_name)-strlen(type)], type) == 0)
          {
            sprintf(s,"%s", namelist[i]->d_name);
            s[strlen(namelist[i]->d_name)-strlen(type)-1] = '\0';
            BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), s);
          }
        }
        else
        {
          sprintf(s,"%s", namelist[i]->d_name);
          BxList_AddString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), s);
        }
      }
    }
  }
#endif
}

static void initList(HBOX hBox)
{
  FileDlgList.m_ViewPos = 0;
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;

  setupList(hBox, pBxFDlgList->Path, pBxFDlgList->Type);
//  setupList(hBox, ".", pBxFDlgList->Type);
}

BX_BOOL formFileDialogUserInit(HBOX hBox,BX_LPARAM lParam)
{
  ((PBOXSTRUCT)BxGetDlgItem(hBox, FORMFILEDIALOG_CMDFILENAME))->lpBoxStr = currentPath;
  initList(hBox);
  return TRUE;
}

BX_BOOL formFileDialogUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formFileDialog_listFile_Click(HBOX hBox)
{
  BX_CHAR *str;

  if((str = BxList_GetString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE), BxList_GetSelected(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTFILE)))) != NULL )
  {
    BxSetBoxText(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDFILENAME), str);
    FILE_SELECTED = TRUE;
  }

  return TRUE;
}

BX_BOOL formFileDialog_listDir_Click(HBOX hBox)
{
  BX_CHAR *str, dirs[512], newPath[1024];
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;

  if((str = BxList_GetString(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTDIR), BxList_GetSelected(BxGetDlgItem(hBox, FORMFILEDIALOG_LISTDIR)))) != NULL )
  {
    if(str[0] == '[')
    {
      sprintf(dirs, "%s", &str[2]);
      dirs[strlen(dirs)-2]='\0';
      sprintf(newPath,"%s/%s", pBxFDlgList->Path, dirs );
      chdir(newPath);
      getcwd(pBxFDlgList->Path, 512);
      initList(hBox);
      FILE_SELECTED = FALSE;
      BxSetBoxText(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDFILENAME), "");
    }
  }
  return TRUE;
}

BX_BOOL formFileDialog_cmdOk_Click(HBOX hBox)
{
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;
  //BX_PSTRING pStr;
	//  BxGetBoxText(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDFILENAME), pStr,	512);

  if(pBxFDlgList->Type!=NULL)
    sprintf(pBxFDlgList->Filename, "%s/%s.%s", pBxFDlgList->Path, currentPath, pBxFDlgList->Type);
  else
    sprintf(pBxFDlgList->Filename, "%s/%s", pBxFDlgList->Path, currentPath);
  BxEndDialog(hBox, IDOK);
  return TRUE;
}

BX_BOOL formFileDialog_cmdCancel_Click(HBOX hBox)
{
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;

  BxStringCopy(pBxFDlgList->Filename, "");
  BxEndDialog(hBox, IDCANCEL);
  return TRUE;
}

BX_BOOL formFileDialog_cmdCreateDir_Click(HBOX hBox)
{
  BX_PSTRING str;
  BX_CHAR newPath[512];
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;
  
  if(BxVirtualKeyboard( hBox, "", 25)==IDOK)
  {
    str = BxVirtualKeyboard_GetString();
    if(strcmp(str, "") != 0)
    {
      sprintf(newPath,"%s/%s", pBxFDlgList->Path, str );
#ifdef LINUX      
      mkdir(newPath, 0x777);
#else
      mkdir(newPath);
#endif
      chdir(newPath);
      getcwd(pBxFDlgList->Path, 512);
      initList(hBox);
      FILE_SELECTED = FALSE;
      BxSetBoxText(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDFILENAME), "");
    }
  }
  return TRUE;
}

BX_BOOL formFileDialog_cmdFilename_Click(HBOX hBox)
{
  BX_PSTRING str;
  BXFILEDLGSTRUCT *pFDlg = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;

  if(pFDlg->Style==BXFILEDIALOG_SAVE)
  {
    if(BxVirtualKeyboard( hBox, "", 25)==IDOK)
    {
      str = BxVirtualKeyboard_GetString();
      if(strcmp(str, "") != 0)
      {
        BxSetBoxText(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDFILENAME), str);
        FILE_SELECTED = TRUE;
      }
    }
  }
  return TRUE;
}

BX_BOOL formFileDialog_cmdRename_Click(HBOX hBox)
{
/*
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;
  BX_CHAR dirs[512];

  if(pBxFDlgList->Type!=NULL)
    sprintf(pBxFDlgList->Filename, "%s/%s.%s", pBxFDlgList->Path, currentPath, pBxFDlgList->Type);
  else
    sprintf(pBxFDlgList->Filename, "%s/%s", pBxFDlgList->Path, currentPath);

  sprintf(dirs,"About to delete: %s ?", pBxFDlgList->Filename );
  if( IDOK == BxMsgBox(hBox, dirs, "Warning", 0) )
  {
    if(rename(pBxFDlgList->Filename)==0)
    initList(hBox);
  }
*/
  return TRUE;
}

BX_BOOL formFileDialog_cmdDelete_Click(HBOX hBox)
{
  BXFILEDLGSTRUCT *pBxFDlgList = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;
  BX_CHAR dirs[2048];
  
  if(pBxFDlgList->Type!=NULL)
    sprintf(pBxFDlgList->Filename, "%s/%s.%s", pBxFDlgList->Path, currentPath, pBxFDlgList->Type);
  else
    sprintf(pBxFDlgList->Filename, "%s/%s", pBxFDlgList->Path, currentPath);

  sprintf(dirs,"About to delete: %s ?", pBxFDlgList->Filename );
  if( IDOK == BxMsgBox(hBox, dirs, "Warning", 0,"Ok","Cancel") )
  {
    if(remove(pBxFDlgList->Filename)==0)
    initList(hBox);
  }
  return TRUE;
}

BX_BOOL formFileDialog_cmdMenu_Click(HBOX hBox)
{
  BXFILEDLGSTRUCT *pBxFDlg = (BXFILEDLGSTRUCT *)((BOXSTRUCT*)hBox)->m_userData;
  HBOX hBx, hFileTool;

  hBx = BxMenu_Create(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDMENU), &pBxMenu);
  if(pBxFDlg->Style == BXFILEDIALOG_SAVE)
    BxMenu_Add(hBx ,"Create dir", MENU, formFileDialog_cmdCreateDir_Click, TRUE, NULL);
  hFileTool = BxMenu_Add(hBx ,"Tools", SUB, NULL, FILE_SELECTED, NULL);
  BxMenu_Add(hFileTool ,"Rename", MENU, formFileDialog_cmdRename_Click, FILE_SELECTED, NULL);
  BxMenu_Add(hFileTool ,"Delete", MENU, formFileDialog_cmdDelete_Click, FILE_SELECTED, NULL);

  BxMenu_Add(hBx ,"Ok", MENU, formFileDialog_cmdOk_Click, FILE_SELECTED, NULL);
  BxMenu_Add(hBx ,"Cancel", MENU, formFileDialog_cmdCancel_Click, TRUE, NULL);
  DoMenu(BxGetDlgItem(hBox, FORMFILEDIALOG_CMDMENU));
  return TRUE;
}

BX_INT BxFileDialog( HBOX hBox, BXFILEDLGSTRUCT* pFDlg )
{
  HBOX hFileDlg;
  BX_INT rtnVal;

  if(hBox == NULL)
    return -1;

  if(pFDlg == NULL)
    return -1;

  FILE_SELECTED = FALSE;
    
  formFileDialog[0].m_userData = (BX_PVOID)pFDlg;
  hFileDlg = BxCreateDialog(GetAppInstance(hBox), &formFileDialog[0], formFileDialogProc);

  BxSetBoxText(BxGetDlgItem(hFileDlg, FORMFILEDIALOG_CMDFILENAME), pFDlg->Filename);
 
  if(strcmp(pFDlg->Path, "")==0)
    getcwd(pFDlg->Path, 512);

  rtnVal = DoModal(hFileDlg);

  ShowDialogBox(hBox);
  BxUpdateView(hBox);

  return rtnVal;
}
