//Code generated by bxbuilder (c) LMS 2002 
// formMsgBoxUser.c
#include <string.h>
#include "Bx.h"
#include "formMsgBox.h"

static int MaxLineLen=75;
 
BX_BOOL formMsgBoxUserInit(HBOX hBox,BX_LPARAM lParam)
{
  BxAssignStringValue(BxGetDlgItem(hBox, FORMMSGBOX_TEXTCAPTION));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMMSGBOX_TEXTMSGTEXT));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMMSGBOX_TEXTMSGTEXT_2));
  BxAssignStringValue(BxGetDlgItem(hBox, FORMMSGBOX_TEXTMSGTEXT_3));
  return TRUE;
}

BX_BOOL formMsgBoxUserUpdate(HBOX hBox)
{
 return TRUE;
}

BX_BOOL formMsgBox_cmdCancel_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDCANCEL);
  return TRUE;
}

BX_BOOL formMsgBox_cmdOk_Click(HBOX hBox)
{
  BxEndDialog(hBox, IDOK);
  return TRUE;
}

BX_INT BxMsgBox( HBOX hBox, BX_PSTRING lpText, BX_PSTRING lpCaption, BX_UINT uType , BX_PSTRING OkStr, BX_PSTRING CancelStr)
{
	BX_INT mlen;
  HBOX hmsgBox;
  BX_INT rtnVal;
	char line1[128];
	char line2[128];
	char line3[128];
	
  if(hBox == NULL)
    return -1;

  if(lpText==NULL)
    return -1;


  formMsgBox[0].bParent = (PBOXSTRUCT)hBox;

  hmsgBox = BxCreateDialog(GetAppInstance(hBox), &formMsgBox[0], (BXDLGPROC)formMsgBoxProc);

	BxAssignStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_CMDCANCEL));
  BxAssignStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_CMDOK));
	BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_CMDCANCEL), CancelStr);
	BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_CMDOK), OkStr);

	mlen=strlen(lpText);
	if (mlen>MaxLineLen*2)
	{
		strncpy(line3,(lpText+2*MaxLineLen),MaxLineLen);
		line3[MaxLineLen]='\0';
		BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_TEXTMSGTEXT_3), line3);
	}
  else
  {
    line3[0]='\0';
		BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_TEXTMSGTEXT_3), line3);
  }
	if (mlen>MaxLineLen)
	{
		strncpy(line2,(lpText+MaxLineLen),MaxLineLen);
		line2[MaxLineLen]='\0';
		BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_TEXTMSGTEXT_2), line2);
	}
  else
  {
    line2[0]='\0';
		BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_TEXTMSGTEXT_2), line2);
  }
	strncpy(line1,(lpText),MaxLineLen);
	line1[MaxLineLen]='\0';
	BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_TEXTMSGTEXT), line1);
  BxSetStringValue(BxGetDlgItem(hmsgBox, FORMMSGBOX_TEXTCAPTION), lpCaption);

  rtnVal = DoModal(hmsgBox);

  formMsgBox[0].bParent = NULL;

  ShowDialogBox(hBox);
  BxUpdateView(hBox);
  return rtnVal;
}
