IOVERSION 1
ipaddr=192.168.0.170
simulate=1
NumOfModules=17
Type=EHC3020
Name=D4004
InWord1="PS1 IO Data"
InWord2="PS1 IO Status"
InWord3="PS1 Counter Status"
InWord4="PS1 Compare Status"
InWord5="PS1 Encoder"
InWord6="PS1 Capture Value"
OutWord1="PS1 Output Data"
OutWord2="PS1 Input Validation"
OutWord3="PS1 Direct"
OutWord4="PS1 Upper Threshold"
OutWord5="PS1 Lower Threshold"
Type=EHC3020
Name=D4005
InWord1="PS2 IO Data"
InWord2="PS2 IO Status"
InWord3="PS2 Counter Status"
InWord4="PS2 Compare Status"
InWord5="PS2 Encoder"
InWord6="PS2 Capture Value"
OutWord1="PS2 Output Data"
OutWord2="PS2 Input Validation"
OutWord3="PS2 Direct"
OutWord4="PS2 Upper Threshold"
OutWord5="PS2 Lower Threshold"
Type=DDI3610
Name=D1306
InConnect1="PS2 switchBottom"
InConnect2="PS1 switchBottom"
InConnect3="PS1 switchTop"
InConnect4="PS1 foto"
InConnect5=""
InConnect6="Continue button"
Type=DDO3600
Name=D1401
OutConnect1="PS Motor Forward"
OutConnect2="PS Motor Reverse"
OutConnect3=""
OutConnect4=""
OutConnect5="PS1 Motor Enable"
OutConnect6="PS2 Motor Enable"
Type=STB3420DDI
Name=2D3
InConnect1="Pallebane9 Foto"
InConnect2="Pallebane7 Foto"
InConnect3="Pallebane6 FotoAlign"
InConnect4="Pallebane6 FotoRev"
Type=STB3420DDI
Name=2D4
InConnect1="Conveyor2 foto1"
InConnect2="Conveyor2 foto2"
InConnect3="ConveyorOut foto1"
InConnect4="Conv3 foto1"
Type=STB3420DDI
Name=2D5
InConnect1="Pallebane6 FotoTest"
InConnect2=""
InConnect3="Pallemagasin ReadTop"
InConnect4="Pallemagasin ReadBottom"
InConnect5=""
InConnect6=""
Type=STB3420DDI
Name=2D6
InConnect1="Pallemagasin ReadMidLeft"
InConnect2="Pallemagasin ReadMidRight"
InConnect3="Pallemagasin ReadGrib"
InConnect4="Pallemagasin ReadSlip"
Type=STB3600DDO
Name=2D7
OutConnect1="Pallemagasin CylUpLeft"
OutConnect2="Pallemagasin CylDownLeft"
OutConnect3="Pallemagasin CylUpRight"
OutConnect4="Pallemagasin CylDownRight"
OutConnect5="Pallemagasin GribCyl"
OutConnect6="Pallemagasin SlipCyl"
Type=STB3600DDO
Name=2D8
OutConnect1="Conv3 motor"
OutConnect2="PS soft"
OutConnect3="Pallebane6 soft"
OutConnect4="Pallebane6 Cyl"
OutConnect5="Signal net"
OutConnect6=""
Type=STB3600DDO
Name=2D9
OutConnect1="Green Light"
OutConnect2="Yellow Light"
OutConnect3="Red Light"
OutConnect4="Tool Modhold"
OutConnect5="Tool Griber"
OutConnect6="Signal Newtec"
Type=STB3610DDI
Name=3D1
InConnect1="PS foto1"
InConnect2="PS foto2"
InConnect3="PS foto3"
InConnect4=""
InConnect5="PS fotoBottom"
InConnect6="PS switchTop"
Type=EPI2145
Name=3E2
Connect1="Pallebane6 MotorFwd"
Connect2="Pallebane6 MotorRev"
Connect3="Pallemagasin Motor"
Connect4=""
Connect5="Pallebane6 Chain"
Connect6=""
Connect7="Pallebane7 Motor"
Connect8=""
Ready1="Pallebane6 Ready"
Tripped1="Pallebane6 Tripped"
Energized1="Pallebane6 Energized"
Ready2="Pallemagasin Ready"
Tripped2="Pallemagasin Tripped"
Energized2="Pallemagasin Energized"
Ready3="Pallebane6 Chain Ready"
Tripped3="Pallebane6 Chain Tripped"
Energized3="Pallebane6 Chain Energized"
Ready4="Pallebane7 Ready"
Tripped4="Pallebane7 Tripped"
Energized4="Pallebane7 Energized"
Type=EPI2145
Name=3E5
Connect1="Pallebane9 Motor"
Connect2=""
Connect3="PS up"
Connect4="PS down"
Connect5="ConveyorOut motor"
Connect6=""
Connect7="Conveyor2 motor"
Connect8=""
Ready1="Pallebane9 Ready"
Tripped1="Pallebane9 Tripped"
Energized1="Pallebane9 Energized"
Ready2="PS Ready"
Tripped2="PS Tripped"
Energized2="PS Energized"
Ready3="ConveyorOut Ready"
Tripped3="ConveyorOut Tripped"
Energized3="ConveyorOut Energized"
Ready4="Conveyor2 Ready"
Tripped4="Conveyor2 Tripped"
Energized4="Conveyor2 Energized"
Type=EPI2145
Name=4E1
Connect1=""
Connect2=""
Connect3=""
Connect4=""
Connect5=""
Connect6=""
Connect7=""
Connect8=""
Ready1=""
Tripped1=""
Energized1=""
Ready2=""
Tripped2=""
Energized2=""
Ready3=""
Tripped3=""
Energized3=""
Ready4=""
Tripped4=""
Energized4=""
Type=EHC3020
Name=4E3
InWord1="PS IO Data"
InWord2="PS IO Status"
InWord3="PS Counter Status"
InWord4="PS Compare Status"
InWord5="PS Encoder"
InWord6="PS Capture Value"
OutWord1="PS Output Data"
OutWord2="PS Input Validation"
OutWord3="PS Direct"
OutWord4="PS Upper Threshold"
OutWord5="PS Lower Threshold"
Type=STB3610DDI
Name=5D1
InConnect1=""
InConnect2=""
InConnect3=""
InConnect4=""
InConnect5="Pallemagasin Foto"
InConnect6="Pallemagasin FotoMid"
